// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:92588417fa010d48e3954c780a1c7284689923c40fd60ea7464f85cbc75b43eb). DO NOT EDIT.

package v1_mobile_device_groups_smart_group

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// V1MobileDeviceGroupsSmartGroupResourceModel is the Terraform state for a jamfpro_v1_mobile_device_groups_smart_group.
//
// Field order follows the schema, and the timeouts value is last.
type V1MobileDeviceGroupsSmartGroupResourceModel struct {
	Count            types.Int64    `tfsdk:"api_count"`
	Criteria         types.Set      `tfsdk:"criteria"`
	GroupDescription types.String   `tfsdk:"group_description"`
	GroupID          types.String   `tfsdk:"group_id"`
	GroupName        types.String   `tfsdk:"group_name"`
	ID               types.String   `tfsdk:"id"`
	SiteID           types.String   `tfsdk:"site_id"`
	Timeouts         timeouts.Value `tfsdk:"timeouts"`
}

// V1MobileDeviceGroupsSmartGroupSmartGroupCriteriaModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V1MobileDeviceGroupsSmartGroupSmartGroupCriteriaModel struct {
	AndOr        types.String `tfsdk:"and_or"`
	ClosingParen types.Bool   `tfsdk:"closing_paren"`
	Name         types.String `tfsdk:"name"`
	OpeningParen types.Bool   `tfsdk:"opening_paren"`
	Priority     types.Int64  `tfsdk:"priority"`
	SearchType   types.String `tfsdk:"search_type"`
	Value        types.String `tfsdk:"value"`
}

// v1MobileDeviceGroupsSmartGroupSmartGroupCriteriaAttrTypes describes V1MobileDeviceGroupsSmartGroupSmartGroupCriteriaModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v1MobileDeviceGroupsSmartGroupSmartGroupCriteriaAttrTypes = map[string]attr.Type{
	"and_or":        types.StringType,
	"closing_paren": types.BoolType,
	"name":          types.StringType,
	"opening_paren": types.BoolType,
	"priority":      types.Int64Type,
	"search_type":   types.StringType,
	"value":         types.StringType,
}

var v1MobileDeviceGroupsSmartGroupSmartGroupCriteriaObjectType = types.ObjectType{AttrTypes: v1MobileDeviceGroupsSmartGroupSmartGroupCriteriaAttrTypes}
