# Code generated by tfpfgen from blueprints/jamfpro
# (sha256:e29c3c55fac9427f0859dfeab08822cf7cbca1463246f5d9cdeb8393ab9d2a4c). DO NOT EDIT.

# The seed resource this data source reads back, then the data block itself. One file,
# because the reference below only resolves against the resource above it.

resource "jamfpro_v1_self_service_branding_io" "test" {
  branding_name                = "tfacc-ds-v1_self_service_branding_io-branding-name"
  branding_name_color_code     = "tfacc-ds-v1_self_service_branding_io-branding-name-color-code"
  header_background_color_code = "tfacc-ds-v1_self_service_branding_io-header-background-color-code"
  menu_icon_color_code         = "tfacc-ds-v1_self_service_branding_io-menu-icon-color-code"
  status_bar_text_color        = "tfacc-ds-v1_self_service_branding_io-status-bar-text-color"
}

# The propagation wait. An API that accepts a create does not always serve the object
# to the next reader immediately, and a data source is the next reader: without this the
# test races the tenant's own consistency and fails intermittently, which is worse than
# failing always. Expressed as a resource rather than a sleep in Go so the dependency is
# something Terraform orders, not something the test framework hopes for.
resource "time_sleep" "wait_for_v1_self_service_branding_io" {
  depends_on      = [jamfpro_v1_self_service_branding_io.test]
  create_duration = "15s"
}

data "jamfpro_v1_self_service_branding_io" "test" {
  id = jamfpro_v1_self_service_branding_io.test.id

  depends_on = [time_sleep.wait_for_v1_self_service_branding_io]
}
