// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:e29c3c55fac9427f0859dfeab08822cf7cbca1463246f5d9cdeb8393ab9d2a4c). DO NOT EDIT.

package v2_computer_groups_static_group

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/client"
	sdk "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk"
	commonschema "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/services/common/schema"
)

const (
	// TypeName is the Terraform type this resource registers as.
	TypeName = "jamfpro_v2_computer_groups_static_group"

	// Default per-operation timeouts, in seconds. A practitioner overrides them
	// with the resource's timeouts block.
	CreateTimeout = 180
	ReadTimeout   = 180
	UpdateTimeout = 180
	DeleteTimeout = 180
)

// Compile-time assertions that this resource implements what it claims to. They
// turn a missing method into a build failure rather than a runtime surprise.
var (
	_ resource.Resource                = (*V2ComputerGroupsStaticGroupResource)(nil)
	_ resource.ResourceWithConfigure   = (*V2ComputerGroupsStaticGroupResource)(nil)
	_ resource.ResourceWithImportState = (*V2ComputerGroupsStaticGroupResource)(nil)
)

// NewV2ComputerGroupsStaticGroupResource returns the jamfpro_v2_computer_groups_static_group resource.
func NewV2ComputerGroupsStaticGroupResource() resource.Resource {
	return &V2ComputerGroupsStaticGroupResource{}
}

// V2ComputerGroupsStaticGroupResource implements the jamfpro_v2_computer_groups_static_group resource.
type V2ComputerGroupsStaticGroupResource struct {
	client *sdk.JamfProClient
}

// Metadata returns the resource type name.
func (r *V2ComputerGroupsStaticGroupResource) Metadata(_ context.Context, _ resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TypeName
}

// Configure receives the configured SDK client from the provider.
func (r *V2ComputerGroupsStaticGroupResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = client.ForResource(ctx, req, resp, TypeName)
}

// ImportState maps a terraform import into state.
func (r *V2ComputerGroupsStaticGroupResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// Schema returns the resource schema.
func (r *V2ComputerGroupsStaticGroupResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Get Static Computer Group by Id.",
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"site_id": schema.StringAttribute{
				Optional: true,
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": commonschema.ResourceTimeouts(ctx),
		},
	}
}
