# Code generated by tfpluginframeworkgen from blueprints/thousandeyes
# (sha256:9a41e8e4f04fc72967fb98f9a911e934252f8b0971b3c4ac1326510fed33d2d0). DO NOT EDIT.

# The seed resource, the ephemeral that opens it, and the echo that makes the opened
# value observable. One file, because each reference only resolves against the block
# above it. The echo provider is HashiCorp's test fixture for exactly this: an ephemeral
# value never reaches state, so a test needs somewhere else to read it from.

resource "thousandeyes_credential" "test" {
  name  = "tfacc-eph-credential-name"
  value = "tfacc-eph-credential-value"
}

ephemeral "thousandeyes_credential" "test" {
  id = thousandeyes_credential.test.id
}

provider "echo" {
  data = ephemeral.thousandeyes_credential.test
}

resource "echo" "test" {}
