// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:92588417fa010d48e3954c780a1c7284689923c40fd60ea7464f85cbc75b43eb). DO NOT EDIT.

package v1_building

import (
	"context"

	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/services/common/convert"
)

// constructResource maps Terraform configuration onto the API's request body.
//
// Only writable attributes appear here. A computed attribute has no expand
// conversion, so it cannot be sent by construction rather than by discipline.
func constructResource(ctx context.Context, data *V1BuildingResourceModel) *models.Building {
	tflog.Debug(ctx, "constructing request body", map[string]any{"resource": TypeName})

	body := models.NewBuilding()

	body.SetCity(convert.FrameworkToPtrString(data.City))
	body.SetCountry(convert.FrameworkToPtrString(data.Country))
	body.SetName(convert.FrameworkToPtrString(data.Name))
	body.SetStateProvince(convert.FrameworkToPtrString(data.StateProvince))
	body.SetStreetAddress1(convert.FrameworkToPtrString(data.StreetAddress1))
	body.SetStreetAddress2(convert.FrameworkToPtrString(data.StreetAddress2))
	body.SetZipPostalCode(convert.FrameworkToPtrString(data.ZipPostalCode))

	return body
}
