// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:92588417fa010d48e3954c780a1c7284689923c40fd60ea7464f85cbc75b43eb). DO NOT EDIT.

package v2_patch_policy

import (
	"context"

	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/services/common/convert"
)

// mapRemoteStateToTerraform maps the API's response onto Terraform state.
//
// This function replaces what a reflection-based provider does at runtime. Being
// generated code, a field whose conversion is wrong is a compile error rather
// than a surprise during apply.
func mapRemoteStateToTerraform(ctx context.Context, data *V2PatchPolicyDataSourceModel, remote models.PatchPolicyListViewable) {
	if remote == nil {
		tflog.Debug(ctx, "remote object is nil, leaving state untouched", map[string]any{
			"dataSource": TypeName,
		})
		return
	}

	data.Completed = convert.PtrInt32ToFrameworkInt64(remote.GetCompleted())
	data.Deferred = convert.PtrInt32ToFrameworkInt64(remote.GetDeferred())
	data.Failed = convert.PtrInt32ToFrameworkInt64(remote.GetFailed())
	data.ID = convert.PtrStringToFramework(remote.GetId())
	data.Pending = convert.PtrInt32ToFrameworkInt64(remote.GetPending())
	data.PolicyDeploymentMethod = convert.PtrStringToFramework(remote.GetPolicyDeploymentMethod())
	data.PolicyEnabled = convert.PtrBoolToFramework(remote.GetPolicyEnabled())
	data.PolicyName = convert.PtrStringToFramework(remote.GetPolicyName())
	data.PolicyTargetVersion = convert.PtrStringToFramework(remote.GetPolicyTargetVersion())
	data.SoftwareTitle = convert.PtrStringToFramework(remote.GetSoftwareTitle())
	data.SoftwareTitleConfigurationID = convert.PtrStringToFramework(remote.GetSoftwareTitleConfigurationId())

	tflog.Debug(ctx, "mapped remote state", map[string]any{"dataSource": TypeName})
}
