// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:92588417fa010d48e3954c780a1c7284689923c40fd60ea7464f85cbc75b43eb). DO NOT EDIT.

package v1_app_store_country_code

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// V1AppStoreCountryCodeDataSourceModel is the Terraform state for a jamfpro_v1_app_store_country_code.
//
// Field order follows the schema, and the timeouts value is last.
type V1AppStoreCountryCodeDataSourceModel struct {
	Code     types.String   `tfsdk:"code"`
	Name     types.String   `tfsdk:"name"`
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}
