// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:92588417fa010d48e3954c780a1c7284689923c40fd60ea7464f85cbc75b43eb). DO NOT EDIT.

package v2_mobile_device_prestage

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/services/common/convert"
)

// mapRemoteStateToTerraform maps the API's response onto Terraform state.
//
// This function replaces what a reflection-based provider does at runtime. Being
// generated code, a field whose conversion is wrong is a compile error rather
// than a surprise during apply.
func mapRemoteStateToTerraform(ctx context.Context, data *V2MobileDevicePrestageResourceModel, remote models.GetMobileDevicePrestageV2able) diag.Diagnostics {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)

	if remote == nil {
		tflog.Debug(ctx, "remote resource is nil, leaving state untouched", map[string]any{
			"resource": TypeName,
		})
		return diags
	}

	data.AllowPairing = convert.PtrBoolToFramework(remote.GetAllowPairing())
	data.AnchorCertificates, d = convert.StringSliceToFrameworkSet(ctx, remote.GetAnchorCertificates())
	diags.Append(d...)
	data.AuthenticationPrompt = convert.PtrStringToFramework(remote.GetAuthenticationPrompt())
	data.AutoAdvanceSetup = convert.PtrBoolToFramework(remote.GetAutoAdvanceSetup())
	data.ConfigureDeviceBeforeSetupAssistant = convert.PtrBoolToFramework(remote.GetConfigureDeviceBeforeSetupAssistant())
	data.DefaultPrestage = convert.PtrBoolToFramework(remote.GetDefaultPrestage())
	data.Department = convert.PtrStringToFramework(remote.GetDepartment())
	data.DeviceEnrollmentProgramInstanceID = convert.PtrStringToFramework(remote.GetDeviceEnrollmentProgramInstanceId())
	data.DisplayName = convert.PtrStringToFramework(remote.GetDisplayName())
	data.EnableDeviceBasedActivationLock = convert.PtrBoolToFramework(remote.GetEnableDeviceBasedActivationLock())
	data.EnforceTemporarySessionTimeout = convert.PtrBoolToFramework(remote.GetEnforceTemporarySessionTimeout())
	data.EnforceUserSessionTimeout = convert.PtrBoolToFramework(remote.GetEnforceUserSessionTimeout())
	data.EnrollmentCustomizationID = convert.PtrStringToFramework(remote.GetEnrollmentCustomizationId())
	data.EnrollmentSiteID = convert.PtrStringToFramework(remote.GetEnrollmentSiteId())
	data.ID = convert.PtrStringToFramework(remote.GetId())
	data.KeepExistingLocationInformation = convert.PtrBoolToFramework(remote.GetKeepExistingLocationInformation())
	data.KeepExistingSiteMembership = convert.PtrBoolToFramework(remote.GetKeepExistingSiteMembership())
	data.Language = convert.PtrStringToFramework(remote.GetLanguage())
	data.LocationInformation, d = flattenV2MobileDevicePrestageLocationInformationV2(ctx, remote.GetLocationInformation())
	diags.Append(d...)
	data.Mandatory = convert.PtrBoolToFramework(remote.GetMandatory())
	data.MaximumSharedAccounts = convert.PtrInt32ToFrameworkInt64(remote.GetMaximumSharedAccounts())
	data.MdmRemovable = convert.PtrBoolToFramework(remote.GetMdmRemovable())
	data.MinimumOSSpecificVersionIos = convert.PtrStringToFramework(remote.GetMinimumOsSpecificVersionIos())
	data.MinimumOSSpecificVersionIpad = convert.PtrStringToFramework(remote.GetMinimumOsSpecificVersionIpad())
	data.MultiUser = convert.PtrBoolToFramework(remote.GetMultiUser())
	data.Names, d = flattenV2MobileDevicePrestageMobileDevicePrestageNamesV2(ctx, remote.GetNames())
	diags.Append(d...)
	data.PrestageMinimumOSTargetVersionTypeIos = convert.PtrStringerToFramework(remote.GetPrestageMinimumOsTargetVersionTypeIos())
	data.PrestageMinimumOSTargetVersionTypeIpad = convert.PtrStringerToFramework(remote.GetPrestageMinimumOsTargetVersionTypeIpad())
	data.PreventActivationLock = convert.PtrBoolToFramework(remote.GetPreventActivationLock())
	data.ProfileUUID = convert.PtrStringToFramework(remote.GetProfileUuid())
	data.PurchasingInformation, d = flattenV2MobileDevicePrestagePrestagePurchasingInformationV2(ctx, remote.GetPurchasingInformation())
	diags.Append(d...)
	data.Region = convert.PtrStringToFramework(remote.GetRegion())
	data.RequireAuthentication = convert.PtrBoolToFramework(remote.GetRequireAuthentication())
	data.RtsConfigProfileID = convert.PtrStringToFramework(remote.GetRtsConfigProfileId())
	data.RtsEnabled = convert.PtrBoolToFramework(remote.GetRtsEnabled())
	data.SendTimezone = convert.PtrBoolToFramework(remote.GetSendTimezone())
	data.SiteID = convert.PtrStringToFramework(remote.GetSiteId())
	data.StorageQuotaSizeMegabytes = convert.PtrInt32ToFrameworkInt64(remote.GetStorageQuotaSizeMegabytes())
	data.Supervised = convert.PtrBoolToFramework(remote.GetSupervised())
	data.SupportEmailAddress = convert.PtrStringToFramework(remote.GetSupportEmailAddress())
	data.SupportPhoneNumber = convert.PtrStringToFramework(remote.GetSupportPhoneNumber())
	data.TemporarySessionOnly = convert.PtrBoolToFramework(remote.GetTemporarySessionOnly())
	data.TemporarySessionTimeout = convert.PtrInt32ToFrameworkInt64(remote.GetTemporarySessionTimeout())
	data.Timezone = convert.PtrStringToFramework(remote.GetTimezone())
	data.UseStorageQuotaSize = convert.PtrBoolToFramework(remote.GetUseStorageQuotaSize())
	data.UserSessionTimeout = convert.PtrInt32ToFrameworkInt64(remote.GetUserSessionTimeout())
	data.VersionLock = convert.PtrInt32ToFrameworkInt64(remote.GetVersionLock())

	tflog.Debug(ctx, "mapped remote state", map[string]any{"resource": TypeName})

	return diags
}

// flattenV2MobileDevicePrestageLocationInformationV2 converts SDK structs into the framework value state holds.
func flattenV2MobileDevicePrestageLocationInformationV2(ctx context.Context, in models.LocationInformationV2able) (types.Object, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in == nil {
		return types.ObjectNull(v2MobileDevicePrestageLocationInformationV2ObjectType.AttrTypes), diags
	}

	item := in

	var m V2MobileDevicePrestageLocationInformationV2Model

	m.BuildingID = convert.PtrStringToFramework(item.GetBuildingId())
	m.DepartmentID = convert.PtrStringToFramework(item.GetDepartmentId())
	m.Email = convert.PtrStringToFramework(item.GetEmail())
	m.ID = convert.PtrStringToFramework(item.GetId())
	m.Phone = convert.PtrStringToFramework(item.GetPhone())
	m.Position = convert.PtrStringToFramework(item.GetPosition())
	m.Realname = convert.PtrStringToFramework(item.GetRealname())
	m.Room = convert.PtrStringToFramework(item.GetRoom())
	m.Username = convert.PtrStringToFramework(item.GetUsername())
	m.VersionLock = convert.PtrInt32ToFrameworkInt64(item.GetVersionLock())

	out, d2 := types.ObjectValueFrom(ctx, v2MobileDevicePrestageLocationInformationV2ObjectType.AttrTypes, m)
	diags.Append(d2...)

	return out, diags
}

// flattenV2MobileDevicePrestageMobileDevicePrestageNamesV2 converts SDK structs into the framework value state holds.
func flattenV2MobileDevicePrestageMobileDevicePrestageNamesV2(ctx context.Context, in models.MobileDevicePrestageNamesV2able) (types.Object, diag.Diagnostics) {
	var diags diag.Diagnostics
	var d diag.Diagnostics

	if in == nil {
		return types.ObjectNull(v2MobileDevicePrestageMobileDevicePrestageNamesV2ObjectType.AttrTypes), diags
	}

	item := in

	var m V2MobileDevicePrestageMobileDevicePrestageNamesV2Model

	m.AssignNamesUsing = convert.PtrStringToFramework(item.GetAssignNamesUsing())
	m.DeviceNamePrefix = convert.PtrStringToFramework(item.GetDeviceNamePrefix())
	m.DeviceNameSuffix = convert.PtrStringToFramework(item.GetDeviceNameSuffix())
	m.DeviceNamingConfigured = convert.PtrBoolToFramework(item.GetDeviceNamingConfigured())
	m.ManageNames = convert.PtrBoolToFramework(item.GetManageNames())
	m.PrestageDeviceNames, d = flattenV2MobileDevicePrestageMobileDevicePrestageNameV2s(ctx, item.GetPrestageDeviceNames())
	diags.Append(d...)
	m.SingleDeviceName = convert.PtrStringToFramework(item.GetSingleDeviceName())

	out, d2 := types.ObjectValueFrom(ctx, v2MobileDevicePrestageMobileDevicePrestageNamesV2ObjectType.AttrTypes, m)
	diags.Append(d2...)

	return out, diags
}

// flattenV2MobileDevicePrestageMobileDevicePrestageNameV2s converts SDK structs into the framework value state holds.
func flattenV2MobileDevicePrestageMobileDevicePrestageNameV2s(ctx context.Context, in []models.MobileDevicePrestageNameV2able) (types.Set, diag.Diagnostics) {
	var diags diag.Diagnostics

	// A nil slice is null and an empty slice is empty. Conflating them produces a
	// diff no configuration change can resolve.
	if in == nil {
		return types.SetNull(v2MobileDevicePrestageMobileDevicePrestageNameV2ObjectType), diags
	}

	elements := make([]V2MobileDevicePrestageMobileDevicePrestageNameV2Model, 0, len(in))
	for _, item := range in {
		var m V2MobileDevicePrestageMobileDevicePrestageNameV2Model

		m.DeviceName = convert.PtrStringToFramework(item.GetDeviceName())
		m.ID = convert.PtrStringToFramework(item.GetId())
		m.Used = convert.PtrBoolToFramework(item.GetUsed())
		elements = append(elements, m)
	}

	out, d2 := types.SetValueFrom(ctx, v2MobileDevicePrestageMobileDevicePrestageNameV2ObjectType, elements)
	diags.Append(d2...)

	return out, diags
}

// flattenV2MobileDevicePrestagePrestagePurchasingInformationV2 converts SDK structs into the framework value state holds.
func flattenV2MobileDevicePrestagePrestagePurchasingInformationV2(ctx context.Context, in models.PrestagePurchasingInformationV2able) (types.Object, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in == nil {
		return types.ObjectNull(v2MobileDevicePrestagePrestagePurchasingInformationV2ObjectType.AttrTypes), diags
	}

	item := in

	var m V2MobileDevicePrestagePrestagePurchasingInformationV2Model

	m.AppleCareID = convert.PtrStringToFramework(item.GetAppleCareId())
	m.ID = convert.PtrStringToFramework(item.GetId())
	m.LeaseDate = convert.PtrStringToFramework(item.GetLeaseDate())
	m.Leased = convert.PtrBoolToFramework(item.GetLeased())
	m.LifeExpectancy = convert.PtrInt32ToFrameworkInt64(item.GetLifeExpectancy())
	m.PoDate = convert.PtrStringToFramework(item.GetPoDate())
	m.PoNumber = convert.PtrStringToFramework(item.GetPoNumber())
	m.PurchasePrice = convert.PtrStringToFramework(item.GetPurchasePrice())
	m.Purchased = convert.PtrBoolToFramework(item.GetPurchased())
	m.PurchasingAccount = convert.PtrStringToFramework(item.GetPurchasingAccount())
	m.PurchasingContact = convert.PtrStringToFramework(item.GetPurchasingContact())
	m.Vendor = convert.PtrStringToFramework(item.GetVendorEscaped())
	m.VersionLock = convert.PtrInt32ToFrameworkInt64(item.GetVersionLock())
	m.WarrantyDate = convert.PtrStringToFramework(item.GetWarrantyDate())

	out, d2 := types.ObjectValueFrom(ctx, v2MobileDevicePrestagePrestagePurchasingInformationV2ObjectType.AttrTypes, m)
	diags.Append(d2...)

	return out, diags
}
