// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:c061d4e55f595ea8cadc584fbf37787c1ad11526b7593404cb3d18442e845360). DO NOT EDIT.

package tests_http_server

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/thousandeyes_api/http_server_tests"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/services/common/convert"
)

// constructResource maps Terraform configuration onto the API's request body.
//
// Only writable attributes appear here. A computed attribute has no expand
// conversion, so it cannot be sent by construction rather than by discipline.
func constructResource(ctx context.Context, data *TestsHTTPServerResourceModel) (*http_server_tests.HttpServerTestRequest, diag.Diagnostics) {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)
	tflog.Debug(ctx, "constructing request body", map[string]any{"resource": TypeName})

	body := &http_server_tests.HttpServerTestRequest{}

	body.AlertsEnabled = convert.FrameworkToPtrBool(data.AlertsEnabled)
	body.AllowUnsafeLegacyRenegotiation = convert.FrameworkToNamedBool[http_server_tests.TestAllowUnsafeLegacyRenegotiation](data.AllowUnsafeLegacyRenegotiation)
	body.AuthType = convert.FrameworkToEnum[http_server_tests.TestAuthType](data.AuthType)
	body.BandwidthMeasurements = convert.FrameworkToNamedBool[http_server_tests.TestBandwidthMeasurements](data.BandwidthMeasurements)
	body.BgpMeasurements = convert.FrameworkToNamedBool[http_server_tests.TestBgpMeasurements](data.BGPMeasurements)
	body.ClientCertificate = convert.FrameworkToEnum[http_server_tests.TestClientCertificate](data.ClientCertificate)
	body.CollectProxyNetworkData = convert.FrameworkToNamedBool[http_server_tests.TestCollectProxyNetworkData](data.CollectProxyNetworkData)
	body.ContentRegex = convert.FrameworkToPtrString(data.ContentRegex)
	body.Description = convert.FrameworkToPtrString(data.Description)
	body.DesiredStatusCode = convert.FrameworkToEnum[http_server_tests.TestDesiredStatusCode](data.DesiredStatusCode)
	body.DistributedTracing = convert.FrameworkToNamedBool[http_server_tests.TestDistributedTracing](data.DistributedTracing)
	body.DnsOverride = convert.FrameworkToPtrString(data.DNSOverride)
	body.DownloadLimit = convert.FrameworkToPtrNamedInt[int](data.DownloadLimit)
	body.Enabled = convert.FrameworkToNamedBool[http_server_tests.Enabled](data.Enabled)
	body.FixedPacketRate = convert.FrameworkToIntEnum[http_server_tests.TestFixedPacketRate](data.FixedPacketRate)
	body.FollowRedirects = convert.FrameworkToNamedBool[http_server_tests.TestFollowRedirects](data.FollowRedirects)
	body.Headers, d = convert.FrameworkSetToStringSlice(ctx, data.Headers)
	diags.Append(d...)
	body.HttpTargetTime = convert.FrameworkToIntEnum[http_server_tests.TestHttpTargetTime](data.HTTPTargetTime)
	body.HttpTimeLimit = convert.FrameworkToIntEnum[http_server_tests.TestHttpTimeLimit](data.HTTPTimeLimit)
	body.HttpVersion = convert.FrameworkToIntEnum[http_server_tests.TestHttpVersion](data.HTTPVersion)
	body.IncludeHeaders = convert.FrameworkToNamedBool[http_server_tests.TestIncludeHeaders](data.IncludeHeaders)
	body.Interval = convert.FrameworkToIntEnum[http_server_tests.TestInterval](data.Interval)
	body.Ipv6Policy = convert.FrameworkToEnum[http_server_tests.TestIpv6Policy](data.Ipv6Policy)
	body.MtuMeasurements = convert.FrameworkToNamedBool[http_server_tests.TestMtuMeasurements](data.MTUMeasurements)
	body.NumPathTraces = convert.FrameworkToIntEnum[http_server_tests.TestNumPathTraces](data.NumPathTraces)
	body.OverrideAgentProxy = convert.FrameworkToNamedBool[http_server_tests.TestOverrideAgentProxy](data.OverrideAgentProxy)
	body.OverrideProxyID = convert.FrameworkToEnum[http_server_tests.TestOverrideProxyId](data.OverrideProxyID)
	body.Password = convert.FrameworkToEnum[http_server_tests.TestPassword](data.Password)
	body.PathTraceMode = convert.FrameworkToEnum[http_server_tests.TestPathTraceMode](data.PathTraceMode)
	body.PostBody = convert.FrameworkToPtrString(data.PostBody)
	body.ProbeMode = convert.FrameworkToEnum[http_server_tests.TestProbeMode](data.ProbeMode)
	body.Protocol = convert.FrameworkToEnum[http_server_tests.TestProtocol](data.Protocol)
	body.RandomizedStartTime = convert.FrameworkToNamedBool[http_server_tests.TestRandomizedStartTime](data.RandomizedStartTime)
	body.RequestMethod = convert.FrameworkToEnum[http_server_tests.RequestMethod](data.RequestMethod)
	body.SslVersionID = convert.FrameworkToEnum[http_server_tests.TestSslVersionId](data.SSLVersionID)
	body.TestName = convert.FrameworkToPtrString(data.TestName)
	body.URL = convert.FrameworkToEnum[http_server_tests.TestUrl](data.URL)
	body.UseNtlm = convert.FrameworkToNamedBool[http_server_tests.TestUseNtlm](data.UseNtlm)
	body.UsePublicBGP = convert.FrameworkToNamedBool[http_server_tests.TestUsePublicBgp](data.UsePublicBGP)
	body.UserAgent = convert.FrameworkToEnum[http_server_tests.TestUserAgent](data.UserAgent)
	body.Username = convert.FrameworkToEnum[http_server_tests.TestUsername](data.Username)
	body.VaultCredentials, d = expandTestsHTTPServerTestVaultCredentials(ctx, data.VaultCredentials)
	diags.Append(d...)
	body.VerifyCertificate = convert.FrameworkToNamedBool[http_server_tests.TestVerifyCertificate](data.VerifyCertificate)
	body.Agents, d = expandHttpServerAgents(ctx, data.Agents)
	diags.Append(d...)

	return body, diags
}

// expandTestsHTTPServerTestVaultCredentials converts the configured TestsHTTPServerTestVaultCredentialModel values into SDK structs.
func expandTestsHTTPServerTestVaultCredentials(ctx context.Context, v types.Set) ([]http_server_tests.TestVaultCredential, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Null and unknown both yield nil so the field is omitted from the request,
	// which is distinct from an empty collection asking the API to clear it.
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var elements []TestsHTTPServerTestVaultCredentialModel
	diags.Append(v.ElementsAs(ctx, &elements, false)...)
	if diags.HasError() {
		return nil, diags
	}

	out := make([]http_server_tests.TestVaultCredential, 0, len(elements))
	for _, m := range elements {
		var item http_server_tests.TestVaultCredential

		item.SecretID = convert.FrameworkToPtrString(m.SecretID)
		item.Target = convert.FrameworkToEnum[http_server_tests.TestVaultCredentialTarget](m.Target)
		out = append(out, item)
	}

	return out, diags
}

// expandHttpServerAgents converts the configured HttpServerAgentModel values into SDK structs.
func expandHttpServerAgents(ctx context.Context, v types.Set) ([]http_server_tests.TestAgentRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Null and unknown both yield nil so the field is omitted from the request,
	// which is distinct from an empty collection asking the API to clear it.
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var elements []HttpServerAgentModel
	diags.Append(v.ElementsAs(ctx, &elements, false)...)
	if diags.HasError() {
		return nil, diags
	}

	out := make([]http_server_tests.TestAgentRequest, 0, len(elements))
	for _, m := range elements {
		var item http_server_tests.TestAgentRequest

		item.AgentID = convert.FrameworkToString(m.AgentID)
		out = append(out, item)
	}

	return out, diags
}
