// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:cd019f12be32331be882ccdbb92a8c651d1dd5bad8c0cb209bba818d3b11f7b4). DO NOT EDIT.

package tests_http_server

import (
	"context"

	"github.com/hashicorp/terraform-plugin-testing/terraform"

	thousandeyes "github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/acceptance/exists"
)

// TestsHTTPServerTestResource answers whether a thousandeyes_tests_http_server is really in the API.
//
// In a _test.go file rather than an ordinary one, so no test scaffolding reaches a built
// provider. An external _test package still sees the exported identifiers of a package's own
// test files, which is what lets the generated acceptance test refer to this.
type TestsHTTPServerTestResource struct{}

// Exists reads the object back through the same operation the resource's Read uses.
//
// Deliberately the same call rather than an equivalent one. A check that asked a list endpoint
// instead could report an object present while the read the provider actually depends on was
// broken, which is the failure an acceptance test exists to catch.
func (TestsHTTPServerTestResource) Exists(
	ctx context.Context,
	state *terraform.InstanceState,
) (*bool, error) {
	return exists.Check(ctx, state, func(
		ctx context.Context,
		client *thousandeyes.Client,
		state *terraform.InstanceState,
	) error {
		_, _, err := client.API.HTTPServerTests.GetHttpServerTest(ctx, state.ID)

		return err
	})
}
