// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:0b953207edd3d864e6bfc30d40b3efd5bbb9451891d33150e8223a4769f7955f). DO NOT EDIT.

package tests_agent_to_server

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/thousandeyes_api/agent_to_server_tests"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/services/common/convert"
)

// constructResource maps Terraform configuration onto the API's request body.
//
// Only writable attributes appear here. A computed attribute has no expand
// conversion, so it cannot be sent by construction rather than by discipline.
func constructResource(ctx context.Context, data *TestsAgentToServerResourceModel) (*agent_to_server_tests.AgentToServerTestRequest, diag.Diagnostics) {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)
	tflog.Debug(ctx, "constructing request body", map[string]any{"resource": ResourceName})

	body := &agent_to_server_tests.AgentToServerTestRequest{}

	body.AlertsEnabled = convert.FrameworkToPtrBool(data.AlertsEnabled)
	body.BandwidthMeasurements = convert.FrameworkToNamedBool[agent_to_server_tests.TestBandwidthMeasurements](data.BandwidthMeasurements)
	body.BgpMeasurements = convert.FrameworkToNamedBool[agent_to_server_tests.TestBgpMeasurements](data.BGPMeasurements)
	body.ContinuousMode = convert.FrameworkToPtrBool(data.ContinuousMode)
	body.Description = convert.FrameworkToPtrString(data.Description)
	body.DscpID = convert.FrameworkToEnum[agent_to_server_tests.TestDscpId](data.DscpID)
	body.Enabled = convert.FrameworkToNamedBool[agent_to_server_tests.Enabled](data.Enabled)
	body.FixedPacketRate = convert.FrameworkToPtrNamedInt[int](data.FixedPacketRate)
	body.Interval = convert.FrameworkToIntEnum[agent_to_server_tests.TestInterval](data.Interval)
	body.Ipv6Policy = convert.FrameworkToEnum[agent_to_server_tests.TestIpv6Policy](data.Ipv6Policy)
	body.MtuMeasurements = convert.FrameworkToNamedBool[agent_to_server_tests.TestMtuMeasurements](data.MTUMeasurements)
	body.NetworkMeasurements = convert.FrameworkToPtrBool(data.NetworkMeasurements)
	body.NumPathTraces = convert.FrameworkToIntEnum[agent_to_server_tests.TestNumPathTraces](data.NumPathTraces)
	body.PathTraceMode = convert.FrameworkToEnum[agent_to_server_tests.TestPathTraceMode](data.PathTraceMode)
	body.PingPayloadSize = convert.FrameworkToPtrNamedInt[int](data.PingPayloadSize)
	body.Port = convert.FrameworkToPtrNamedInt[int](data.Port)
	body.ProbeMode = convert.FrameworkToEnum[agent_to_server_tests.TestProbeMode](data.ProbeMode)
	body.Protocol = convert.FrameworkToEnum[agent_to_server_tests.TestProtocol](data.Protocol)
	body.RandomizedStartTime = convert.FrameworkToNamedBool[agent_to_server_tests.TestRandomizedStartTime](data.RandomizedStartTime)
	body.Server = convert.FrameworkToString(data.Server)
	body.TestName = convert.FrameworkToPtrString(data.TestName)
	body.UsePublicBGP = convert.FrameworkToNamedBool[agent_to_server_tests.TestUsePublicBgp](data.UsePublicBGP)
	body.Agents, d = expandAgentToServerAgents(ctx, data.Agents)
	diags.Append(d...)

	return body, diags
}

// expandAgentToServerAgents converts the configured AgentToServerAgentModel values into SDK structs.
func expandAgentToServerAgents(ctx context.Context, v types.Set) ([]agent_to_server_tests.TestAgentRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Null and unknown both yield nil so the field is omitted from the request,
	// which is distinct from an empty collection asking the API to clear it.
	if v.IsNull() || v.IsUnknown() {
		return nil, diags
	}

	var models []AgentToServerAgentModel
	diags.Append(v.ElementsAs(ctx, &models, false)...)
	if diags.HasError() {
		return nil, diags
	}

	out := make([]agent_to_server_tests.TestAgentRequest, 0, len(models))
	for _, m := range models {
		var item agent_to_server_tests.TestAgentRequest

		item.AgentID = convert.FrameworkToString(m.AgentID)
		out = append(out, item)
	}

	return out, diags
}
