// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:d15e84515fb216029c5660b1c6b6ccf320bd6d606db78d76d5abbd3fac5185fc). DO NOT EDIT.

package tests_agent_to_server

import (
	"context"

	"github.com/hashicorp/terraform-plugin-testing/terraform"

	thousandeyes "github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/acceptance/exists"
)

// TestsAgentToServerTestResource answers whether a thousandeyes_tests_agent_to_server is really in the API.
//
// In a _test.go file rather than an ordinary one, so no test scaffolding reaches a built
// provider. An external _test package still sees the exported identifiers of a package's own
// test files, which is what lets the generated acceptance test refer to this.
type TestsAgentToServerTestResource struct{}

// Exists reads the object back through the same operation the resource's Read uses.
//
// Deliberately the same call rather than an equivalent one. A check that asked a list endpoint
// instead could report an object present while the read the provider actually depends on was
// broken, which is the failure an acceptance test exists to catch.
func (TestsAgentToServerTestResource) Exists(
	ctx context.Context,
	state *terraform.InstanceState,
) (*bool, error) {
	return exists.Check(ctx, state, func(
		ctx context.Context,
		client *thousandeyes.Client,
		state *terraform.InstanceState,
	) error {
		_, _, err := client.API.AgentToServerTests.GetAgentToServerTest(ctx, state.ID)

		return err
	})
}
