// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ApiRolePrivilegesSearchRequestBuilder builds and executes requests for operations under \v1\api-role-privileges\search
type ApiRolePrivilegesSearchRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// ApiRolePrivilegesSearchRequestBuilderGetQueryParameters search role privileges
type ApiRolePrivilegesSearchRequestBuilderGetQueryParameters struct {
	// Limit the query results, defaults to 15
	Limit *string "uriparametername:\"limit\""
	// The partial or complete privilege name we are searching for
	Name *string "uriparametername:\"name\""
}

// NewApiRolePrivilegesSearchRequestBuilderInternal instantiates a new ApiRolePrivilegesSearchRequestBuilder and sets the default values.
func NewApiRolePrivilegesSearchRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ApiRolePrivilegesSearchRequestBuilder {
	m := &ApiRolePrivilegesSearchRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/api-role-privileges/search?name={name}{&limit*}", pathParameters),
	}
	return m
}

// NewApiRolePrivilegesSearchRequestBuilder instantiates a new ApiRolePrivilegesSearchRequestBuilder and sets the default values.
func NewApiRolePrivilegesSearchRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ApiRolePrivilegesSearchRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewApiRolePrivilegesSearchRequestBuilderInternal(urlParams, requestAdapter)
}

// Get search role privileges
// returns a ApiRolePrivilegesable when successful
func (m *ApiRolePrivilegesSearchRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ApiRolePrivilegesSearchRequestBuilderGetQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.ApiRolePrivilegesable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiRolePrivilegesFromDiscriminatorValue, nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.ApiRolePrivilegesable), nil
}

// ToGetRequestInformation search role privileges
// returns a *RequestInformation when successful
func (m *ApiRolePrivilegesSearchRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ApiRolePrivilegesSearchRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ApiRolePrivilegesSearchRequestBuilder when successful
func (m *ApiRolePrivilegesSearchRequestBuilder) WithUrl(rawUrl string) *ApiRolePrivilegesSearchRequestBuilder {
	return NewApiRolePrivilegesSearchRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
