// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CloudDistributionPointUploadCapabilityRequestBuilder builds and executes requests for operations under \v1\cloud-distribution-point\upload-capability
type CloudDistributionPointUploadCapabilityRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewCloudDistributionPointUploadCapabilityRequestBuilderInternal instantiates a new CloudDistributionPointUploadCapabilityRequestBuilder and sets the default values.
func NewCloudDistributionPointUploadCapabilityRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CloudDistributionPointUploadCapabilityRequestBuilder {
	m := &CloudDistributionPointUploadCapabilityRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/cloud-distribution-point/upload-capability", pathParameters),
	}
	return m
}

// NewCloudDistributionPointUploadCapabilityRequestBuilder instantiates a new CloudDistributionPointUploadCapabilityRequestBuilder and sets the default values.
func NewCloudDistributionPointUploadCapabilityRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CloudDistributionPointUploadCapabilityRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewCloudDistributionPointUploadCapabilityRequestBuilderInternal(urlParams, requestAdapter)
}

// Get finds a variety of values based on the currently configured cloud distribution point.
// returns a CloudDistributionPointUploadCapabilityable when successful
func (m *CloudDistributionPointUploadCapabilityRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CloudDistributionPointUploadCapabilityable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateCloudDistributionPointUploadCapabilityFromDiscriminatorValue, nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CloudDistributionPointUploadCapabilityable), nil
}

// ToGetRequestInformation finds a variety of values based on the currently configured cloud distribution point.
// returns a *RequestInformation when successful
func (m *CloudDistributionPointUploadCapabilityRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CloudDistributionPointUploadCapabilityRequestBuilder when successful
func (m *CloudDistributionPointUploadCapabilityRequestBuilder) WithUrl(rawUrl string) *CloudDistributionPointUploadCapabilityRequestBuilder {
	return NewCloudDistributionPointUploadCapabilityRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
