// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ComputerExtensionAttributesTemplatesRequestBuilder builds and executes requests for operations under \v1\computer-extension-attributes\templates
type ComputerExtensionAttributesTemplatesRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// ComputerExtensionAttributesTemplatesRequestBuilderGetQueryParameters retrieves All Computer Extension Attributes Templates.
type ComputerExtensionAttributesTemplatesRequestBuilderGetQueryParameters struct {
	// Filters results. Use RSQL format for queries. which allows filtering by multiple fields such as templateName, templateCategoryName.<br/> Can be combined with paging and sorting.<br/> Fields allowed in the query: templateName, templateCategoryName <br/> Default filter is an empty query and returns all results from the requested page.
	Filter   *string "uriparametername:\"filter\""
	Page     *int32  "uriparametername:\"page\""
	PageSize *int32  "uriparametername:\"page%2Dsize\""
	// Sorts results by one or more criteria, following the format property:asc/desc.<br/> Default sort is templateName:asc.<br/> If using multiple criteria, separate with commas. Allows sort for templateName and templateCategory.
	Sort []string "uriparametername:\"sort\""
}

// ById gets an item from the github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk.v1.computerExtensionAttributes.templates.item collection
// returns a *ComputerExtensionAttributesTemplatesTemplatesItemRequestBuilder when successful
func (m *ComputerExtensionAttributesTemplatesRequestBuilder) ById(id string) *ComputerExtensionAttributesTemplatesTemplatesItemRequestBuilder {
	urlTplParams := make(map[string]string)
	for idx, item := range m.BaseRequestBuilder.PathParameters {
		urlTplParams[idx] = item
	}
	if id != "" {
		urlTplParams["id"] = id
	}
	return NewComputerExtensionAttributesTemplatesTemplatesItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}

// NewComputerExtensionAttributesTemplatesRequestBuilderInternal instantiates a new ComputerExtensionAttributesTemplatesRequestBuilder and sets the default values.
func NewComputerExtensionAttributesTemplatesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ComputerExtensionAttributesTemplatesRequestBuilder {
	m := &ComputerExtensionAttributesTemplatesRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/computer-extension-attributes/templates{?filter*,page*,page%2Dsize*,sort*}", pathParameters),
	}
	return m
}

// NewComputerExtensionAttributesTemplatesRequestBuilder instantiates a new ComputerExtensionAttributesTemplatesRequestBuilder and sets the default values.
func NewComputerExtensionAttributesTemplatesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ComputerExtensionAttributesTemplatesRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewComputerExtensionAttributesTemplatesRequestBuilderInternal(urlParams, requestAdapter)
}

// Get retrieves All Computer Extension Attributes Templates.
// returns a CeaTemplatesResultsable when successful
func (m *ComputerExtensionAttributesTemplatesRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ComputerExtensionAttributesTemplatesRequestBuilderGetQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CeaTemplatesResultsable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateCeaTemplatesResultsFromDiscriminatorValue, nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CeaTemplatesResultsable), nil
}

// ToGetRequestInformation retrieves All Computer Extension Attributes Templates.
// returns a *RequestInformation when successful
func (m *ComputerExtensionAttributesTemplatesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ComputerExtensionAttributesTemplatesRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ComputerExtensionAttributesTemplatesRequestBuilder when successful
func (m *ComputerExtensionAttributesTemplatesRequestBuilder) WithUrl(rawUrl string) *ComputerExtensionAttributesTemplatesRequestBuilder {
	return NewComputerExtensionAttributesTemplatesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
