// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder builds and executes requests for operations under \v1\conditional-access\device-compliance-information\computer\{deviceId}
type ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilderInternal instantiates a new ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder and sets the default values.
func NewConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder {
	m := &ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/conditional-access/device-compliance-information/computer/{deviceId}", pathParameters),
	}
	return m
}

// NewConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder instantiates a new ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder and sets the default values.
func NewConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilderInternal(urlParams, requestAdapter)
}

// Get return basic compliance information for the given computer device
// returns a []DeviceComplianceInformationable when successful
func (m *ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) ([]id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.DeviceComplianceInformationable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.SendCollection(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateDeviceComplianceInformationFromDiscriminatorValue, nil)
	if err != nil {
		return nil, err
	}
	val := make([]id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.DeviceComplianceInformationable, len(res))
	for i, v := range res {
		if v != nil {
			val[i] = v.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.DeviceComplianceInformationable)
		}
	}
	return val, nil
}

// ToGetRequestInformation return basic compliance information for the given computer device
// returns a *RequestInformation when successful
func (m *ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder when successful
func (m *ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder) WithUrl(rawUrl string) *ConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder {
	return NewConditionalAccessDeviceComplianceInformationComputerWithDeviceItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
