// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// CsaTokenRequestBuilder builds and executes requests for operations under \v1\csa\token
type CsaTokenRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewCsaTokenRequestBuilderInternal instantiates a new CsaTokenRequestBuilder and sets the default values.
func NewCsaTokenRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CsaTokenRequestBuilder {
	m := &CsaTokenRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/csa/token", pathParameters),
	}
	return m
}

// NewCsaTokenRequestBuilder instantiates a new CsaTokenRequestBuilder and sets the default values.
func NewCsaTokenRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *CsaTokenRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewCsaTokenRequestBuilderInternal(urlParams, requestAdapter)
}

// Delete delete the CSA token exchange - This will disable Jamf Pro's ability to authenticate with cloud-hosted services
// returns a ApiError error when the service returns a 404 status code
// returns a ApiError error when the service returns a 409 status code
func (m *CsaTokenRequestBuilder) Delete(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) error {
	requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"404": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
		"409": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
	}
	err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
	if err != nil {
		return err
	}
	return nil
}

// Get get details regarding the CSA token exchange
// returns a CsaTokenable when successful
// returns a ApiError error when the service returns a 404 status code
func (m *CsaTokenRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CsaTokenable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"404": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateCsaTokenFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CsaTokenable), nil
}

// ToDeleteRequestInformation delete the CSA token exchange - This will disable Jamf Pro's ability to authenticate with cloud-hosted services
// returns a *RequestInformation when successful
func (m *CsaTokenRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// ToGetRequestInformation get details regarding the CSA token exchange
// returns a *RequestInformation when successful
func (m *CsaTokenRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *CsaTokenRequestBuilder when successful
func (m *CsaTokenRequestBuilder) WithUrl(rawUrl string) *CsaTokenRequestBuilder {
	return NewCsaTokenRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
