// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// GsxConnectionTestRequestBuilder builds and executes requests for operations under \v1\gsx-connection\test
type GsxConnectionTestRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewGsxConnectionTestRequestBuilderInternal instantiates a new GsxConnectionTestRequestBuilder and sets the default values.
func NewGsxConnectionTestRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *GsxConnectionTestRequestBuilder {
	m := &GsxConnectionTestRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/gsx-connection/test", pathParameters),
	}
	return m
}

// NewGsxConnectionTestRequestBuilder instantiates a new GsxConnectionTestRequestBuilder and sets the default values.
func NewGsxConnectionTestRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *GsxConnectionTestRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewGsxConnectionTestRequestBuilderInternal(urlParams, requestAdapter)
}

// Post test functionality of an GSX Connection
// returns a GsxTestResponse error when the service returns a 400 status code
func (m *GsxConnectionTestRequestBuilder) Post(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) error {
	requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateGsxTestResponseFromDiscriminatorValue,
	}
	err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
	if err != nil {
		return err
	}
	return nil
}

// ToPostRequestInformation test functionality of an GSX Connection
// returns a *RequestInformation when successful
func (m *GsxConnectionTestRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *GsxConnectionTestRequestBuilder when successful
func (m *GsxConnectionTestRequestBuilder) WithUrl(rawUrl string) *GsxConnectionTestRequestBuilder {
	return NewGsxConnectionTestRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
