// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// LdapRequestBuilder builds and executes requests for operations under \v1\ldap
type LdapRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewLdapRequestBuilderInternal instantiates a new LdapRequestBuilder and sets the default values.
func NewLdapRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *LdapRequestBuilder {
	m := &LdapRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/ldap", pathParameters),
	}
	return m
}

// NewLdapRequestBuilder instantiates a new LdapRequestBuilder and sets the default values.
func NewLdapRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *LdapRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewLdapRequestBuilderInternal(urlParams, requestAdapter)
}

// Groups the groups property
// returns a *LdapGroupsRequestBuilder when successful
func (m *LdapRequestBuilder) Groups() *LdapGroupsRequestBuilder {
	return NewLdapGroupsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// LdapServers the ldapServers property
// returns a *LdapLdapServersRequestBuilder when successful
func (m *LdapRequestBuilder) LdapServers() *LdapLdapServersRequestBuilder {
	return NewLdapLdapServersRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// Servers the servers property
// returns a *LdapServersRequestBuilder when successful
func (m *LdapRequestBuilder) Servers() *LdapServersRequestBuilder {
	return NewLdapServersRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
