// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilder builds and executes requests for operations under \v1\managed-software-updates\update-statuses\mobile-devices
type ManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// ById gets an item from the github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk.v1.managedSoftwareUpdates.updateStatuses.mobileDevices.item collection
// returns a *ManagedSoftwareUpdatesUpdateStatusesMobileDevicesMobileDevicesItemRequestBuilder when successful
func (m *ManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilder) ById(id string) *ManagedSoftwareUpdatesUpdateStatusesMobileDevicesMobileDevicesItemRequestBuilder {
	urlTplParams := make(map[string]string)
	for idx, item := range m.BaseRequestBuilder.PathParameters {
		urlTplParams[idx] = item
	}
	if id != "" {
		urlTplParams["id"] = id
	}
	return NewManagedSoftwareUpdatesUpdateStatusesMobileDevicesMobileDevicesItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}

// NewManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilderInternal instantiates a new ManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilder and sets the default values.
func NewManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilder {
	m := &ManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/managed-software-updates/update-statuses/mobile-devices", pathParameters),
	}
	return m
}

// NewManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilder instantiates a new ManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilder and sets the default values.
func NewManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewManagedSoftwareUpdatesUpdateStatusesMobileDevicesRequestBuilderInternal(urlParams, requestAdapter)
}
