// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// MobileDeviceGroupsStaticGroupsRequestBuilder builds and executes requests for operations under \v1\mobile-device-groups\static-groups
type MobileDeviceGroupsStaticGroupsRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// MobileDeviceGroupsStaticGroupsRequestBuilderGetQueryParameters get Static Groups
type MobileDeviceGroupsStaticGroupsRequestBuilderGetQueryParameters struct {
	// Query in the RSQL format, allowing to filter department collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: groupId, groupName, siteId. The siteId field can only be filtered by admins with full access. Any sited admin will have siteId filtered automatically. This param can be combined with paging and sorting. Example: groupName=="staticGroup1"
	Filter   *string "uriparametername:\"filter\""
	Page     *int32  "uriparametername:\"page\""
	PageSize *int32  "uriparametername:\"page%2Dsize\""
	// Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Available criteria to sort on: groupId, groupName, siteId.
	Sort []string "uriparametername:\"sort\""
}

// MobileDeviceGroupsStaticGroupsRequestBuilderPostQueryParameters create membership of a static group
type MobileDeviceGroupsStaticGroupsRequestBuilderPostQueryParameters struct {
	// Optional. Return platform identifiers instead of internal identifiers when set to true.
	Platform *bool "uriparametername:\"platform\""
}

// ById gets an item from the github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk.v1.mobileDeviceGroups.staticGroups.item collection
// Deprecated:
// returns a *MobileDeviceGroupsStaticGroupsStaticGroupsItemRequestBuilder when successful
func (m *MobileDeviceGroupsStaticGroupsRequestBuilder) ById(id string) *MobileDeviceGroupsStaticGroupsStaticGroupsItemRequestBuilder {
	urlTplParams := make(map[string]string)
	for idx, item := range m.BaseRequestBuilder.PathParameters {
		urlTplParams[idx] = item
	}
	if id != "" {
		urlTplParams["id"] = id
	}
	return NewMobileDeviceGroupsStaticGroupsStaticGroupsItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}

// NewMobileDeviceGroupsStaticGroupsRequestBuilderInternal instantiates a new MobileDeviceGroupsStaticGroupsRequestBuilder and sets the default values.
func NewMobileDeviceGroupsStaticGroupsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileDeviceGroupsStaticGroupsRequestBuilder {
	m := &MobileDeviceGroupsStaticGroupsRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/mobile-device-groups/static-groups{?filter*,page*,page%2Dsize*,platform*,sort*}", pathParameters),
	}
	return m
}

// NewMobileDeviceGroupsStaticGroupsRequestBuilder instantiates a new MobileDeviceGroupsStaticGroupsRequestBuilder and sets the default values.
func NewMobileDeviceGroupsStaticGroupsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *MobileDeviceGroupsStaticGroupsRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewMobileDeviceGroupsStaticGroupsRequestBuilderInternal(urlParams, requestAdapter)
}

// Get get Static Groups
// Deprecated:
// returns a StaticGroupSearchResultsable when successful
func (m *MobileDeviceGroupsStaticGroupsRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[MobileDeviceGroupsStaticGroupsRequestBuilderGetQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.StaticGroupSearchResultsable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateStaticGroupSearchResultsFromDiscriminatorValue, nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.StaticGroupSearchResultsable), nil
}

// Post create membership of a static group
// Deprecated:
// returns a HrefResponseable when successful
// returns a ApiError error when the service returns a 400 status code
func (m *MobileDeviceGroupsStaticGroupsRequestBuilder) Post(ctx context.Context, body id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.StaticGroupAssignmentable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[MobileDeviceGroupsStaticGroupsRequestBuilderPostQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.HrefResponseable, error) {
	requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateHrefResponseFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.HrefResponseable), nil
}

// ToGetRequestInformation get Static Groups
// Deprecated:
// returns a *RequestInformation when successful
func (m *MobileDeviceGroupsStaticGroupsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[MobileDeviceGroupsStaticGroupsRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// ToPostRequestInformation create membership of a static group
// Deprecated:
// returns a *RequestInformation when successful
func (m *MobileDeviceGroupsStaticGroupsRequestBuilder) ToPostRequestInformation(ctx context.Context, body id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.StaticGroupAssignmentable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[MobileDeviceGroupsStaticGroupsRequestBuilderPostQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
	if err != nil {
		return nil, err
	}
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// Deprecated:
// returns a *MobileDeviceGroupsStaticGroupsRequestBuilder when successful
func (m *MobileDeviceGroupsStaticGroupsRequestBuilder) WithUrl(rawUrl string) *MobileDeviceGroupsStaticGroupsRequestBuilder {
	return NewMobileDeviceGroupsStaticGroupsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
