// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// OidcPublicFeaturesRequestBuilder builds and executes requests for operations under \v1\oidc\public-features
type OidcPublicFeaturesRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewOidcPublicFeaturesRequestBuilderInternal instantiates a new OidcPublicFeaturesRequestBuilder and sets the default values.
func NewOidcPublicFeaturesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *OidcPublicFeaturesRequestBuilder {
	m := &OidcPublicFeaturesRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/oidc/public-features", pathParameters),
	}
	return m
}

// NewOidcPublicFeaturesRequestBuilder instantiates a new OidcPublicFeaturesRequestBuilder and sets the default values.
func NewOidcPublicFeaturesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *OidcPublicFeaturesRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewOidcPublicFeaturesRequestBuilderInternal(urlParams, requestAdapter)
}

// Get retrieves public OIDC configuration features.
// returns a OidcPublicFeaturesResponseable when successful
func (m *OidcPublicFeaturesRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.OidcPublicFeaturesResponseable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateOidcPublicFeaturesResponseFromDiscriminatorValue, nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.OidcPublicFeaturesResponseable), nil
}

// ToGetRequestInformation retrieves public OIDC configuration features.
// returns a *RequestInformation when successful
func (m *OidcPublicFeaturesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *OidcPublicFeaturesRequestBuilder when successful
func (m *OidcPublicFeaturesRequestBuilder) WithUrl(rawUrl string) *OidcPublicFeaturesRequestBuilder {
	return NewOidcPublicFeaturesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
