// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"

	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// SelfServicePlusFeatureToggleEnabledRequestBuilder builds and executes requests for operations under \v1\self-service-plus\feature-toggle\enabled
type SelfServicePlusFeatureToggleEnabledRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewSelfServicePlusFeatureToggleEnabledRequestBuilderInternal instantiates a new SelfServicePlusFeatureToggleEnabledRequestBuilder and sets the default values.
func NewSelfServicePlusFeatureToggleEnabledRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *SelfServicePlusFeatureToggleEnabledRequestBuilder {
	m := &SelfServicePlusFeatureToggleEnabledRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/self-service-plus/feature-toggle/enabled", pathParameters),
	}
	return m
}

// NewSelfServicePlusFeatureToggleEnabledRequestBuilder instantiates a new SelfServicePlusFeatureToggleEnabledRequestBuilder and sets the default values.
func NewSelfServicePlusFeatureToggleEnabledRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *SelfServicePlusFeatureToggleEnabledRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewSelfServicePlusFeatureToggleEnabledRequestBuilderInternal(urlParams, requestAdapter)
}

// Get this endpoint is used to determine if the Self Service Plus feature toggle is enabled.
func (m *SelfServicePlusFeatureToggleEnabledRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) error {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return err
	}
	err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, nil)
	if err != nil {
		return err
	}
	return nil
}

// ToGetRequestInformation this endpoint is used to determine if the Self Service Plus feature toggle is enabled.
// returns a *RequestInformation when successful
func (m *SelfServicePlusFeatureToggleEnabledRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SelfServicePlusFeatureToggleEnabledRequestBuilder when successful
func (m *SelfServicePlusFeatureToggleEnabledRequestBuilder) WithUrl(rawUrl string) *SelfServicePlusFeatureToggleEnabledRequestBuilder {
	return NewSelfServicePlusFeatureToggleEnabledRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
