// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v1

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// SystemInitializeDatabaseConnectionRequestBuilder builds and executes requests for operations under \v1\system\initialize-database-connection
type SystemInitializeDatabaseConnectionRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewSystemInitializeDatabaseConnectionRequestBuilderInternal instantiates a new SystemInitializeDatabaseConnectionRequestBuilder and sets the default values.
func NewSystemInitializeDatabaseConnectionRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *SystemInitializeDatabaseConnectionRequestBuilder {
	m := &SystemInitializeDatabaseConnectionRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v1/system/initialize-database-connection", pathParameters),
	}
	return m
}

// NewSystemInitializeDatabaseConnectionRequestBuilder instantiates a new SystemInitializeDatabaseConnectionRequestBuilder and sets the default values.
func NewSystemInitializeDatabaseConnectionRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *SystemInitializeDatabaseConnectionRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewSystemInitializeDatabaseConnectionRequestBuilderInternal(urlParams, requestAdapter)
}

// Post provide database password during startup. Endpoint is accessible when database password was not configured and Jamf Pro server has not been initialized yet.
// returns a ApiError error when the service returns a 400 status code
// returns a ApiError error when the service returns a 429 status code
func (m *SystemInitializeDatabaseConnectionRequestBuilder) Post(ctx context.Context, body id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.DatabasePasswordable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) error {
	requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration)
	if err != nil {
		return err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
		"429": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
	}
	err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
	if err != nil {
		return err
	}
	return nil
}

// ToPostRequestInformation provide database password during startup. Endpoint is accessible when database password was not configured and Jamf Pro server has not been initialized yet.
// returns a *RequestInformation when successful
func (m *SystemInitializeDatabaseConnectionRequestBuilder) ToPostRequestInformation(ctx context.Context, body id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.DatabasePasswordable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
	if err != nil {
		return nil, err
	}
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SystemInitializeDatabaseConnectionRequestBuilder when successful
func (m *SystemInitializeDatabaseConnectionRequestBuilder) WithUrl(rawUrl string) *SystemInitializeDatabaseConnectionRequestBuilder {
	return NewSystemInitializeDatabaseConnectionRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
