// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:1c390a29e8f876058ab1470b6ae0115be89751869d4b803c43b5f6600ed83e0b). DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"

	v7TagData "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/services/datasources/tags/v7/tag"
	v7TagsData "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/services/datasources/tags/v7/tags"
)

// DataSources returns every data source this provider serves.
//
// This file is generated in full. Add a data source by adding a blueprint and
// regenerating, not by editing here.
func (p *Provider) DataSources(_ context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		v7TagData.NewTagDataSource,
		v7TagsData.NewTagsDataSource,
	}
}
