// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:b7a37637e9e8944926fd0bd81f3ab351c323ae5d0afc88e063ab09719025d907). DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"

	v7Tag "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/services/resources/tags/v7/tag"
)

// Resources returns every managed resource this provider serves.
//
// This file is generated in full. Add a resource by adding a blueprint and
// regenerating, not by editing here.
func (p *Provider) Resources(_ context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		v7Tag.NewTagResource,
	}
}
