// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:92588417fa010d48e3954c780a1c7284689923c40fd60ea7464f85cbc75b43eb). DO NOT EDIT.

package v2_enrollment_customization

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"

	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/client"
	sdk "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk"
	commonschema "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/services/common/schema"
)

const (
	// TypeName is the Terraform type this resource registers as.
	TypeName = "jamfpro_v2_enrollment_customization"

	// Default per-operation timeouts, in seconds. A practitioner overrides them
	// with the resource's timeouts block.
	CreateTimeout = 180
	ReadTimeout   = 180
	UpdateTimeout = 180
	DeleteTimeout = 180
)

// Compile-time assertions that this resource implements what it claims to. They
// turn a missing method into a build failure rather than a runtime surprise.
var (
	_ resource.Resource                = (*V2EnrollmentCustomizationResource)(nil)
	_ resource.ResourceWithConfigure   = (*V2EnrollmentCustomizationResource)(nil)
	_ resource.ResourceWithImportState = (*V2EnrollmentCustomizationResource)(nil)
)

// NewV2EnrollmentCustomizationResource returns the jamfpro_v2_enrollment_customization resource.
func NewV2EnrollmentCustomizationResource() resource.Resource {
	return &V2EnrollmentCustomizationResource{}
}

// V2EnrollmentCustomizationResource implements the jamfpro_v2_enrollment_customization resource.
type V2EnrollmentCustomizationResource struct {
	client *sdk.JamfProClient
}

// Metadata returns the resource type name.
func (r *V2EnrollmentCustomizationResource) Metadata(_ context.Context, _ resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TypeName
}

// Configure receives the configured SDK client from the provider.
func (r *V2EnrollmentCustomizationResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = client.ForResource(ctx, req, resp, TypeName)
}

// ImportState maps a terraform import into state.
func (r *V2EnrollmentCustomizationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// Schema returns the resource schema.
func (r *V2EnrollmentCustomizationResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieve an Enrollment Customization with the supplied id.",
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Required: true,
			},
			"display_name": schema.StringAttribute{
				Required: true,
			},
			"enrollment_customization_branding_settings": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"background_color": schema.StringAttribute{
						Required: true,
					},
					"button_color": schema.StringAttribute{
						Required: true,
					},
					"button_text_color": schema.StringAttribute{
						Required: true,
					},
					"icon_url": schema.StringAttribute{
						Required: true,
					},
					"text_color": schema.StringAttribute{
						Required: true,
					},
				},
				Required: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"site_id": schema.StringAttribute{
				Required: true,
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": commonschema.ResourceTimeouts(ctx),
		},
	}
}
