// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:e9fc089728e964a2ce1adf1c51444126c782ff30e172933b5177fd9a4982f6db). DO NOT EDIT.

// REF: https://developer.cisco.com/docs/thousandeyes/get-credential/
package credential

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// CredentialEphemeralModel carries a thousandeyes_credential's configuration in and its result
// out. There is no timeouts field: an ephemeral schema has no timeouts block, and the
// open deadline is the generated constant.
type CredentialEphemeralModel struct {
	ID    types.String `tfsdk:"id"`
	Name  types.String `tfsdk:"name"`
	Value types.String `tfsdk:"value"`
}
