# Code generated by tfpluginframeworkgen from blueprints/thousandeyes
# (sha256:34641e38d86861908506361741dc13945137d4be4706350b91de515c0979fdc0). DO NOT EDIT.

# The widest configuration the evidence supports: every writable attribute with a derivable
# value, chosen by the same derivation the rehearsal probe sends to the live API.
#
# Regenerated and policed, deliberately. This file used to be a hand-owned scaffold, and
# hand edits are how its values drifted from the generated assertions -- the checks derive
# from the blueprint, so the blueprint is where a value is corrected: an accFixture hint for
# something only a human knows, recorded behaviour for everything the probe observed. What
# could not be derived is listed inside the block, each with the reason.

resource "thousandeyes_tag" "test" {
  # Where a value came from.
  #
  # color: the API's own default, so a value it is known to accept
  #
  # icon: the API's own default, so a value it is known to accept
  #
  # object_type: observed accepted
  #
  # access_type: observed accepted; the API refused system
  #
  # match_type: observed accepted
  #
  # type: documented; unprobed
  #
  # Not filled in, because no correct value could be derived. Each of these is optional, so this
  # configuration is valid as it stands -- but it is testing less than it could.
  #
  # filters: a nested object's members may be identifiers of objects that must already exist,
  # and nothing in the specification says whether they are
  key         = "tfacc-key"
  value       = "tfacc-value"
  color       = "#A7EB10"
  description = "tfacc-description"
  icon        = "LABEL"
  object_type = "test"
  access_type = "all"
  match_type  = "and"
  type        = "static"
}
