# Code generated by tfpluginframeworkgen from blueprints/thousandeyes
# (sha256:024618eb965d811980cc3d4d0361d909f17f28d0535b60a84f068e43b77d95e0). DO NOT EDIT.

# The query configuration: one list block over the whole collection. The provider block
# is explicit because the list block references it by symbol, unlike a resource step
# where the test factories inject it.

provider "thousandeyes" {}

list "thousandeyes_tag" "test" {
  provider = thousandeyes
}
