// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:92588417fa010d48e3954c780a1c7284689923c40fd60ea7464f85cbc75b43eb). DO NOT EDIT.

package v4_computers_inventory

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// V4ComputersInventoryResourceModel is the Terraform state for a jamfpro_v4_computers_inventory.
//
// Field order follows the schema, and the timeouts value is last.
type V4ComputersInventoryResourceModel struct {
	Attachments         types.Set      `tfsdk:"attachments"`
	ContentCaching      types.Object   `tfsdk:"content_caching"`
	DiskEncryption      types.Object   `tfsdk:"disk_encryption"`
	ExtensionAttributes types.Set      `tfsdk:"extension_attributes"`
	GroupMemberships    types.Set      `tfsdk:"group_memberships"`
	Ibeacons            types.Set      `tfsdk:"ibeacons"`
	ID                  types.String   `tfsdk:"id"`
	LicensedSoftware    types.Set      `tfsdk:"licensed_software"`
	Udid                types.String   `tfsdk:"udid"`
	Timeouts            timeouts.Value `tfsdk:"timeouts"`
}

// V4ComputersInventoryComputerAttachmentModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerAttachmentModel struct {
	FileType  types.String `tfsdk:"file_type"`
	ID        types.String `tfsdk:"id"`
	Name      types.String `tfsdk:"name"`
	SizeBytes types.Int64  `tfsdk:"size_bytes"`
}

// v4ComputersInventoryComputerAttachmentAttrTypes describes V4ComputersInventoryComputerAttachmentModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerAttachmentAttrTypes = map[string]attr.Type{
	"file_type":  types.StringType,
	"id":         types.StringType,
	"name":       types.StringType,
	"size_bytes": types.Int64Type,
}

var v4ComputersInventoryComputerAttachmentObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerAttachmentAttrTypes}

// V4ComputersInventoryComputerContentCachingModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerContentCachingModel struct {
	Activated                           types.Bool   `tfsdk:"activated"`
	Active                              types.Bool   `tfsdk:"active"`
	ActualCacheBytesUsed                types.Int64  `tfsdk:"actual_cache_bytes_used"`
	Alerts                              types.Set    `tfsdk:"alerts"`
	CacheBytesFree                      types.Int64  `tfsdk:"cache_bytes_free"`
	CacheBytesLimit                     types.Int64  `tfsdk:"cache_bytes_limit"`
	CacheBytesUsed                      types.Int64  `tfsdk:"cache_bytes_used"`
	CacheDetails                        types.Set    `tfsdk:"cache_details"`
	CacheStatus                         types.String `tfsdk:"cache_status"`
	ComputerContentCachingInformationID types.String `tfsdk:"computer_content_caching_information_id"`
	DataMigrationCompleted              types.Bool   `tfsdk:"data_migration_completed"`
	DataMigrationError                  types.Object `tfsdk:"data_migration_error"`
	DataMigrationProgressPercentage     types.Int64  `tfsdk:"data_migration_progress_percentage"`
	MaxCachePressureLast1HourPercentage types.Int64  `tfsdk:"max_cache_pressure_last1_hour_percentage"`
	Parents                             types.Set    `tfsdk:"parents"`
	PersonalCacheBytesFree              types.Int64  `tfsdk:"personal_cache_bytes_free"`
	PersonalCacheBytesLimit             types.Int64  `tfsdk:"personal_cache_bytes_limit"`
	PersonalCacheBytesUsed              types.Int64  `tfsdk:"personal_cache_bytes_used"`
	Port                                types.Int64  `tfsdk:"port"`
	PublicAddress                       types.String `tfsdk:"public_address"`
	RegistrationError                   types.String `tfsdk:"registration_error"`
	RegistrationResponseCode            types.Int64  `tfsdk:"registration_response_code"`
	RegistrationStarted                 types.String `tfsdk:"registration_started"`
	RegistrationStatus                  types.String `tfsdk:"registration_status"`
	RestrictedMedia                     types.Bool   `tfsdk:"restricted_media"`
	ServerGuid                          types.String `tfsdk:"server_guid"`
	StartupStatus                       types.String `tfsdk:"startup_status"`
	TetheratorStatus                    types.String `tfsdk:"tetherator_status"`
	TotalBytesAreSince                  types.String `tfsdk:"total_bytes_are_since"`
	TotalBytesDropped                   types.Int64  `tfsdk:"total_bytes_dropped"`
	TotalBytesImported                  types.Int64  `tfsdk:"total_bytes_imported"`
	TotalBytesReturnedToChildren        types.Int64  `tfsdk:"total_bytes_returned_to_children"`
	TotalBytesReturnedToClients         types.Int64  `tfsdk:"total_bytes_returned_to_clients"`
	TotalBytesReturnedToPeers           types.Int64  `tfsdk:"total_bytes_returned_to_peers"`
	TotalBytesStoredFromOrigin          types.Int64  `tfsdk:"total_bytes_stored_from_origin"`
	TotalBytesStoredFromParents         types.Int64  `tfsdk:"total_bytes_stored_from_parents"`
	TotalBytesStoredFromPeers           types.Int64  `tfsdk:"total_bytes_stored_from_peers"`
}

// v4ComputersInventoryComputerContentCachingAttrTypes describes V4ComputersInventoryComputerContentCachingModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerContentCachingAttrTypes = map[string]attr.Type{
	"activated":               types.BoolType,
	"active":                  types.BoolType,
	"actual_cache_bytes_used": types.Int64Type,
	"alerts":                  types.SetType{ElemType: v4ComputersInventoryComputerContentCachingAlertObjectType},
	"cache_bytes_free":        types.Int64Type,
	"cache_bytes_limit":       types.Int64Type,
	"cache_bytes_used":        types.Int64Type,
	"cache_details":           types.SetType{ElemType: v4ComputersInventoryComputerContentCachingCacheDetailObjectType},
	"cache_status":            types.StringType,
	"computer_content_caching_information_id":  types.StringType,
	"data_migration_completed":                 types.BoolType,
	"data_migration_error":                     v4ComputersInventoryComputerContentCachingDataMigrationErrorObjectType,
	"data_migration_progress_percentage":       types.Int64Type,
	"max_cache_pressure_last1_hour_percentage": types.Int64Type,
	"parents":                          types.SetType{ElemType: v4ComputersInventoryComputerContentCachingParentObjectType},
	"personal_cache_bytes_free":        types.Int64Type,
	"personal_cache_bytes_limit":       types.Int64Type,
	"personal_cache_bytes_used":        types.Int64Type,
	"port":                             types.Int64Type,
	"public_address":                   types.StringType,
	"registration_error":               types.StringType,
	"registration_response_code":       types.Int64Type,
	"registration_started":             types.StringType,
	"registration_status":              types.StringType,
	"restricted_media":                 types.BoolType,
	"server_guid":                      types.StringType,
	"startup_status":                   types.StringType,
	"tetherator_status":                types.StringType,
	"total_bytes_are_since":            types.StringType,
	"total_bytes_dropped":              types.Int64Type,
	"total_bytes_imported":             types.Int64Type,
	"total_bytes_returned_to_children": types.Int64Type,
	"total_bytes_returned_to_clients":  types.Int64Type,
	"total_bytes_returned_to_peers":    types.Int64Type,
	"total_bytes_stored_from_origin":   types.Int64Type,
	"total_bytes_stored_from_parents":  types.Int64Type,
	"total_bytes_stored_from_peers":    types.Int64Type,
}

var v4ComputersInventoryComputerContentCachingObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerContentCachingAttrTypes}

// V4ComputersInventoryComputerContentCachingAlertModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerContentCachingAlertModel struct {
	CacheBytesLimit      types.Int64  `tfsdk:"cache_bytes_limit"`
	ClassName            types.String `tfsdk:"class_name"`
	PathPreventingAccess types.String `tfsdk:"path_preventing_access"`
	PostDate             types.String `tfsdk:"post_date"`
	ReservedVolumeBytes  types.Int64  `tfsdk:"reserved_volume_bytes"`
	Resource             types.String `tfsdk:"resource"`
}

// v4ComputersInventoryComputerContentCachingAlertAttrTypes describes V4ComputersInventoryComputerContentCachingAlertModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerContentCachingAlertAttrTypes = map[string]attr.Type{
	"cache_bytes_limit":      types.Int64Type,
	"class_name":             types.StringType,
	"path_preventing_access": types.StringType,
	"post_date":              types.StringType,
	"reserved_volume_bytes":  types.Int64Type,
	"resource":               types.StringType,
}

var v4ComputersInventoryComputerContentCachingAlertObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerContentCachingAlertAttrTypes}

// V4ComputersInventoryComputerContentCachingCacheDetailModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerContentCachingCacheDetailModel struct {
	CategoryName                         types.String `tfsdk:"category_name"`
	ComputerContentCachingCacheDetailsID types.String `tfsdk:"computer_content_caching_cache_details_id"`
	DiskSpaceBytesUsed                   types.Int64  `tfsdk:"disk_space_bytes_used"`
}

// v4ComputersInventoryComputerContentCachingCacheDetailAttrTypes describes V4ComputersInventoryComputerContentCachingCacheDetailModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerContentCachingCacheDetailAttrTypes = map[string]attr.Type{
	"category_name": types.StringType,
	"computer_content_caching_cache_details_id": types.StringType,
	"disk_space_bytes_used":                     types.Int64Type,
}

var v4ComputersInventoryComputerContentCachingCacheDetailObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerContentCachingCacheDetailAttrTypes}

// V4ComputersInventoryComputerContentCachingDataMigrationErrorModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerContentCachingDataMigrationErrorModel struct {
	Code     types.Int64  `tfsdk:"code"`
	Domain   types.String `tfsdk:"domain"`
	UserInfo types.Set    `tfsdk:"user_info"`
}

// v4ComputersInventoryComputerContentCachingDataMigrationErrorAttrTypes describes V4ComputersInventoryComputerContentCachingDataMigrationErrorModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerContentCachingDataMigrationErrorAttrTypes = map[string]attr.Type{
	"code":      types.Int64Type,
	"domain":    types.StringType,
	"user_info": types.SetType{ElemType: v4ComputersInventoryComputerContentCachingDataMigrationErrorUserInfoObjectType},
}

var v4ComputersInventoryComputerContentCachingDataMigrationErrorObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerContentCachingDataMigrationErrorAttrTypes}

// V4ComputersInventoryComputerContentCachingDataMigrationErrorUserInfoModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerContentCachingDataMigrationErrorUserInfoModel struct {
	Key   types.String `tfsdk:"key"`
	Value types.String `tfsdk:"value"`
}

// v4ComputersInventoryComputerContentCachingDataMigrationErrorUserInfoAttrTypes describes V4ComputersInventoryComputerContentCachingDataMigrationErrorUserInfoModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerContentCachingDataMigrationErrorUserInfoAttrTypes = map[string]attr.Type{
	"key":   types.StringType,
	"value": types.StringType,
}

var v4ComputersInventoryComputerContentCachingDataMigrationErrorUserInfoObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerContentCachingDataMigrationErrorUserInfoAttrTypes}

// V4ComputersInventoryComputerContentCachingParentModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerContentCachingParentModel struct {
	Address                types.String `tfsdk:"address"`
	Alerts                 types.Object `tfsdk:"alerts"`
	ContentCachingParentID types.String `tfsdk:"content_caching_parent_id"`
	Details                types.Object `tfsdk:"details"`
	Guid                   types.String `tfsdk:"guid"`
	Healthy                types.Bool   `tfsdk:"healthy"`
	Port                   types.Int64  `tfsdk:"port"`
	Version                types.String `tfsdk:"version"`
}

// v4ComputersInventoryComputerContentCachingParentAttrTypes describes V4ComputersInventoryComputerContentCachingParentModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerContentCachingParentAttrTypes = map[string]attr.Type{
	"address":                   types.StringType,
	"alerts":                    v4ComputersInventoryComputerContentCachingParentAlertObjectType,
	"content_caching_parent_id": types.StringType,
	"details":                   v4ComputersInventoryComputerContentCachingParentDetailsObjectType,
	"guid":                      types.StringType,
	"healthy":                   types.BoolType,
	"port":                      types.Int64Type,
	"version":                   types.StringType,
}

var v4ComputersInventoryComputerContentCachingParentObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerContentCachingParentAttrTypes}

// V4ComputersInventoryComputerContentCachingParentAlertModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerContentCachingParentAlertModel struct {
	Addresses                   types.Set    `tfsdk:"addresses"`
	ClassName                   types.String `tfsdk:"class_name"`
	ContentCachingParentAlertID types.String `tfsdk:"content_caching_parent_alert_id"`
	PostDate                    types.String `tfsdk:"post_date"`
}

// v4ComputersInventoryComputerContentCachingParentAlertAttrTypes describes V4ComputersInventoryComputerContentCachingParentAlertModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerContentCachingParentAlertAttrTypes = map[string]attr.Type{
	"addresses":                       types.SetType{ElemType: types.StringType},
	"class_name":                      types.StringType,
	"content_caching_parent_alert_id": types.StringType,
	"post_date":                       types.StringType,
}

var v4ComputersInventoryComputerContentCachingParentAlertObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerContentCachingParentAlertAttrTypes}

// V4ComputersInventoryComputerContentCachingParentDetailsModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerContentCachingParentDetailsModel struct {
	AcPower                       types.Bool   `tfsdk:"ac_power"`
	CacheSizeBytes                types.Int64  `tfsdk:"cache_size_bytes"`
	Capabilities                  types.Object `tfsdk:"capabilities"`
	ContentCachingParentDetailsID types.String `tfsdk:"content_caching_parent_details_id"`
	LocalNetwork                  types.Set    `tfsdk:"local_network"`
	Portable                      types.Bool   `tfsdk:"portable"`
}

// v4ComputersInventoryComputerContentCachingParentDetailsAttrTypes describes V4ComputersInventoryComputerContentCachingParentDetailsModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerContentCachingParentDetailsAttrTypes = map[string]attr.Type{
	"ac_power":                          types.BoolType,
	"cache_size_bytes":                  types.Int64Type,
	"capabilities":                      v4ComputersInventoryComputerContentCachingParentCapabilitiesObjectType,
	"content_caching_parent_details_id": types.StringType,
	"local_network":                     types.SetType{ElemType: v4ComputersInventoryComputerContentCachingParentLocalNetworkObjectType},
	"portable":                          types.BoolType,
}

var v4ComputersInventoryComputerContentCachingParentDetailsObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerContentCachingParentDetailsAttrTypes}

// V4ComputersInventoryComputerContentCachingParentCapabilitiesModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerContentCachingParentCapabilitiesModel struct {
	ContentCachingParentCapabilitiesID types.String `tfsdk:"content_caching_parent_capabilities_id"`
	Imports                            types.Bool   `tfsdk:"imports"`
	Namespaces                         types.Bool   `tfsdk:"namespaces"`
	PersonalContent                    types.Bool   `tfsdk:"personal_content"`
	Prioritization                     types.Bool   `tfsdk:"prioritization"`
	QueryParameters                    types.Bool   `tfsdk:"query_parameters"`
	SharedContent                      types.Bool   `tfsdk:"shared_content"`
}

// v4ComputersInventoryComputerContentCachingParentCapabilitiesAttrTypes describes V4ComputersInventoryComputerContentCachingParentCapabilitiesModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerContentCachingParentCapabilitiesAttrTypes = map[string]attr.Type{
	"content_caching_parent_capabilities_id": types.StringType,
	"imports":                                types.BoolType,
	"namespaces":                             types.BoolType,
	"personal_content":                       types.BoolType,
	"prioritization":                         types.BoolType,
	"query_parameters":                       types.BoolType,
	"shared_content":                         types.BoolType,
}

var v4ComputersInventoryComputerContentCachingParentCapabilitiesObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerContentCachingParentCapabilitiesAttrTypes}

// V4ComputersInventoryComputerContentCachingParentLocalNetworkModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerContentCachingParentLocalNetworkModel struct {
	ContentCachingParentLocalNetworkID types.String `tfsdk:"content_caching_parent_local_network_id"`
	Speed                              types.Int64  `tfsdk:"speed"`
	Wired                              types.Bool   `tfsdk:"wired"`
}

// v4ComputersInventoryComputerContentCachingParentLocalNetworkAttrTypes describes V4ComputersInventoryComputerContentCachingParentLocalNetworkModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerContentCachingParentLocalNetworkAttrTypes = map[string]attr.Type{
	"content_caching_parent_local_network_id": types.StringType,
	"speed": types.Int64Type,
	"wired": types.BoolType,
}

var v4ComputersInventoryComputerContentCachingParentLocalNetworkObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerContentCachingParentLocalNetworkAttrTypes}

// V4ComputersInventoryComputerDiskEncryptionModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerDiskEncryptionModel struct {
	BootPartitionEncryptionDetails      types.Object `tfsdk:"boot_partition_encryption_details"`
	DiskEncryptionConfigurationName     types.String `tfsdk:"disk_encryption_configuration_name"`
	FileVault2EligibilityMessage        types.String `tfsdk:"file_vault2_eligibility_message"`
	FileVault2Enabled                   types.Bool   `tfsdk:"file_vault2_enabled"`
	FileVault2EnabledUserNames          types.Set    `tfsdk:"file_vault2_enabled_user_names"`
	IndividualRecoveryKeyValidityStatus types.String `tfsdk:"individual_recovery_key_validity_status"`
	InstitutionalRecoveryKeyPresent     types.Bool   `tfsdk:"institutional_recovery_key_present"`
}

// v4ComputersInventoryComputerDiskEncryptionAttrTypes describes V4ComputersInventoryComputerDiskEncryptionModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerDiskEncryptionAttrTypes = map[string]attr.Type{
	"boot_partition_encryption_details":       v4ComputersInventoryComputerPartitionEncryptionObjectType,
	"disk_encryption_configuration_name":      types.StringType,
	"file_vault2_eligibility_message":         types.StringType,
	"file_vault2_enabled":                     types.BoolType,
	"file_vault2_enabled_user_names":          types.SetType{ElemType: types.StringType},
	"individual_recovery_key_validity_status": types.StringType,
	"institutional_recovery_key_present":      types.BoolType,
}

var v4ComputersInventoryComputerDiskEncryptionObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerDiskEncryptionAttrTypes}

// V4ComputersInventoryComputerPartitionEncryptionModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerPartitionEncryptionModel struct {
	PartitionFileVault2Percent types.Int64  `tfsdk:"partition_file_vault2_percent"`
	PartitionFileVault2State   types.String `tfsdk:"partition_file_vault2_state"`
	PartitionName              types.String `tfsdk:"partition_name"`
}

// v4ComputersInventoryComputerPartitionEncryptionAttrTypes describes V4ComputersInventoryComputerPartitionEncryptionModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerPartitionEncryptionAttrTypes = map[string]attr.Type{
	"partition_file_vault2_percent": types.Int64Type,
	"partition_file_vault2_state":   types.StringType,
	"partition_name":                types.StringType,
}

var v4ComputersInventoryComputerPartitionEncryptionObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerPartitionEncryptionAttrTypes}

// V4ComputersInventoryComputerExtensionAttributeModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerExtensionAttributeModel struct {
	DataType     types.String `tfsdk:"data_type"`
	DefinitionID types.String `tfsdk:"definition_id"`
	Description  types.String `tfsdk:"description"`
	Enabled      types.Bool   `tfsdk:"enabled"`
	InputType    types.String `tfsdk:"input_type"`
	MultiValue   types.Bool   `tfsdk:"multi_value"`
	Name         types.String `tfsdk:"name"`
	Options      types.Set    `tfsdk:"options"`
	Values       types.Set    `tfsdk:"values"`
}

// v4ComputersInventoryComputerExtensionAttributeAttrTypes describes V4ComputersInventoryComputerExtensionAttributeModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerExtensionAttributeAttrTypes = map[string]attr.Type{
	"data_type":     types.StringType,
	"definition_id": types.StringType,
	"description":   types.StringType,
	"enabled":       types.BoolType,
	"input_type":    types.StringType,
	"multi_value":   types.BoolType,
	"name":          types.StringType,
	"options":       types.SetType{ElemType: types.StringType},
	"values":        types.SetType{ElemType: types.StringType},
}

var v4ComputersInventoryComputerExtensionAttributeObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerExtensionAttributeAttrTypes}

// V4ComputersInventoryGroupMembershipModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryGroupMembershipModel struct {
	GroupDescription types.String `tfsdk:"group_description"`
	GroupID          types.String `tfsdk:"group_id"`
	GroupName        types.String `tfsdk:"group_name"`
	SmartGroup       types.Bool   `tfsdk:"smart_group"`
}

// v4ComputersInventoryGroupMembershipAttrTypes describes V4ComputersInventoryGroupMembershipModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryGroupMembershipAttrTypes = map[string]attr.Type{
	"group_description": types.StringType,
	"group_id":          types.StringType,
	"group_name":        types.StringType,
	"smart_group":       types.BoolType,
}

var v4ComputersInventoryGroupMembershipObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryGroupMembershipAttrTypes}

// V4ComputersInventoryComputerIbeaconModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerIbeaconModel struct {
	Name types.String `tfsdk:"name"`
}

// v4ComputersInventoryComputerIbeaconAttrTypes describes V4ComputersInventoryComputerIbeaconModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerIbeaconAttrTypes = map[string]attr.Type{
	"name": types.StringType,
}

var v4ComputersInventoryComputerIbeaconObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerIbeaconAttrTypes}

// V4ComputersInventoryComputerLicensedSoftwareModel is one element of a nested attribute.
//
// It is a sibling of the resource model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V4ComputersInventoryComputerLicensedSoftwareModel struct {
	ID   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
}

// v4ComputersInventoryComputerLicensedSoftwareAttrTypes describes V4ComputersInventoryComputerLicensedSoftwareModel to the framework.
//
// It is declared once and referenced by both conversion helpers, so the shape
// cannot drift between the direction that reads it and the direction that writes it.
var v4ComputersInventoryComputerLicensedSoftwareAttrTypes = map[string]attr.Type{
	"id":   types.StringType,
	"name": types.StringType,
}

var v4ComputersInventoryComputerLicensedSoftwareObjectType = types.ObjectType{AttrTypes: v4ComputersInventoryComputerLicensedSoftwareAttrTypes}
