// Code generated by tfpfgen from blueprints/thousandeyes-kiota
// (sha256:434ad04ce572e36db37385f5f233e261de50e3736b4a1586468ad4a66a893ca5). DO NOT EDIT.

package credential

import (
	"context"

	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes-kiota/internal/sdk/models"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes-kiota/internal/services/common/convert"
)

// mapRemoteStateToTerraform maps the API's response onto Terraform state.
//
// This function replaces what a reflection-based provider does at runtime. Being
// generated code, a field whose conversion is wrong is a compile error rather
// than a surprise during apply.
func mapRemoteStateToTerraform(ctx context.Context, data *CredentialResourceModel, remote models.Credentials_API_Credentialable) {
	if remote == nil {
		tflog.Debug(ctx, "remote resource is nil, leaving state untouched", map[string]any{
			"resource": TypeName,
		})
		return
	}

	data.ID = convert.PtrStringToFramework(remote.GetId())
	data.Name = convert.PtrStringToFramework(remote.GetName())
	data.Value = convert.PtrStringToFramework(remote.GetValue())

	tflog.Debug(ctx, "mapped remote state", map[string]any{"resource": TypeName})
}
