# Code generated by tfpfgen. DO NOT EDIT.

resource "jamfpro_v1_log_flushing_task" "example" {
  qualifier             = "tfacc-qualifier"
  retention_period      = 1
  retention_period_unit = "tfacc-retention-period-unit"
}
