// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:e9fc089728e964a2ce1adf1c51444126c782ff30e172933b5177fd9a4982f6db). DO NOT EDIT.

package role

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// RoleResourceModel is the Terraform state for a thousandeyes_role.
//
// Field order follows the schema, and the timeouts value is last.
type RoleResourceModel struct {
	IsBuiltin   types.Bool     `tfsdk:"is_builtin"`
	Name        types.String   `tfsdk:"name"`
	Permissions types.Set      `tfsdk:"permissions"`
	ID          types.String   `tfsdk:"id"`
	Timeouts    timeouts.Value `tfsdk:"timeouts"`
}
