// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:e9fc089728e964a2ce1adf1c51444126c782ff30e172933b5177fd9a4982f6db). DO NOT EDIT.

package role

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	thousandeyes "github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/client"
	commonschema "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/services/common/schema"
)

const (
	// ResourceName is the Terraform type this resource registers as.
	ResourceName = "thousandeyes_role"

	// Default per-operation timeouts, in seconds. A practitioner overrides them
	// with the resource's timeouts block.
	CreateTimeout = 180
	ReadTimeout   = 180
	UpdateTimeout = 180
	DeleteTimeout = 180
)

// Compile-time assertions that this resource implements what it claims to. They
// turn a missing method into a build failure rather than a runtime surprise.
var (
	_ resource.Resource                = (*RoleResource)(nil)
	_ resource.ResourceWithConfigure   = (*RoleResource)(nil)
	_ resource.ResourceWithImportState = (*RoleResource)(nil)
)

// NewRoleResource returns the thousandeyes_role resource.
func NewRoleResource() resource.Resource {
	return &RoleResource{}
}

// RoleResource implements the thousandeyes_role resource.
type RoleResource struct {
	client *thousandeyes.Client
}

// Metadata returns the resource type name.
func (r *RoleResource) Metadata(_ context.Context, _ resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = ResourceName
}

// Configure receives the configured SDK client from the provider.
func (r *RoleResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = client.ForResource(ctx, req, resp, ResourceName)
}

// ImportState maps a terraform import into state.
func (r *RoleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// Schema returns the resource schema.
func (r *RoleResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieve role.",
		Attributes: map[string]schema.Attribute{
			"is_builtin": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Flag indicating if the role is built-in (Account Admin, Organization Admin, Regular User).",
			},
			"name": schema.StringAttribute{
				Optional: true,
				MarkdownDescription: "Name of the role. Required-by-API by curation: the sweeper's field, unprobeable by " +
					"omission.",
			},
			"permissions": schema.SetAttribute{
				ElementType: types.StringType,
				Optional:    true,
				MarkdownDescription: "List of permission ids to grant (permissionId values from the permissions API). The " +
					"response echoes permissions as expanded objects, never this id list, so state carries the " +
					"configured value. Effectively required: a permission-less role create answers 500 (live " +
					"probe, 2026-08-03). <!-- probed:7.0.98-t1785772662063 --> The API enforces this field's " +
					"presence, which the specification does not declare. <!-- /probed -->",
			},
			"id": schema.StringAttribute{
				Computed: true,
				MarkdownDescription: "Unique ID representing the role. Named `id` per the import convention; the wire field " +
					"stays roleId.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": commonschema.ResourceTimeouts(ctx),
		},
	}
}
