// Code generated by tfpfgen from blueprints/thousandeyes-kiota
// (sha256:82a8701a0f77258aba49054f577921f206b8fcaecd42c5fb57874c3fd6799173). DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
)

// DataSources returns every data source this provider serves.
//
// This file is generated in full. Add a data source by adding a blueprint and
// regenerating, not by editing here.
func (p *Provider) DataSources(_ context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{}
}
