// Code generated by tfpfgen from blueprints/thousandeyes-kiota
// (sha256:434ad04ce572e36db37385f5f233e261de50e3736b4a1586468ad4a66a893ca5). DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/ephemeral"

	v7CredentialEph "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes-kiota/internal/services/ephemerals/credentials/v7/credential"
)

// EphemeralResources returns every ephemeral resource this provider serves.
//
// This file is generated in full. Add an ephemeral by adding a blueprint and
// regenerating, not by editing here.
func (p *Provider) EphemeralResources(_ context.Context) []func() ephemeral.EphemeralResource {
	return []func() ephemeral.EphemeralResource{
		v7CredentialEph.NewCredentialEphemeral,
	}
}
