// Code generated by tfpfgen from blueprints/thousandeyes-kiota
// (sha256:82a8701a0f77258aba49054f577921f206b8fcaecd42c5fb57874c3fd6799173). DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/resource"

	v7Tag "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes-kiota/internal/services/resources/tags/v7/tag"
)

// Resources returns every managed resource this provider serves.
//
// This file is generated in full. Add a resource by adding a blueprint and
// regenerating, not by editing here.
func (p *Provider) Resources(_ context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		v7Tag.NewTagResource,
	}
}
