// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ApiIntegrationResponse struct {
	// The accessTokenLifetimeSeconds property
	accessTokenLifetimeSeconds *int32
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Type of API Client:    * `CLIENT_CREDENTIALS` - A client ID and secret have been generated for this integration.    * `NATIVE_APP_OAUTH` - A native app (i.e., Jamf Reset) has been linked to this integration for auth code grant type via Managed App Config.    * `NONE` - No client is currently associated with this integration.
	appType *ApiIntegrationResponse_appType
	// The authorizationScopes property
	authorizationScopes []string
	// The clientId property
	clientId *string
	// The displayName property
	displayName *string
	// The enabled property
	enabled *bool
	// The id property
	id *int32
}

// NewApiIntegrationResponse instantiates a new ApiIntegrationResponse and sets the default values.
func NewApiIntegrationResponse() *ApiIntegrationResponse {
	m := &ApiIntegrationResponse{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateApiIntegrationResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateApiIntegrationResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewApiIntegrationResponse(), nil
}

// GetAccessTokenLifetimeSeconds gets the accessTokenLifetimeSeconds property value. The accessTokenLifetimeSeconds property
// returns a *int32 when successful
func (m *ApiIntegrationResponse) GetAccessTokenLifetimeSeconds() *int32 {
	return m.accessTokenLifetimeSeconds
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ApiIntegrationResponse) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAppType gets the appType property value. Type of API Client:    * `CLIENT_CREDENTIALS` - A client ID and secret have been generated for this integration.    * `NATIVE_APP_OAUTH` - A native app (i.e., Jamf Reset) has been linked to this integration for auth code grant type via Managed App Config.    * `NONE` - No client is currently associated with this integration.
// returns a *ApiIntegrationResponse_appType when successful
func (m *ApiIntegrationResponse) GetAppType() *ApiIntegrationResponse_appType {
	return m.appType
}

// GetAuthorizationScopes gets the authorizationScopes property value. The authorizationScopes property
// returns a []string when successful
func (m *ApiIntegrationResponse) GetAuthorizationScopes() []string {
	return m.authorizationScopes
}

// GetClientId gets the clientId property value. The clientId property
// returns a *string when successful
func (m *ApiIntegrationResponse) GetClientId() *string {
	return m.clientId
}

// GetDisplayName gets the displayName property value. The displayName property
// returns a *string when successful
func (m *ApiIntegrationResponse) GetDisplayName() *string {
	return m.displayName
}

// GetEnabled gets the enabled property value. The enabled property
// returns a *bool when successful
func (m *ApiIntegrationResponse) GetEnabled() *bool {
	return m.enabled
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ApiIntegrationResponse) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["accessTokenLifetimeSeconds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAccessTokenLifetimeSeconds(val)
		}
		return nil
	}
	res["appType"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseApiIntegrationResponse_appType)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAppType(val.(*ApiIntegrationResponse_appType))
		}
		return nil
	}
	res["authorizationScopes"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetAuthorizationScopes(res)
		}
		return nil
	}
	res["clientId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetClientId(val)
		}
		return nil
	}
	res["displayName"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDisplayName(val)
		}
		return nil
	}
	res["enabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEnabled(val)
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	return res
}

// GetId gets the id property value. The id property
// returns a *int32 when successful
func (m *ApiIntegrationResponse) GetId() *int32 {
	return m.id
}

// Serialize serializes information the current object
func (m *ApiIntegrationResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt32Value("accessTokenLifetimeSeconds", m.GetAccessTokenLifetimeSeconds())
		if err != nil {
			return err
		}
	}
	if m.GetAuthorizationScopes() != nil {
		err := writer.WriteCollectionOfStringValues("authorizationScopes", m.GetAuthorizationScopes())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("displayName", m.GetDisplayName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("enabled", m.GetEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("id", m.GetId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAccessTokenLifetimeSeconds sets the accessTokenLifetimeSeconds property value. The accessTokenLifetimeSeconds property
func (m *ApiIntegrationResponse) SetAccessTokenLifetimeSeconds(value *int32) {
	m.accessTokenLifetimeSeconds = value
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ApiIntegrationResponse) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAppType sets the appType property value. Type of API Client:    * `CLIENT_CREDENTIALS` - A client ID and secret have been generated for this integration.    * `NATIVE_APP_OAUTH` - A native app (i.e., Jamf Reset) has been linked to this integration for auth code grant type via Managed App Config.    * `NONE` - No client is currently associated with this integration.
func (m *ApiIntegrationResponse) SetAppType(value *ApiIntegrationResponse_appType) {
	m.appType = value
}

// SetAuthorizationScopes sets the authorizationScopes property value. The authorizationScopes property
func (m *ApiIntegrationResponse) SetAuthorizationScopes(value []string) {
	m.authorizationScopes = value
}

// SetClientId sets the clientId property value. The clientId property
func (m *ApiIntegrationResponse) SetClientId(value *string) {
	m.clientId = value
}

// SetDisplayName sets the displayName property value. The displayName property
func (m *ApiIntegrationResponse) SetDisplayName(value *string) {
	m.displayName = value
}

// SetEnabled sets the enabled property value. The enabled property
func (m *ApiIntegrationResponse) SetEnabled(value *bool) {
	m.enabled = value
}

// SetId sets the id property value. The id property
func (m *ApiIntegrationResponse) SetId(value *int32) {
	m.id = value
}

type ApiIntegrationResponseable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAccessTokenLifetimeSeconds() *int32
	GetAppType() *ApiIntegrationResponse_appType
	GetAuthorizationScopes() []string
	GetClientId() *string
	GetDisplayName() *string
	GetEnabled() *bool
	GetId() *int32
	SetAccessTokenLifetimeSeconds(value *int32)
	SetAppType(value *ApiIntegrationResponse_appType)
	SetAuthorizationScopes(value []string)
	SetClientId(value *string)
	SetDisplayName(value *string)
	SetEnabled(value *bool)
	SetId(value *int32)
}
