// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AppConfigReinstallCode struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The reinstallCode property
	reinstallCode *string
}

// NewAppConfigReinstallCode instantiates a new AppConfigReinstallCode and sets the default values.
func NewAppConfigReinstallCode() *AppConfigReinstallCode {
	m := &AppConfigReinstallCode{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateAppConfigReinstallCodeFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAppConfigReinstallCodeFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewAppConfigReinstallCode(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AppConfigReinstallCode) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AppConfigReinstallCode) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["reinstallCode"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetReinstallCode(val)
		}
		return nil
	}
	return res
}

// GetReinstallCode gets the reinstallCode property value. The reinstallCode property
// returns a *string when successful
func (m *AppConfigReinstallCode) GetReinstallCode() *string {
	return m.reinstallCode
}

// Serialize serializes information the current object
func (m *AppConfigReinstallCode) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("reinstallCode", m.GetReinstallCode())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AppConfigReinstallCode) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetReinstallCode sets the reinstallCode property value. The reinstallCode property
func (m *AppConfigReinstallCode) SetReinstallCode(value *string) {
	m.reinstallCode = value
}

type AppConfigReinstallCodeable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetReinstallCode() *string
	SetReinstallCode(value *string)
}
