// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AssignRemoveProfileResponseSyncState struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The failureCount property
	failureCount *int32
	// The id property
	id *int32
	// The profileUUID property
	profileUUID *string
	// The serialNumber property
	serialNumber *string
	// The syncStatus property
	syncStatus *string
	// The timestamp property
	timestamp *int32
}

// NewAssignRemoveProfileResponseSyncState instantiates a new AssignRemoveProfileResponseSyncState and sets the default values.
func NewAssignRemoveProfileResponseSyncState() *AssignRemoveProfileResponseSyncState {
	m := &AssignRemoveProfileResponseSyncState{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateAssignRemoveProfileResponseSyncStateFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAssignRemoveProfileResponseSyncStateFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewAssignRemoveProfileResponseSyncState(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AssignRemoveProfileResponseSyncState) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFailureCount gets the failureCount property value. The failureCount property
// returns a *int32 when successful
func (m *AssignRemoveProfileResponseSyncState) GetFailureCount() *int32 {
	return m.failureCount
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AssignRemoveProfileResponseSyncState) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["failureCount"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetFailureCount(val)
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["profileUUID"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProfileUUID(val)
		}
		return nil
	}
	res["serialNumber"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSerialNumber(val)
		}
		return nil
	}
	res["syncStatus"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSyncStatus(val)
		}
		return nil
	}
	res["timestamp"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTimestamp(val)
		}
		return nil
	}
	return res
}

// GetId gets the id property value. The id property
// returns a *int32 when successful
func (m *AssignRemoveProfileResponseSyncState) GetId() *int32 {
	return m.id
}

// GetProfileUUID gets the profileUUID property value. The profileUUID property
// returns a *string when successful
func (m *AssignRemoveProfileResponseSyncState) GetProfileUUID() *string {
	return m.profileUUID
}

// GetSerialNumber gets the serialNumber property value. The serialNumber property
// returns a *string when successful
func (m *AssignRemoveProfileResponseSyncState) GetSerialNumber() *string {
	return m.serialNumber
}

// GetSyncStatus gets the syncStatus property value. The syncStatus property
// returns a *string when successful
func (m *AssignRemoveProfileResponseSyncState) GetSyncStatus() *string {
	return m.syncStatus
}

// GetTimestamp gets the timestamp property value. The timestamp property
// returns a *int32 when successful
func (m *AssignRemoveProfileResponseSyncState) GetTimestamp() *int32 {
	return m.timestamp
}

// Serialize serializes information the current object
func (m *AssignRemoveProfileResponseSyncState) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt32Value("failureCount", m.GetFailureCount())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("id", m.GetId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("profileUUID", m.GetProfileUUID())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("serialNumber", m.GetSerialNumber())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("syncStatus", m.GetSyncStatus())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("timestamp", m.GetTimestamp())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AssignRemoveProfileResponseSyncState) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetFailureCount sets the failureCount property value. The failureCount property
func (m *AssignRemoveProfileResponseSyncState) SetFailureCount(value *int32) {
	m.failureCount = value
}

// SetId sets the id property value. The id property
func (m *AssignRemoveProfileResponseSyncState) SetId(value *int32) {
	m.id = value
}

// SetProfileUUID sets the profileUUID property value. The profileUUID property
func (m *AssignRemoveProfileResponseSyncState) SetProfileUUID(value *string) {
	m.profileUUID = value
}

// SetSerialNumber sets the serialNumber property value. The serialNumber property
func (m *AssignRemoveProfileResponseSyncState) SetSerialNumber(value *string) {
	m.serialNumber = value
}

// SetSyncStatus sets the syncStatus property value. The syncStatus property
func (m *AssignRemoveProfileResponseSyncState) SetSyncStatus(value *string) {
	m.syncStatus = value
}

// SetTimestamp sets the timestamp property value. The timestamp property
func (m *AssignRemoveProfileResponseSyncState) SetTimestamp(value *int32) {
	m.timestamp = value
}

type AssignRemoveProfileResponseSyncStateable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetFailureCount() *int32
	GetId() *int32
	GetProfileUUID() *string
	GetSerialNumber() *string
	GetSyncStatus() *string
	GetTimestamp() *int32
	SetFailureCount(value *int32)
	SetId(value *int32)
	SetProfileUUID(value *string)
	SetSerialNumber(value *string)
	SetSyncStatus(value *string)
	SetTimestamp(value *int32)
}
