// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AssignmentDtoV1 struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The deviceId property
	deviceId *string
	// The selected property
	selected *bool
}

// NewAssignmentDtoV1 instantiates a new AssignmentDtoV1 and sets the default values.
func NewAssignmentDtoV1() *AssignmentDtoV1 {
	m := &AssignmentDtoV1{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateAssignmentDtoV1FromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAssignmentDtoV1FromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewAssignmentDtoV1(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AssignmentDtoV1) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetDeviceId gets the deviceId property value. The deviceId property
// returns a *string when successful
func (m *AssignmentDtoV1) GetDeviceId() *string {
	return m.deviceId
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AssignmentDtoV1) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["deviceId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDeviceId(val)
		}
		return nil
	}
	res["selected"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSelected(val)
		}
		return nil
	}
	return res
}

// GetSelected gets the selected property value. The selected property
// returns a *bool when successful
func (m *AssignmentDtoV1) GetSelected() *bool {
	return m.selected
}

// Serialize serializes information the current object
func (m *AssignmentDtoV1) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("deviceId", m.GetDeviceId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("selected", m.GetSelected())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AssignmentDtoV1) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetDeviceId sets the deviceId property value. The deviceId property
func (m *AssignmentDtoV1) SetDeviceId(value *string) {
	m.deviceId = value
}

// SetSelected sets the selected property value. The selected property
func (m *AssignmentDtoV1) SetSelected(value *bool) {
	m.selected = value
}

type AssignmentDtoV1able interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetDeviceId() *string
	GetSelected() *bool
	SetDeviceId(value *string)
	SetSelected(value *bool)
}
