// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// Type of Entra ID connection
type AzureServerConfigurationRequest_type int

const (
	PUBLIC_AZURESERVERCONFIGURATIONREQUEST_TYPE AzureServerConfigurationRequest_type = iota
	GCC_HIGH_AZURESERVERCONFIGURATIONREQUEST_TYPE
)

func (i AzureServerConfigurationRequest_type) String() string {
	return []string{"PUBLIC", "GCC_HIGH"}[i]
}

func ParseAzureServerConfigurationRequest_type(v string) (any, error) {
	result := PUBLIC_AZURESERVERCONFIGURATIONREQUEST_TYPE
	switch v {
	case "PUBLIC":
		result = PUBLIC_AZURESERVERCONFIGURATIONREQUEST_TYPE
	case "GCC_HIGH":
		result = GCC_HIGH_AZURESERVERCONFIGURATIONREQUEST_TYPE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeAzureServerConfigurationRequest_type(values []AzureServerConfigurationRequest_type) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i AzureServerConfigurationRequest_type) isMultiValue() bool {
	return false
}
