// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// AzureServerConfigurationUpdate azure Cloud Identity Provider configuration update
type AzureServerConfigurationUpdate struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The enabled property
	enabled *bool
	// The id property
	id *string
	// Azure Cloud Identity Provider mappings
	mappings AzureMappingsable
	// Use this field to enable membership calculation optimization. This setting would not apply to Single Sign On
	membershipCalculationOptimizationEnabled *bool
	// The searchTimeout property
	searchTimeout *int32
	// Use this field to enable transitive membership lookup. This setting would not apply to Single Sign On
	transitiveDirectoryMembershipEnabled *bool
	// Use this field to enable transitive membership lookup with Single Sign On
	transitiveMembershipEnabled *bool
	// Use this field to set user field mapping for transitive membership lookup with Single Sign On
	transitiveMembershipUserField *string
}

// NewAzureServerConfigurationUpdate instantiates a new AzureServerConfigurationUpdate and sets the default values.
func NewAzureServerConfigurationUpdate() *AzureServerConfigurationUpdate {
	m := &AzureServerConfigurationUpdate{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateAzureServerConfigurationUpdateFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAzureServerConfigurationUpdateFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewAzureServerConfigurationUpdate(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AzureServerConfigurationUpdate) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetEnabled gets the enabled property value. The enabled property
// returns a *bool when successful
func (m *AzureServerConfigurationUpdate) GetEnabled() *bool {
	return m.enabled
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AzureServerConfigurationUpdate) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["enabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEnabled(val)
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["mappings"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateAzureMappingsFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMappings(val.(AzureMappingsable))
		}
		return nil
	}
	res["membershipCalculationOptimizationEnabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMembershipCalculationOptimizationEnabled(val)
		}
		return nil
	}
	res["searchTimeout"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSearchTimeout(val)
		}
		return nil
	}
	res["transitiveDirectoryMembershipEnabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTransitiveDirectoryMembershipEnabled(val)
		}
		return nil
	}
	res["transitiveMembershipEnabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTransitiveMembershipEnabled(val)
		}
		return nil
	}
	res["transitiveMembershipUserField"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTransitiveMembershipUserField(val)
		}
		return nil
	}
	return res
}

// GetId gets the id property value. The id property
// returns a *string when successful
func (m *AzureServerConfigurationUpdate) GetId() *string {
	return m.id
}

// GetMappings gets the mappings property value. Azure Cloud Identity Provider mappings
// returns a AzureMappingsable when successful
func (m *AzureServerConfigurationUpdate) GetMappings() AzureMappingsable {
	return m.mappings
}

// GetMembershipCalculationOptimizationEnabled gets the membershipCalculationOptimizationEnabled property value. Use this field to enable membership calculation optimization. This setting would not apply to Single Sign On
// returns a *bool when successful
func (m *AzureServerConfigurationUpdate) GetMembershipCalculationOptimizationEnabled() *bool {
	return m.membershipCalculationOptimizationEnabled
}

// GetSearchTimeout gets the searchTimeout property value. The searchTimeout property
// returns a *int32 when successful
func (m *AzureServerConfigurationUpdate) GetSearchTimeout() *int32 {
	return m.searchTimeout
}

// GetTransitiveDirectoryMembershipEnabled gets the transitiveDirectoryMembershipEnabled property value. Use this field to enable transitive membership lookup. This setting would not apply to Single Sign On
// returns a *bool when successful
func (m *AzureServerConfigurationUpdate) GetTransitiveDirectoryMembershipEnabled() *bool {
	return m.transitiveDirectoryMembershipEnabled
}

// GetTransitiveMembershipEnabled gets the transitiveMembershipEnabled property value. Use this field to enable transitive membership lookup with Single Sign On
// returns a *bool when successful
func (m *AzureServerConfigurationUpdate) GetTransitiveMembershipEnabled() *bool {
	return m.transitiveMembershipEnabled
}

// GetTransitiveMembershipUserField gets the transitiveMembershipUserField property value. Use this field to set user field mapping for transitive membership lookup with Single Sign On
// returns a *string when successful
func (m *AzureServerConfigurationUpdate) GetTransitiveMembershipUserField() *string {
	return m.transitiveMembershipUserField
}

// Serialize serializes information the current object
func (m *AzureServerConfigurationUpdate) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteBoolValue("enabled", m.GetEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("id", m.GetId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("mappings", m.GetMappings())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("membershipCalculationOptimizationEnabled", m.GetMembershipCalculationOptimizationEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("searchTimeout", m.GetSearchTimeout())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("transitiveDirectoryMembershipEnabled", m.GetTransitiveDirectoryMembershipEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("transitiveMembershipEnabled", m.GetTransitiveMembershipEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("transitiveMembershipUserField", m.GetTransitiveMembershipUserField())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AzureServerConfigurationUpdate) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetEnabled sets the enabled property value. The enabled property
func (m *AzureServerConfigurationUpdate) SetEnabled(value *bool) {
	m.enabled = value
}

// SetId sets the id property value. The id property
func (m *AzureServerConfigurationUpdate) SetId(value *string) {
	m.id = value
}

// SetMappings sets the mappings property value. Azure Cloud Identity Provider mappings
func (m *AzureServerConfigurationUpdate) SetMappings(value AzureMappingsable) {
	m.mappings = value
}

// SetMembershipCalculationOptimizationEnabled sets the membershipCalculationOptimizationEnabled property value. Use this field to enable membership calculation optimization. This setting would not apply to Single Sign On
func (m *AzureServerConfigurationUpdate) SetMembershipCalculationOptimizationEnabled(value *bool) {
	m.membershipCalculationOptimizationEnabled = value
}

// SetSearchTimeout sets the searchTimeout property value. The searchTimeout property
func (m *AzureServerConfigurationUpdate) SetSearchTimeout(value *int32) {
	m.searchTimeout = value
}

// SetTransitiveDirectoryMembershipEnabled sets the transitiveDirectoryMembershipEnabled property value. Use this field to enable transitive membership lookup. This setting would not apply to Single Sign On
func (m *AzureServerConfigurationUpdate) SetTransitiveDirectoryMembershipEnabled(value *bool) {
	m.transitiveDirectoryMembershipEnabled = value
}

// SetTransitiveMembershipEnabled sets the transitiveMembershipEnabled property value. Use this field to enable transitive membership lookup with Single Sign On
func (m *AzureServerConfigurationUpdate) SetTransitiveMembershipEnabled(value *bool) {
	m.transitiveMembershipEnabled = value
}

// SetTransitiveMembershipUserField sets the transitiveMembershipUserField property value. Use this field to set user field mapping for transitive membership lookup with Single Sign On
func (m *AzureServerConfigurationUpdate) SetTransitiveMembershipUserField(value *string) {
	m.transitiveMembershipUserField = value
}

type AzureServerConfigurationUpdateable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetEnabled() *bool
	GetId() *string
	GetMappings() AzureMappingsable
	GetMembershipCalculationOptimizationEnabled() *bool
	GetSearchTimeout() *int32
	GetTransitiveDirectoryMembershipEnabled() *bool
	GetTransitiveMembershipEnabled() *bool
	GetTransitiveMembershipUserField() *string
	SetEnabled(value *bool)
	SetId(value *string)
	SetMappings(value AzureMappingsable)
	SetMembershipCalculationOptimizationEnabled(value *bool)
	SetSearchTimeout(value *int32)
	SetTransitiveDirectoryMembershipEnabled(value *bool)
	SetTransitiveMembershipEnabled(value *bool)
	SetTransitiveMembershipUserField(value *string)
}
