// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CacheSettings struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The cacheType property
	cacheType *string
	// The default is for Jamf Pro to generate a UUID, so we can only give an example instead.
	cacheUniqueId *string
	// The directoryTimeToLiveSeconds property
	directoryTimeToLiveSeconds *int32
	// The ehcacheMaxBytesLocalHeap property
	ehcacheMaxBytesLocalHeap *string
	// The elasticache property
	elasticache *bool
	// The id property
	id *string
	// The memcachedEndpoints property
	memcachedEndpoints []MemcachedEndpointsable
	// The name property
	name *string
	// The timeToIdleSeconds property
	timeToIdleSeconds *int32
	// The timeToLiveSeconds property
	timeToLiveSeconds *int32
}

// NewCacheSettings instantiates a new CacheSettings and sets the default values.
func NewCacheSettings() *CacheSettings {
	m := &CacheSettings{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCacheSettingsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCacheSettingsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCacheSettings(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CacheSettings) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetCacheType gets the cacheType property value. The cacheType property
// returns a *string when successful
func (m *CacheSettings) GetCacheType() *string {
	return m.cacheType
}

// GetCacheUniqueId gets the cacheUniqueId property value. The default is for Jamf Pro to generate a UUID, so we can only give an example instead.
// returns a *string when successful
func (m *CacheSettings) GetCacheUniqueId() *string {
	return m.cacheUniqueId
}

// GetDirectoryTimeToLiveSeconds gets the directoryTimeToLiveSeconds property value. The directoryTimeToLiveSeconds property
// returns a *int32 when successful
func (m *CacheSettings) GetDirectoryTimeToLiveSeconds() *int32 {
	return m.directoryTimeToLiveSeconds
}

// GetEhcacheMaxBytesLocalHeap gets the ehcacheMaxBytesLocalHeap property value. The ehcacheMaxBytesLocalHeap property
// returns a *string when successful
func (m *CacheSettings) GetEhcacheMaxBytesLocalHeap() *string {
	return m.ehcacheMaxBytesLocalHeap
}

// GetElasticache gets the elasticache property value. The elasticache property
// returns a *bool when successful
func (m *CacheSettings) GetElasticache() *bool {
	return m.elasticache
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CacheSettings) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["cacheType"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCacheType(val)
		}
		return nil
	}
	res["cacheUniqueId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCacheUniqueId(val)
		}
		return nil
	}
	res["directoryTimeToLiveSeconds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDirectoryTimeToLiveSeconds(val)
		}
		return nil
	}
	res["ehcacheMaxBytesLocalHeap"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEhcacheMaxBytesLocalHeap(val)
		}
		return nil
	}
	res["elasticache"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetElasticache(val)
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["memcachedEndpoints"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateMemcachedEndpointsFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]MemcachedEndpointsable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(MemcachedEndpointsable)
				}
			}
			m.SetMemcachedEndpoints(res)
		}
		return nil
	}
	res["name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetName(val)
		}
		return nil
	}
	res["timeToIdleSeconds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTimeToIdleSeconds(val)
		}
		return nil
	}
	res["timeToLiveSeconds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTimeToLiveSeconds(val)
		}
		return nil
	}
	return res
}

// GetId gets the id property value. The id property
// returns a *string when successful
func (m *CacheSettings) GetId() *string {
	return m.id
}

// GetMemcachedEndpoints gets the memcachedEndpoints property value. The memcachedEndpoints property
// returns a []MemcachedEndpointsable when successful
func (m *CacheSettings) GetMemcachedEndpoints() []MemcachedEndpointsable {
	return m.memcachedEndpoints
}

// GetName gets the name property value. The name property
// returns a *string when successful
func (m *CacheSettings) GetName() *string {
	return m.name
}

// GetTimeToIdleSeconds gets the timeToIdleSeconds property value. The timeToIdleSeconds property
// returns a *int32 when successful
func (m *CacheSettings) GetTimeToIdleSeconds() *int32 {
	return m.timeToIdleSeconds
}

// GetTimeToLiveSeconds gets the timeToLiveSeconds property value. The timeToLiveSeconds property
// returns a *int32 when successful
func (m *CacheSettings) GetTimeToLiveSeconds() *int32 {
	return m.timeToLiveSeconds
}

// Serialize serializes information the current object
func (m *CacheSettings) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("cacheType", m.GetCacheType())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("cacheUniqueId", m.GetCacheUniqueId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("directoryTimeToLiveSeconds", m.GetDirectoryTimeToLiveSeconds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("ehcacheMaxBytesLocalHeap", m.GetEhcacheMaxBytesLocalHeap())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("elasticache", m.GetElasticache())
		if err != nil {
			return err
		}
	}
	if m.GetMemcachedEndpoints() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetMemcachedEndpoints()))
		for i, v := range m.GetMemcachedEndpoints() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("memcachedEndpoints", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("name", m.GetName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("timeToIdleSeconds", m.GetTimeToIdleSeconds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("timeToLiveSeconds", m.GetTimeToLiveSeconds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CacheSettings) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetCacheType sets the cacheType property value. The cacheType property
func (m *CacheSettings) SetCacheType(value *string) {
	m.cacheType = value
}

// SetCacheUniqueId sets the cacheUniqueId property value. The default is for Jamf Pro to generate a UUID, so we can only give an example instead.
func (m *CacheSettings) SetCacheUniqueId(value *string) {
	m.cacheUniqueId = value
}

// SetDirectoryTimeToLiveSeconds sets the directoryTimeToLiveSeconds property value. The directoryTimeToLiveSeconds property
func (m *CacheSettings) SetDirectoryTimeToLiveSeconds(value *int32) {
	m.directoryTimeToLiveSeconds = value
}

// SetEhcacheMaxBytesLocalHeap sets the ehcacheMaxBytesLocalHeap property value. The ehcacheMaxBytesLocalHeap property
func (m *CacheSettings) SetEhcacheMaxBytesLocalHeap(value *string) {
	m.ehcacheMaxBytesLocalHeap = value
}

// SetElasticache sets the elasticache property value. The elasticache property
func (m *CacheSettings) SetElasticache(value *bool) {
	m.elasticache = value
}

// SetId sets the id property value. The id property
func (m *CacheSettings) SetId(value *string) {
	m.id = value
}

// SetMemcachedEndpoints sets the memcachedEndpoints property value. The memcachedEndpoints property
func (m *CacheSettings) SetMemcachedEndpoints(value []MemcachedEndpointsable) {
	m.memcachedEndpoints = value
}

// SetName sets the name property value. The name property
func (m *CacheSettings) SetName(value *string) {
	m.name = value
}

// SetTimeToIdleSeconds sets the timeToIdleSeconds property value. The timeToIdleSeconds property
func (m *CacheSettings) SetTimeToIdleSeconds(value *int32) {
	m.timeToIdleSeconds = value
}

// SetTimeToLiveSeconds sets the timeToLiveSeconds property value. The timeToLiveSeconds property
func (m *CacheSettings) SetTimeToLiveSeconds(value *int32) {
	m.timeToLiveSeconds = value
}

type CacheSettingsable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetCacheType() *string
	GetCacheUniqueId() *string
	GetDirectoryTimeToLiveSeconds() *int32
	GetEhcacheMaxBytesLocalHeap() *string
	GetElasticache() *bool
	GetId() *string
	GetMemcachedEndpoints() []MemcachedEndpointsable
	GetName() *string
	GetTimeToIdleSeconds() *int32
	GetTimeToLiveSeconds() *int32
	SetCacheType(value *string)
	SetCacheUniqueId(value *string)
	SetDirectoryTimeToLiveSeconds(value *int32)
	SetEhcacheMaxBytesLocalHeap(value *string)
	SetElasticache(value *bool)
	SetId(value *string)
	SetMemcachedEndpoints(value []MemcachedEndpointsable)
	SetName(value *string)
	SetTimeToIdleSeconds(value *int32)
	SetTimeToLiveSeconds(value *int32)
}
