// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CertificateRecord struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The issuerX500Principal property
	issuerX500Principal *string
	// The keyUsage property
	keyUsage []string
	// The keyUsageExtended property
	keyUsageExtended []string
	// The notAfter property
	notAfter *int32
	// The notBefore property
	notBefore *int32
	// The serialNumber property
	serialNumber *string
	// The sha1Fingerprint property
	sha1Fingerprint *string
	// The sha256Fingerprint property
	sha256Fingerprint *string
	// The signature property
	signature Signatureable
	// The subjectX500Principal property
	subjectX500Principal *string
	// The version property
	version *int32
}

// NewCertificateRecord instantiates a new CertificateRecord and sets the default values.
func NewCertificateRecord() *CertificateRecord {
	m := &CertificateRecord{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCertificateRecordFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCertificateRecordFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCertificateRecord(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CertificateRecord) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CertificateRecord) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["issuerX500Principal"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIssuerX500Principal(val)
		}
		return nil
	}
	res["keyUsage"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetKeyUsage(res)
		}
		return nil
	}
	res["keyUsageExtended"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetKeyUsageExtended(res)
		}
		return nil
	}
	res["notAfter"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNotAfter(val)
		}
		return nil
	}
	res["notBefore"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetNotBefore(val)
		}
		return nil
	}
	res["serialNumber"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSerialNumber(val)
		}
		return nil
	}
	res["sha1Fingerprint"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSha1Fingerprint(val)
		}
		return nil
	}
	res["sha256Fingerprint"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSha256Fingerprint(val)
		}
		return nil
	}
	res["signature"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateSignatureFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSignature(val.(Signatureable))
		}
		return nil
	}
	res["subjectX500Principal"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSubjectX500Principal(val)
		}
		return nil
	}
	res["version"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetVersion(val)
		}
		return nil
	}
	return res
}

// GetIssuerX500Principal gets the issuerX500Principal property value. The issuerX500Principal property
// returns a *string when successful
func (m *CertificateRecord) GetIssuerX500Principal() *string {
	return m.issuerX500Principal
}

// GetKeyUsage gets the keyUsage property value. The keyUsage property
// returns a []string when successful
func (m *CertificateRecord) GetKeyUsage() []string {
	return m.keyUsage
}

// GetKeyUsageExtended gets the keyUsageExtended property value. The keyUsageExtended property
// returns a []string when successful
func (m *CertificateRecord) GetKeyUsageExtended() []string {
	return m.keyUsageExtended
}

// GetNotAfter gets the notAfter property value. The notAfter property
// returns a *int32 when successful
func (m *CertificateRecord) GetNotAfter() *int32 {
	return m.notAfter
}

// GetNotBefore gets the notBefore property value. The notBefore property
// returns a *int32 when successful
func (m *CertificateRecord) GetNotBefore() *int32 {
	return m.notBefore
}

// GetSerialNumber gets the serialNumber property value. The serialNumber property
// returns a *string when successful
func (m *CertificateRecord) GetSerialNumber() *string {
	return m.serialNumber
}

// GetSha1Fingerprint gets the sha1Fingerprint property value. The sha1Fingerprint property
// returns a *string when successful
func (m *CertificateRecord) GetSha1Fingerprint() *string {
	return m.sha1Fingerprint
}

// GetSha256Fingerprint gets the sha256Fingerprint property value. The sha256Fingerprint property
// returns a *string when successful
func (m *CertificateRecord) GetSha256Fingerprint() *string {
	return m.sha256Fingerprint
}

// GetSignature gets the signature property value. The signature property
// returns a Signatureable when successful
func (m *CertificateRecord) GetSignature() Signatureable {
	return m.signature
}

// GetSubjectX500Principal gets the subjectX500Principal property value. The subjectX500Principal property
// returns a *string when successful
func (m *CertificateRecord) GetSubjectX500Principal() *string {
	return m.subjectX500Principal
}

// GetVersion gets the version property value. The version property
// returns a *int32 when successful
func (m *CertificateRecord) GetVersion() *int32 {
	return m.version
}

// Serialize serializes information the current object
func (m *CertificateRecord) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("issuerX500Principal", m.GetIssuerX500Principal())
		if err != nil {
			return err
		}
	}
	if m.GetKeyUsage() != nil {
		err := writer.WriteCollectionOfStringValues("keyUsage", m.GetKeyUsage())
		if err != nil {
			return err
		}
	}
	if m.GetKeyUsageExtended() != nil {
		err := writer.WriteCollectionOfStringValues("keyUsageExtended", m.GetKeyUsageExtended())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("notAfter", m.GetNotAfter())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("notBefore", m.GetNotBefore())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("serialNumber", m.GetSerialNumber())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("sha1Fingerprint", m.GetSha1Fingerprint())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("sha256Fingerprint", m.GetSha256Fingerprint())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("signature", m.GetSignature())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("subjectX500Principal", m.GetSubjectX500Principal())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("version", m.GetVersion())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CertificateRecord) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetIssuerX500Principal sets the issuerX500Principal property value. The issuerX500Principal property
func (m *CertificateRecord) SetIssuerX500Principal(value *string) {
	m.issuerX500Principal = value
}

// SetKeyUsage sets the keyUsage property value. The keyUsage property
func (m *CertificateRecord) SetKeyUsage(value []string) {
	m.keyUsage = value
}

// SetKeyUsageExtended sets the keyUsageExtended property value. The keyUsageExtended property
func (m *CertificateRecord) SetKeyUsageExtended(value []string) {
	m.keyUsageExtended = value
}

// SetNotAfter sets the notAfter property value. The notAfter property
func (m *CertificateRecord) SetNotAfter(value *int32) {
	m.notAfter = value
}

// SetNotBefore sets the notBefore property value. The notBefore property
func (m *CertificateRecord) SetNotBefore(value *int32) {
	m.notBefore = value
}

// SetSerialNumber sets the serialNumber property value. The serialNumber property
func (m *CertificateRecord) SetSerialNumber(value *string) {
	m.serialNumber = value
}

// SetSha1Fingerprint sets the sha1Fingerprint property value. The sha1Fingerprint property
func (m *CertificateRecord) SetSha1Fingerprint(value *string) {
	m.sha1Fingerprint = value
}

// SetSha256Fingerprint sets the sha256Fingerprint property value. The sha256Fingerprint property
func (m *CertificateRecord) SetSha256Fingerprint(value *string) {
	m.sha256Fingerprint = value
}

// SetSignature sets the signature property value. The signature property
func (m *CertificateRecord) SetSignature(value Signatureable) {
	m.signature = value
}

// SetSubjectX500Principal sets the subjectX500Principal property value. The subjectX500Principal property
func (m *CertificateRecord) SetSubjectX500Principal(value *string) {
	m.subjectX500Principal = value
}

// SetVersion sets the version property value. The version property
func (m *CertificateRecord) SetVersion(value *int32) {
	m.version = value
}

type CertificateRecordable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetIssuerX500Principal() *string
	GetKeyUsage() []string
	GetKeyUsageExtended() []string
	GetNotAfter() *int32
	GetNotBefore() *int32
	GetSerialNumber() *string
	GetSha1Fingerprint() *string
	GetSha256Fingerprint() *string
	GetSignature() Signatureable
	GetSubjectX500Principal() *string
	GetVersion() *int32
	SetIssuerX500Principal(value *string)
	SetKeyUsage(value []string)
	SetKeyUsageExtended(value []string)
	SetNotAfter(value *int32)
	SetNotBefore(value *int32)
	SetSerialNumber(value *string)
	SetSha1Fingerprint(value *string)
	SetSha256Fingerprint(value *string)
	SetSignature(value Signatureable)
	SetSubjectX500Principal(value *string)
	SetVersion(value *int32)
}
