// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// CloudIdPCommonResponse a Cloud Identity Provider information for responses
type CloudIdPCommonResponse struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The displayName property
	displayName *string
	// The enabled property
	enabled *bool
	// The id property
	id *string
	// The providerDescription property
	providerDescription *string
	// The providerName property
	providerName *CloudIdPCommonResponse_providerName
}

// NewCloudIdPCommonResponse instantiates a new CloudIdPCommonResponse and sets the default values.
func NewCloudIdPCommonResponse() *CloudIdPCommonResponse {
	m := &CloudIdPCommonResponse{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateCloudIdPCommonResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCloudIdPCommonResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewCloudIdPCommonResponse(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CloudIdPCommonResponse) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetDisplayName gets the displayName property value. The displayName property
// returns a *string when successful
func (m *CloudIdPCommonResponse) GetDisplayName() *string {
	return m.displayName
}

// GetEnabled gets the enabled property value. The enabled property
// returns a *bool when successful
func (m *CloudIdPCommonResponse) GetEnabled() *bool {
	return m.enabled
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CloudIdPCommonResponse) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["displayName"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDisplayName(val)
		}
		return nil
	}
	res["enabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetEnabled(val)
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["providerDescription"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProviderDescription(val)
		}
		return nil
	}
	res["providerName"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseCloudIdPCommonResponse_providerName)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProviderName(val.(*CloudIdPCommonResponse_providerName))
		}
		return nil
	}
	return res
}

// GetId gets the id property value. The id property
// returns a *string when successful
func (m *CloudIdPCommonResponse) GetId() *string {
	return m.id
}

// GetProviderDescription gets the providerDescription property value. The providerDescription property
// returns a *string when successful
func (m *CloudIdPCommonResponse) GetProviderDescription() *string {
	return m.providerDescription
}

// GetProviderName gets the providerName property value. The providerName property
// returns a *CloudIdPCommonResponse_providerName when successful
func (m *CloudIdPCommonResponse) GetProviderName() *CloudIdPCommonResponse_providerName {
	return m.providerName
}

// Serialize serializes information the current object
func (m *CloudIdPCommonResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("displayName", m.GetDisplayName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("enabled", m.GetEnabled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("id", m.GetId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("providerDescription", m.GetProviderDescription())
		if err != nil {
			return err
		}
	}
	if m.GetProviderName() != nil {
		cast := (*m.GetProviderName()).String()
		err := writer.WriteStringValue("providerName", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CloudIdPCommonResponse) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetDisplayName sets the displayName property value. The displayName property
func (m *CloudIdPCommonResponse) SetDisplayName(value *string) {
	m.displayName = value
}

// SetEnabled sets the enabled property value. The enabled property
func (m *CloudIdPCommonResponse) SetEnabled(value *bool) {
	m.enabled = value
}

// SetId sets the id property value. The id property
func (m *CloudIdPCommonResponse) SetId(value *string) {
	m.id = value
}

// SetProviderDescription sets the providerDescription property value. The providerDescription property
func (m *CloudIdPCommonResponse) SetProviderDescription(value *string) {
	m.providerDescription = value
}

// SetProviderName sets the providerName property value. The providerName property
func (m *CloudIdPCommonResponse) SetProviderName(value *CloudIdPCommonResponse_providerName) {
	m.providerName = value
}

type CloudIdPCommonResponseable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetDisplayName() *string
	GetEnabled() *bool
	GetId() *string
	GetProviderDescription() *string
	GetProviderName() *CloudIdPCommonResponse_providerName
	SetDisplayName(value *string)
	SetEnabled(value *bool)
	SetId(value *string)
	SetProviderDescription(value *string)
	SetProviderName(value *CloudIdPCommonResponse_providerName)
}
