// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ComputerContentCachingParentDetails struct {
	// The acPower property
	acPower *bool
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The cacheSizeBytes property
	cacheSizeBytes *int64
	// The capabilities property
	capabilities ComputerContentCachingParentCapabilitiesable
	// The contentCachingParentDetailsId property
	contentCachingParentDetailsId *string
	// The localNetwork property
	localNetwork []ComputerContentCachingParentLocalNetworkable
	// The portable property
	portable *bool
}

// NewComputerContentCachingParentDetails instantiates a new ComputerContentCachingParentDetails and sets the default values.
func NewComputerContentCachingParentDetails() *ComputerContentCachingParentDetails {
	m := &ComputerContentCachingParentDetails{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateComputerContentCachingParentDetailsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateComputerContentCachingParentDetailsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewComputerContentCachingParentDetails(), nil
}

// GetAcPower gets the acPower property value. The acPower property
// returns a *bool when successful
func (m *ComputerContentCachingParentDetails) GetAcPower() *bool {
	return m.acPower
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ComputerContentCachingParentDetails) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetCacheSizeBytes gets the cacheSizeBytes property value. The cacheSizeBytes property
// returns a *int64 when successful
func (m *ComputerContentCachingParentDetails) GetCacheSizeBytes() *int64 {
	return m.cacheSizeBytes
}

// GetCapabilities gets the capabilities property value. The capabilities property
// returns a ComputerContentCachingParentCapabilitiesable when successful
func (m *ComputerContentCachingParentDetails) GetCapabilities() ComputerContentCachingParentCapabilitiesable {
	return m.capabilities
}

// GetContentCachingParentDetailsId gets the contentCachingParentDetailsId property value. The contentCachingParentDetailsId property
// returns a *string when successful
func (m *ComputerContentCachingParentDetails) GetContentCachingParentDetailsId() *string {
	return m.contentCachingParentDetailsId
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ComputerContentCachingParentDetails) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["acPower"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAcPower(val)
		}
		return nil
	}
	res["cacheSizeBytes"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt64Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCacheSizeBytes(val)
		}
		return nil
	}
	res["capabilities"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateComputerContentCachingParentCapabilitiesFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCapabilities(val.(ComputerContentCachingParentCapabilitiesable))
		}
		return nil
	}
	res["contentCachingParentDetailsId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetContentCachingParentDetailsId(val)
		}
		return nil
	}
	res["localNetwork"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateComputerContentCachingParentLocalNetworkFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]ComputerContentCachingParentLocalNetworkable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(ComputerContentCachingParentLocalNetworkable)
				}
			}
			m.SetLocalNetwork(res)
		}
		return nil
	}
	res["portable"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPortable(val)
		}
		return nil
	}
	return res
}

// GetLocalNetwork gets the localNetwork property value. The localNetwork property
// returns a []ComputerContentCachingParentLocalNetworkable when successful
func (m *ComputerContentCachingParentDetails) GetLocalNetwork() []ComputerContentCachingParentLocalNetworkable {
	return m.localNetwork
}

// GetPortable gets the portable property value. The portable property
// returns a *bool when successful
func (m *ComputerContentCachingParentDetails) GetPortable() *bool {
	return m.portable
}

// Serialize serializes information the current object
func (m *ComputerContentCachingParentDetails) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteObjectValue("capabilities", m.GetCapabilities())
		if err != nil {
			return err
		}
	}
	if m.GetLocalNetwork() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetLocalNetwork()))
		for i, v := range m.GetLocalNetwork() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("localNetwork", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAcPower sets the acPower property value. The acPower property
func (m *ComputerContentCachingParentDetails) SetAcPower(value *bool) {
	m.acPower = value
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ComputerContentCachingParentDetails) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetCacheSizeBytes sets the cacheSizeBytes property value. The cacheSizeBytes property
func (m *ComputerContentCachingParentDetails) SetCacheSizeBytes(value *int64) {
	m.cacheSizeBytes = value
}

// SetCapabilities sets the capabilities property value. The capabilities property
func (m *ComputerContentCachingParentDetails) SetCapabilities(value ComputerContentCachingParentCapabilitiesable) {
	m.capabilities = value
}

// SetContentCachingParentDetailsId sets the contentCachingParentDetailsId property value. The contentCachingParentDetailsId property
func (m *ComputerContentCachingParentDetails) SetContentCachingParentDetailsId(value *string) {
	m.contentCachingParentDetailsId = value
}

// SetLocalNetwork sets the localNetwork property value. The localNetwork property
func (m *ComputerContentCachingParentDetails) SetLocalNetwork(value []ComputerContentCachingParentLocalNetworkable) {
	m.localNetwork = value
}

// SetPortable sets the portable property value. The portable property
func (m *ComputerContentCachingParentDetails) SetPortable(value *bool) {
	m.portable = value
}

type ComputerContentCachingParentDetailsable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAcPower() *bool
	GetCacheSizeBytes() *int64
	GetCapabilities() ComputerContentCachingParentCapabilitiesable
	GetContentCachingParentDetailsId() *string
	GetLocalNetwork() []ComputerContentCachingParentLocalNetworkable
	GetPortable() *bool
	SetAcPower(value *bool)
	SetCacheSizeBytes(value *int64)
	SetCapabilities(value ComputerContentCachingParentCapabilitiesable)
	SetContentCachingParentDetailsId(value *string)
	SetLocalNetwork(value []ComputerContentCachingParentLocalNetworkable)
	SetPortable(value *bool)
}
