// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

type ComputerGeneralCreateV4_platform int

const (
	WINDOWS_COMPUTERGENERALCREATEV4_PLATFORM ComputerGeneralCreateV4_platform = iota
	MAC_COMPUTERGENERALCREATEV4_PLATFORM
	NONE_COMPUTERGENERALCREATEV4_PLATFORM
)

func (i ComputerGeneralCreateV4_platform) String() string {
	return []string{"WINDOWS", "MAC", "NONE"}[i]
}

func ParseComputerGeneralCreateV4_platform(v string) (any, error) {
	result := WINDOWS_COMPUTERGENERALCREATEV4_PLATFORM
	switch v {
	case "WINDOWS":
		result = WINDOWS_COMPUTERGENERALCREATEV4_PLATFORM
	case "MAC":
		result = MAC_COMPUTERGENERALCREATEV4_PLATFORM
	case "NONE":
		result = NONE_COMPUTERGENERALCREATEV4_PLATFORM
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeComputerGeneralCreateV4_platform(values []ComputerGeneralCreateV4_platform) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i ComputerGeneralCreateV4_platform) isMultiValue() bool {
	return false
}
