// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

type ComputerSecurity_sipStatus int

const (
	NOT_COLLECTED_COMPUTERSECURITY_SIPSTATUS ComputerSecurity_sipStatus = iota
	NOT_AVAILABLE_COMPUTERSECURITY_SIPSTATUS
	DISABLED_COMPUTERSECURITY_SIPSTATUS
	ENABLED_COMPUTERSECURITY_SIPSTATUS
)

func (i ComputerSecurity_sipStatus) String() string {
	return []string{"NOT_COLLECTED", "NOT_AVAILABLE", "DISABLED", "ENABLED"}[i]
}

func ParseComputerSecurity_sipStatus(v string) (any, error) {
	result := NOT_COLLECTED_COMPUTERSECURITY_SIPSTATUS
	switch v {
	case "NOT_COLLECTED":
		result = NOT_COLLECTED_COMPUTERSECURITY_SIPSTATUS
	case "NOT_AVAILABLE":
		result = NOT_AVAILABLE_COMPUTERSECURITY_SIPSTATUS
	case "DISABLED":
		result = DISABLED_COMPUTERSECURITY_SIPSTATUS
	case "ENABLED":
		result = ENABLED_COMPUTERSECURITY_SIPSTATUS
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeComputerSecurity_sipStatus(values []ComputerSecurity_sipStatus) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i ComputerSecurity_sipStatus) isMultiValue() bool {
	return false
}
