// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"

	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ComputerConfigurationProfileCreate struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The displayName property
	displayName *string
	// The id property
	id *string
	// The lastInstalled property
	lastInstalled *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	// The profileIdentifier property
	profileIdentifier *string
	// The removable property
	removable *bool
	// The username property
	username *string
}

// NewComputerConfigurationProfileCreate instantiates a new ComputerConfigurationProfileCreate and sets the default values.
func NewComputerConfigurationProfileCreate() *ComputerConfigurationProfileCreate {
	m := &ComputerConfigurationProfileCreate{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateComputerConfigurationProfileCreateFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateComputerConfigurationProfileCreateFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewComputerConfigurationProfileCreate(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ComputerConfigurationProfileCreate) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetDisplayName gets the displayName property value. The displayName property
// returns a *string when successful
func (m *ComputerConfigurationProfileCreate) GetDisplayName() *string {
	return m.displayName
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ComputerConfigurationProfileCreate) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["displayName"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDisplayName(val)
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["lastInstalled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetTimeValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLastInstalled(val)
		}
		return nil
	}
	res["profileIdentifier"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetProfileIdentifier(val)
		}
		return nil
	}
	res["removable"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRemovable(val)
		}
		return nil
	}
	res["username"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUsername(val)
		}
		return nil
	}
	return res
}

// GetId gets the id property value. The id property
// returns a *string when successful
func (m *ComputerConfigurationProfileCreate) GetId() *string {
	return m.id
}

// GetLastInstalled gets the lastInstalled property value. The lastInstalled property
// returns a *Time when successful
func (m *ComputerConfigurationProfileCreate) GetLastInstalled() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time {
	return m.lastInstalled
}

// GetProfileIdentifier gets the profileIdentifier property value. The profileIdentifier property
// returns a *string when successful
func (m *ComputerConfigurationProfileCreate) GetProfileIdentifier() *string {
	return m.profileIdentifier
}

// GetRemovable gets the removable property value. The removable property
// returns a *bool when successful
func (m *ComputerConfigurationProfileCreate) GetRemovable() *bool {
	return m.removable
}

// GetUsername gets the username property value. The username property
// returns a *string when successful
func (m *ComputerConfigurationProfileCreate) GetUsername() *string {
	return m.username
}

// Serialize serializes information the current object
func (m *ComputerConfigurationProfileCreate) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("displayName", m.GetDisplayName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("id", m.GetId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteTimeValue("lastInstalled", m.GetLastInstalled())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("profileIdentifier", m.GetProfileIdentifier())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("removable", m.GetRemovable())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("username", m.GetUsername())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ComputerConfigurationProfileCreate) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetDisplayName sets the displayName property value. The displayName property
func (m *ComputerConfigurationProfileCreate) SetDisplayName(value *string) {
	m.displayName = value
}

// SetId sets the id property value. The id property
func (m *ComputerConfigurationProfileCreate) SetId(value *string) {
	m.id = value
}

// SetLastInstalled sets the lastInstalled property value. The lastInstalled property
func (m *ComputerConfigurationProfileCreate) SetLastInstalled(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
	m.lastInstalled = value
}

// SetProfileIdentifier sets the profileIdentifier property value. The profileIdentifier property
func (m *ComputerConfigurationProfileCreate) SetProfileIdentifier(value *string) {
	m.profileIdentifier = value
}

// SetRemovable sets the removable property value. The removable property
func (m *ComputerConfigurationProfileCreate) SetRemovable(value *bool) {
	m.removable = value
}

// SetUsername sets the username property value. The username property
func (m *ComputerConfigurationProfileCreate) SetUsername(value *string) {
	m.username = value
}

type ComputerConfigurationProfileCreateable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetDisplayName() *string
	GetId() *string
	GetLastInstalled() *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
	GetProfileIdentifier() *string
	GetRemovable() *bool
	GetUsername() *string
	SetDisplayName(value *string)
	SetId(value *string)
	SetLastInstalled(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
	SetProfileIdentifier(value *string)
	SetRemovable(value *bool)
	SetUsername(value *string)
}
