// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type DeviceLockCommand struct {
	MdmCommandBase
	// The message property
	message *string
	// The phoneNumber property
	phoneNumber *string
	// The pin property
	pin *string
}

// NewDeviceLockCommand instantiates a new DeviceLockCommand and sets the default values.
func NewDeviceLockCommand() *DeviceLockCommand {
	m := &DeviceLockCommand{
		MdmCommandBase: *NewMdmCommandBase(),
	}
	return m
}

// CreateDeviceLockCommandFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateDeviceLockCommandFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewDeviceLockCommand(), nil
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *DeviceLockCommand) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.MdmCommandBase.GetFieldDeserializers()
	res["message"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetMessage(val)
		}
		return nil
	}
	res["phoneNumber"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPhoneNumber(val)
		}
		return nil
	}
	res["pin"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetPin(val)
		}
		return nil
	}
	return res
}

// GetMessage gets the message property value. The message property
// returns a *string when successful
func (m *DeviceLockCommand) GetMessage() *string {
	return m.message
}

// GetPhoneNumber gets the phoneNumber property value. The phoneNumber property
// returns a *string when successful
func (m *DeviceLockCommand) GetPhoneNumber() *string {
	return m.phoneNumber
}

// GetPin gets the pin property value. The pin property
// returns a *string when successful
func (m *DeviceLockCommand) GetPin() *string {
	return m.pin
}

// Serialize serializes information the current object
func (m *DeviceLockCommand) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.MdmCommandBase.Serialize(writer)
	if err != nil {
		return err
	}
	{
		err = writer.WriteStringValue("message", m.GetMessage())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteStringValue("phoneNumber", m.GetPhoneNumber())
		if err != nil {
			return err
		}
	}
	{
		err = writer.WriteStringValue("pin", m.GetPin())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetMessage sets the message property value. The message property
func (m *DeviceLockCommand) SetMessage(value *string) {
	m.message = value
}

// SetPhoneNumber sets the phoneNumber property value. The phoneNumber property
func (m *DeviceLockCommand) SetPhoneNumber(value *string) {
	m.phoneNumber = value
}

// SetPin sets the pin property value. The pin property
func (m *DeviceLockCommand) SetPin(value *string) {
	m.pin = value
}

type DeviceLockCommandable interface {
	MdmCommandBaseable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetMessage() *string
	GetPhoneNumber() *string
	GetPin() *string
	SetMessage(value *string)
	SetPhoneNumber(value *string)
	SetPin(value *string)
}
