// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type EbookScope struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The allComputers property
	allComputers *bool
	// The allMobileDevices property
	allMobileDevices *bool
	// The allUsers property
	allUsers *bool
	// The buildingIds property
	buildingIds []string
	// The classroomIds property
	classroomIds []string
	// The computerGroupIds property
	computerGroupIds []string
	// The computerIds property
	computerIds []string
	// The departmentIds property
	departmentIds []string
	// The exclusions property
	exclusions EbookExclusionsable
	// The limitations property
	limitations EbookLimitationsable
	// The mobileDeviceGroupIds property
	mobileDeviceGroupIds []string
	// The mobileDeviceIds property
	mobileDeviceIds []string
	// The userGroupIds property
	userGroupIds []string
	// The userIds property
	userIds []string
}

// NewEbookScope instantiates a new EbookScope and sets the default values.
func NewEbookScope() *EbookScope {
	m := &EbookScope{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateEbookScopeFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEbookScopeFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewEbookScope(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *EbookScope) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAllComputers gets the allComputers property value. The allComputers property
// returns a *bool when successful
func (m *EbookScope) GetAllComputers() *bool {
	return m.allComputers
}

// GetAllMobileDevices gets the allMobileDevices property value. The allMobileDevices property
// returns a *bool when successful
func (m *EbookScope) GetAllMobileDevices() *bool {
	return m.allMobileDevices
}

// GetAllUsers gets the allUsers property value. The allUsers property
// returns a *bool when successful
func (m *EbookScope) GetAllUsers() *bool {
	return m.allUsers
}

// GetBuildingIds gets the buildingIds property value. The buildingIds property
// returns a []string when successful
func (m *EbookScope) GetBuildingIds() []string {
	return m.buildingIds
}

// GetClassroomIds gets the classroomIds property value. The classroomIds property
// returns a []string when successful
func (m *EbookScope) GetClassroomIds() []string {
	return m.classroomIds
}

// GetComputerGroupIds gets the computerGroupIds property value. The computerGroupIds property
// returns a []string when successful
func (m *EbookScope) GetComputerGroupIds() []string {
	return m.computerGroupIds
}

// GetComputerIds gets the computerIds property value. The computerIds property
// returns a []string when successful
func (m *EbookScope) GetComputerIds() []string {
	return m.computerIds
}

// GetDepartmentIds gets the departmentIds property value. The departmentIds property
// returns a []string when successful
func (m *EbookScope) GetDepartmentIds() []string {
	return m.departmentIds
}

// GetExclusions gets the exclusions property value. The exclusions property
// returns a EbookExclusionsable when successful
func (m *EbookScope) GetExclusions() EbookExclusionsable {
	return m.exclusions
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *EbookScope) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["allComputers"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAllComputers(val)
		}
		return nil
	}
	res["allMobileDevices"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAllMobileDevices(val)
		}
		return nil
	}
	res["allUsers"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAllUsers(val)
		}
		return nil
	}
	res["buildingIds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetBuildingIds(res)
		}
		return nil
	}
	res["classroomIds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetClassroomIds(res)
		}
		return nil
	}
	res["computerGroupIds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetComputerGroupIds(res)
		}
		return nil
	}
	res["computerIds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetComputerIds(res)
		}
		return nil
	}
	res["departmentIds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetDepartmentIds(res)
		}
		return nil
	}
	res["exclusions"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateEbookExclusionsFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetExclusions(val.(EbookExclusionsable))
		}
		return nil
	}
	res["limitations"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetObjectValue(CreateEbookLimitationsFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetLimitations(val.(EbookLimitationsable))
		}
		return nil
	}
	res["mobileDeviceGroupIds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetMobileDeviceGroupIds(res)
		}
		return nil
	}
	res["mobileDeviceIds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetMobileDeviceIds(res)
		}
		return nil
	}
	res["userGroupIds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetUserGroupIds(res)
		}
		return nil
	}
	res["userIds"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetUserIds(res)
		}
		return nil
	}
	return res
}

// GetLimitations gets the limitations property value. The limitations property
// returns a EbookLimitationsable when successful
func (m *EbookScope) GetLimitations() EbookLimitationsable {
	return m.limitations
}

// GetMobileDeviceGroupIds gets the mobileDeviceGroupIds property value. The mobileDeviceGroupIds property
// returns a []string when successful
func (m *EbookScope) GetMobileDeviceGroupIds() []string {
	return m.mobileDeviceGroupIds
}

// GetMobileDeviceIds gets the mobileDeviceIds property value. The mobileDeviceIds property
// returns a []string when successful
func (m *EbookScope) GetMobileDeviceIds() []string {
	return m.mobileDeviceIds
}

// GetUserGroupIds gets the userGroupIds property value. The userGroupIds property
// returns a []string when successful
func (m *EbookScope) GetUserGroupIds() []string {
	return m.userGroupIds
}

// GetUserIds gets the userIds property value. The userIds property
// returns a []string when successful
func (m *EbookScope) GetUserIds() []string {
	return m.userIds
}

// Serialize serializes information the current object
func (m *EbookScope) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteBoolValue("allComputers", m.GetAllComputers())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("allMobileDevices", m.GetAllMobileDevices())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("allUsers", m.GetAllUsers())
		if err != nil {
			return err
		}
	}
	if m.GetBuildingIds() != nil {
		err := writer.WriteCollectionOfStringValues("buildingIds", m.GetBuildingIds())
		if err != nil {
			return err
		}
	}
	if m.GetClassroomIds() != nil {
		err := writer.WriteCollectionOfStringValues("classroomIds", m.GetClassroomIds())
		if err != nil {
			return err
		}
	}
	if m.GetComputerGroupIds() != nil {
		err := writer.WriteCollectionOfStringValues("computerGroupIds", m.GetComputerGroupIds())
		if err != nil {
			return err
		}
	}
	if m.GetComputerIds() != nil {
		err := writer.WriteCollectionOfStringValues("computerIds", m.GetComputerIds())
		if err != nil {
			return err
		}
	}
	if m.GetDepartmentIds() != nil {
		err := writer.WriteCollectionOfStringValues("departmentIds", m.GetDepartmentIds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("exclusions", m.GetExclusions())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteObjectValue("limitations", m.GetLimitations())
		if err != nil {
			return err
		}
	}
	if m.GetMobileDeviceGroupIds() != nil {
		err := writer.WriteCollectionOfStringValues("mobileDeviceGroupIds", m.GetMobileDeviceGroupIds())
		if err != nil {
			return err
		}
	}
	if m.GetMobileDeviceIds() != nil {
		err := writer.WriteCollectionOfStringValues("mobileDeviceIds", m.GetMobileDeviceIds())
		if err != nil {
			return err
		}
	}
	if m.GetUserGroupIds() != nil {
		err := writer.WriteCollectionOfStringValues("userGroupIds", m.GetUserGroupIds())
		if err != nil {
			return err
		}
	}
	if m.GetUserIds() != nil {
		err := writer.WriteCollectionOfStringValues("userIds", m.GetUserIds())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *EbookScope) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAllComputers sets the allComputers property value. The allComputers property
func (m *EbookScope) SetAllComputers(value *bool) {
	m.allComputers = value
}

// SetAllMobileDevices sets the allMobileDevices property value. The allMobileDevices property
func (m *EbookScope) SetAllMobileDevices(value *bool) {
	m.allMobileDevices = value
}

// SetAllUsers sets the allUsers property value. The allUsers property
func (m *EbookScope) SetAllUsers(value *bool) {
	m.allUsers = value
}

// SetBuildingIds sets the buildingIds property value. The buildingIds property
func (m *EbookScope) SetBuildingIds(value []string) {
	m.buildingIds = value
}

// SetClassroomIds sets the classroomIds property value. The classroomIds property
func (m *EbookScope) SetClassroomIds(value []string) {
	m.classroomIds = value
}

// SetComputerGroupIds sets the computerGroupIds property value. The computerGroupIds property
func (m *EbookScope) SetComputerGroupIds(value []string) {
	m.computerGroupIds = value
}

// SetComputerIds sets the computerIds property value. The computerIds property
func (m *EbookScope) SetComputerIds(value []string) {
	m.computerIds = value
}

// SetDepartmentIds sets the departmentIds property value. The departmentIds property
func (m *EbookScope) SetDepartmentIds(value []string) {
	m.departmentIds = value
}

// SetExclusions sets the exclusions property value. The exclusions property
func (m *EbookScope) SetExclusions(value EbookExclusionsable) {
	m.exclusions = value
}

// SetLimitations sets the limitations property value. The limitations property
func (m *EbookScope) SetLimitations(value EbookLimitationsable) {
	m.limitations = value
}

// SetMobileDeviceGroupIds sets the mobileDeviceGroupIds property value. The mobileDeviceGroupIds property
func (m *EbookScope) SetMobileDeviceGroupIds(value []string) {
	m.mobileDeviceGroupIds = value
}

// SetMobileDeviceIds sets the mobileDeviceIds property value. The mobileDeviceIds property
func (m *EbookScope) SetMobileDeviceIds(value []string) {
	m.mobileDeviceIds = value
}

// SetUserGroupIds sets the userGroupIds property value. The userGroupIds property
func (m *EbookScope) SetUserGroupIds(value []string) {
	m.userGroupIds = value
}

// SetUserIds sets the userIds property value. The userIds property
func (m *EbookScope) SetUserIds(value []string) {
	m.userIds = value
}

type EbookScopeable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAllComputers() *bool
	GetAllMobileDevices() *bool
	GetAllUsers() *bool
	GetBuildingIds() []string
	GetClassroomIds() []string
	GetComputerGroupIds() []string
	GetComputerIds() []string
	GetDepartmentIds() []string
	GetExclusions() EbookExclusionsable
	GetLimitations() EbookLimitationsable
	GetMobileDeviceGroupIds() []string
	GetMobileDeviceIds() []string
	GetUserGroupIds() []string
	GetUserIds() []string
	SetAllComputers(value *bool)
	SetAllMobileDevices(value *bool)
	SetAllUsers(value *bool)
	SetBuildingIds(value []string)
	SetClassroomIds(value []string)
	SetComputerGroupIds(value []string)
	SetComputerIds(value []string)
	SetDepartmentIds(value []string)
	SetExclusions(value EbookExclusionsable)
	SetLimitations(value EbookLimitationsable)
	SetMobileDeviceGroupIds(value []string)
	SetMobileDeviceIds(value []string)
	SetUserGroupIds(value []string)
	SetUserIds(value []string)
}
