// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

type GroupDtoV1_groupType int

const (
	MOBILE_GROUPDTOV1_GROUPTYPE GroupDtoV1_groupType = iota
	COMPUTER_GROUPDTOV1_GROUPTYPE
)

func (i GroupDtoV1_groupType) String() string {
	return []string{"MOBILE", "COMPUTER"}[i]
}

func ParseGroupDtoV1_groupType(v string) (any, error) {
	result := MOBILE_GROUPDTOV1_GROUPTYPE
	switch v {
	case "MOBILE":
		result = MOBILE_GROUPDTOV1_GROUPTYPE
	case "COMPUTER":
		result = COMPUTER_GROUPDTOV1_GROUPTYPE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeGroupDtoV1_groupType(values []GroupDtoV1_groupType) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i GroupDtoV1_groupType) isMultiValue() bool {
	return false
}
