// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

type InventoryPreloadRecord_deviceType int

const (
	COMPUTER_INVENTORYPRELOADRECORD_DEVICETYPE InventoryPreloadRecord_deviceType = iota
	MOBILEDEVICE_INVENTORYPRELOADRECORD_DEVICETYPE
	UNKNOWN_INVENTORYPRELOADRECORD_DEVICETYPE
)

func (i InventoryPreloadRecord_deviceType) String() string {
	return []string{"Computer", "Mobile Device", "Unknown"}[i]
}

func ParseInventoryPreloadRecord_deviceType(v string) (any, error) {
	result := COMPUTER_INVENTORYPRELOADRECORD_DEVICETYPE
	switch v {
	case "Computer":
		result = COMPUTER_INVENTORYPRELOADRECORD_DEVICETYPE
	case "Mobile Device":
		result = MOBILEDEVICE_INVENTORYPRELOADRECORD_DEVICETYPE
	case "Unknown":
		result = UNKNOWN_INVENTORYPRELOADRECORD_DEVICETYPE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeInventoryPreloadRecord_deviceType(values []InventoryPreloadRecord_deviceType) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i InventoryPreloadRecord_deviceType) isMultiValue() bool {
	return false
}
