// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type LapsUserPasswordResponseV2 struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The lapsUserPasswordList property
	lapsUserPasswordList []LapsUserPasswordV2able
}

// NewLapsUserPasswordResponseV2 instantiates a new LapsUserPasswordResponseV2 and sets the default values.
func NewLapsUserPasswordResponseV2() *LapsUserPasswordResponseV2 {
	m := &LapsUserPasswordResponseV2{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateLapsUserPasswordResponseV2FromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLapsUserPasswordResponseV2FromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewLapsUserPasswordResponseV2(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *LapsUserPasswordResponseV2) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *LapsUserPasswordResponseV2) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["lapsUserPasswordList"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateLapsUserPasswordV2FromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]LapsUserPasswordV2able, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(LapsUserPasswordV2able)
				}
			}
			m.SetLapsUserPasswordList(res)
		}
		return nil
	}
	return res
}

// GetLapsUserPasswordList gets the lapsUserPasswordList property value. The lapsUserPasswordList property
// returns a []LapsUserPasswordV2able when successful
func (m *LapsUserPasswordResponseV2) GetLapsUserPasswordList() []LapsUserPasswordV2able {
	return m.lapsUserPasswordList
}

// Serialize serializes information the current object
func (m *LapsUserPasswordResponseV2) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetLapsUserPasswordList() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetLapsUserPasswordList()))
		for i, v := range m.GetLapsUserPasswordList() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("lapsUserPasswordList", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *LapsUserPasswordResponseV2) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetLapsUserPasswordList sets the lapsUserPasswordList property value. The lapsUserPasswordList property
func (m *LapsUserPasswordResponseV2) SetLapsUserPasswordList(value []LapsUserPasswordV2able) {
	m.lapsUserPasswordList = value
}

type LapsUserPasswordResponseV2able interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetLapsUserPasswordList() []LapsUserPasswordV2able
	SetLapsUserPasswordList(value []LapsUserPasswordV2able)
}
