// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type LapsHistoryResponse struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The results property
	results []LapsHistoryable
	// The totalCount property
	totalCount *int32
}

// NewLapsHistoryResponse instantiates a new LapsHistoryResponse and sets the default values.
func NewLapsHistoryResponse() *LapsHistoryResponse {
	m := &LapsHistoryResponse{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateLapsHistoryResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLapsHistoryResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewLapsHistoryResponse(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *LapsHistoryResponse) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *LapsHistoryResponse) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["results"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreateLapsHistoryFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]LapsHistoryable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(LapsHistoryable)
				}
			}
			m.SetResults(res)
		}
		return nil
	}
	res["totalCount"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTotalCount(val)
		}
		return nil
	}
	return res
}

// GetResults gets the results property value. The results property
// returns a []LapsHistoryable when successful
func (m *LapsHistoryResponse) GetResults() []LapsHistoryable {
	return m.results
}

// GetTotalCount gets the totalCount property value. The totalCount property
// returns a *int32 when successful
func (m *LapsHistoryResponse) GetTotalCount() *int32 {
	return m.totalCount
}

// Serialize serializes information the current object
func (m *LapsHistoryResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetResults() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetResults()))
		for i, v := range m.GetResults() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err := writer.WriteCollectionOfObjectValues("results", cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("totalCount", m.GetTotalCount())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *LapsHistoryResponse) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetResults sets the results property value. The results property
func (m *LapsHistoryResponse) SetResults(value []LapsHistoryable) {
	m.results = value
}

// SetTotalCount sets the totalCount property value. The totalCount property
func (m *LapsHistoryResponse) SetTotalCount(value *int32) {
	m.totalCount = value
}

type LapsHistoryResponseable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetResults() []LapsHistoryable
	GetTotalCount() *int32
	SetResults(value []LapsHistoryable)
	SetTotalCount(value *int32)
}
