// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type LoginContentPut struct {
	// The actionText property
	actionText *string
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The disclaimerHeading property
	disclaimerHeading *string
	// The disclaimerMainText property
	disclaimerMainText *string
	// The includeCustomDisclaimer property
	includeCustomDisclaimer *bool
}

// NewLoginContentPut instantiates a new LoginContentPut and sets the default values.
func NewLoginContentPut() *LoginContentPut {
	m := &LoginContentPut{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateLoginContentPutFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLoginContentPutFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewLoginContentPut(), nil
}

// GetActionText gets the actionText property value. The actionText property
// returns a *string when successful
func (m *LoginContentPut) GetActionText() *string {
	return m.actionText
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *LoginContentPut) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetDisclaimerHeading gets the disclaimerHeading property value. The disclaimerHeading property
// returns a *string when successful
func (m *LoginContentPut) GetDisclaimerHeading() *string {
	return m.disclaimerHeading
}

// GetDisclaimerMainText gets the disclaimerMainText property value. The disclaimerMainText property
// returns a *string when successful
func (m *LoginContentPut) GetDisclaimerMainText() *string {
	return m.disclaimerMainText
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *LoginContentPut) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["actionText"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetActionText(val)
		}
		return nil
	}
	res["disclaimerHeading"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDisclaimerHeading(val)
		}
		return nil
	}
	res["disclaimerMainText"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDisclaimerMainText(val)
		}
		return nil
	}
	res["includeCustomDisclaimer"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetIncludeCustomDisclaimer(val)
		}
		return nil
	}
	return res
}

// GetIncludeCustomDisclaimer gets the includeCustomDisclaimer property value. The includeCustomDisclaimer property
// returns a *bool when successful
func (m *LoginContentPut) GetIncludeCustomDisclaimer() *bool {
	return m.includeCustomDisclaimer
}

// Serialize serializes information the current object
func (m *LoginContentPut) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("actionText", m.GetActionText())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("disclaimerHeading", m.GetDisclaimerHeading())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("disclaimerMainText", m.GetDisclaimerMainText())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteBoolValue("includeCustomDisclaimer", m.GetIncludeCustomDisclaimer())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetActionText sets the actionText property value. The actionText property
func (m *LoginContentPut) SetActionText(value *string) {
	m.actionText = value
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *LoginContentPut) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetDisclaimerHeading sets the disclaimerHeading property value. The disclaimerHeading property
func (m *LoginContentPut) SetDisclaimerHeading(value *string) {
	m.disclaimerHeading = value
}

// SetDisclaimerMainText sets the disclaimerMainText property value. The disclaimerMainText property
func (m *LoginContentPut) SetDisclaimerMainText(value *string) {
	m.disclaimerMainText = value
}

// SetIncludeCustomDisclaimer sets the includeCustomDisclaimer property value. The includeCustomDisclaimer property
func (m *LoginContentPut) SetIncludeCustomDisclaimer(value *bool) {
	m.includeCustomDisclaimer = value
}

type LoginContentPutable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetActionText() *string
	GetDisclaimerHeading() *string
	GetDisclaimerMainText() *string
	GetIncludeCustomDisclaimer() *bool
	SetActionText(value *string)
	SetDisclaimerHeading(value *string)
	SetDisclaimerMainText(value *string)
	SetIncludeCustomDisclaimer(value *bool)
}
