// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type MobileDeviceEbookInventoryDetail struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The author property
	author *string
	// The kind property
	kind *string
	// The managementState property
	managementState *string
	// The title property
	title *string
	// The version property
	version *string
}

// NewMobileDeviceEbookInventoryDetail instantiates a new MobileDeviceEbookInventoryDetail and sets the default values.
func NewMobileDeviceEbookInventoryDetail() *MobileDeviceEbookInventoryDetail {
	m := &MobileDeviceEbookInventoryDetail{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateMobileDeviceEbookInventoryDetailFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMobileDeviceEbookInventoryDetailFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewMobileDeviceEbookInventoryDetail(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *MobileDeviceEbookInventoryDetail) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAuthor gets the author property value. The author property
// returns a *string when successful
func (m *MobileDeviceEbookInventoryDetail) GetAuthor() *string {
	return m.author
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *MobileDeviceEbookInventoryDetail) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["author"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAuthor(val)
		}
		return nil
	}
	res["kind"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetKind(val)
		}
		return nil
	}
	res["managementState"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetManagementState(val)
		}
		return nil
	}
	res["title"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTitle(val)
		}
		return nil
	}
	res["version"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetVersion(val)
		}
		return nil
	}
	return res
}

// GetKind gets the kind property value. The kind property
// returns a *string when successful
func (m *MobileDeviceEbookInventoryDetail) GetKind() *string {
	return m.kind
}

// GetManagementState gets the managementState property value. The managementState property
// returns a *string when successful
func (m *MobileDeviceEbookInventoryDetail) GetManagementState() *string {
	return m.managementState
}

// GetTitle gets the title property value. The title property
// returns a *string when successful
func (m *MobileDeviceEbookInventoryDetail) GetTitle() *string {
	return m.title
}

// GetVersion gets the version property value. The version property
// returns a *string when successful
func (m *MobileDeviceEbookInventoryDetail) GetVersion() *string {
	return m.version
}

// Serialize serializes information the current object
func (m *MobileDeviceEbookInventoryDetail) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("author", m.GetAuthor())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("kind", m.GetKind())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("managementState", m.GetManagementState())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("title", m.GetTitle())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("version", m.GetVersion())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *MobileDeviceEbookInventoryDetail) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAuthor sets the author property value. The author property
func (m *MobileDeviceEbookInventoryDetail) SetAuthor(value *string) {
	m.author = value
}

// SetKind sets the kind property value. The kind property
func (m *MobileDeviceEbookInventoryDetail) SetKind(value *string) {
	m.kind = value
}

// SetManagementState sets the managementState property value. The managementState property
func (m *MobileDeviceEbookInventoryDetail) SetManagementState(value *string) {
	m.managementState = value
}

// SetTitle sets the title property value. The title property
func (m *MobileDeviceEbookInventoryDetail) SetTitle(value *string) {
	m.title = value
}

// SetVersion sets the version property value. The version property
func (m *MobileDeviceEbookInventoryDetail) SetVersion(value *string) {
	m.version = value
}

type MobileDeviceEbookInventoryDetailable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAuthor() *string
	GetKind() *string
	GetManagementState() *string
	GetTitle() *string
	GetVersion() *string
	SetAuthor(value *string)
	SetKind(value *string)
	SetManagementState(value *string)
	SetTitle(value *string)
	SetVersion(value *string)
}
