// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type MobileDeviceExtensionAttribute struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The extensionAttributeCollectionAllowed property
	extensionAttributeCollectionAllowed *bool
	// The id property
	id *string
	// The inventoryDisplay property
	inventoryDisplay *string
	// The name property
	name *string
	// The type property
	typeEscaped *MobileDeviceExtensionAttribute_type
	// The value property
	value []string
}

// NewMobileDeviceExtensionAttribute instantiates a new MobileDeviceExtensionAttribute and sets the default values.
func NewMobileDeviceExtensionAttribute() *MobileDeviceExtensionAttribute {
	m := &MobileDeviceExtensionAttribute{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateMobileDeviceExtensionAttributeFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateMobileDeviceExtensionAttributeFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewMobileDeviceExtensionAttribute(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *MobileDeviceExtensionAttribute) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetExtensionAttributeCollectionAllowed gets the extensionAttributeCollectionAllowed property value. The extensionAttributeCollectionAllowed property
// returns a *bool when successful
func (m *MobileDeviceExtensionAttribute) GetExtensionAttributeCollectionAllowed() *bool {
	return m.extensionAttributeCollectionAllowed
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *MobileDeviceExtensionAttribute) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["extensionAttributeCollectionAllowed"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetExtensionAttributeCollectionAllowed(val)
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["inventoryDisplay"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetInventoryDisplay(val)
		}
		return nil
	}
	res["name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetName(val)
		}
		return nil
	}
	res["type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseMobileDeviceExtensionAttribute_type)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTypeEscaped(val.(*MobileDeviceExtensionAttribute_type))
		}
		return nil
	}
	res["value"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetValue(res)
		}
		return nil
	}
	return res
}

// GetId gets the id property value. The id property
// returns a *string when successful
func (m *MobileDeviceExtensionAttribute) GetId() *string {
	return m.id
}

// GetInventoryDisplay gets the inventoryDisplay property value. The inventoryDisplay property
// returns a *string when successful
func (m *MobileDeviceExtensionAttribute) GetInventoryDisplay() *string {
	return m.inventoryDisplay
}

// GetName gets the name property value. The name property
// returns a *string when successful
func (m *MobileDeviceExtensionAttribute) GetName() *string {
	return m.name
}

// GetTypeEscaped gets the type property value. The type property
// returns a *MobileDeviceExtensionAttribute_type when successful
func (m *MobileDeviceExtensionAttribute) GetTypeEscaped() *MobileDeviceExtensionAttribute_type {
	return m.typeEscaped
}

// GetValue gets the value property value. The value property
// returns a []string when successful
func (m *MobileDeviceExtensionAttribute) GetValue() []string {
	return m.value
}

// Serialize serializes information the current object
func (m *MobileDeviceExtensionAttribute) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteBoolValue("extensionAttributeCollectionAllowed", m.GetExtensionAttributeCollectionAllowed())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("inventoryDisplay", m.GetInventoryDisplay())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("name", m.GetName())
		if err != nil {
			return err
		}
	}
	if m.GetTypeEscaped() != nil {
		cast := (*m.GetTypeEscaped()).String()
		err := writer.WriteStringValue("type", &cast)
		if err != nil {
			return err
		}
	}
	if m.GetValue() != nil {
		err := writer.WriteCollectionOfStringValues("value", m.GetValue())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *MobileDeviceExtensionAttribute) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetExtensionAttributeCollectionAllowed sets the extensionAttributeCollectionAllowed property value. The extensionAttributeCollectionAllowed property
func (m *MobileDeviceExtensionAttribute) SetExtensionAttributeCollectionAllowed(value *bool) {
	m.extensionAttributeCollectionAllowed = value
}

// SetId sets the id property value. The id property
func (m *MobileDeviceExtensionAttribute) SetId(value *string) {
	m.id = value
}

// SetInventoryDisplay sets the inventoryDisplay property value. The inventoryDisplay property
func (m *MobileDeviceExtensionAttribute) SetInventoryDisplay(value *string) {
	m.inventoryDisplay = value
}

// SetName sets the name property value. The name property
func (m *MobileDeviceExtensionAttribute) SetName(value *string) {
	m.name = value
}

// SetTypeEscaped sets the type property value. The type property
func (m *MobileDeviceExtensionAttribute) SetTypeEscaped(value *MobileDeviceExtensionAttribute_type) {
	m.typeEscaped = value
}

// SetValue sets the value property value. The value property
func (m *MobileDeviceExtensionAttribute) SetValue(value []string) {
	m.value = value
}

type MobileDeviceExtensionAttributeable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetExtensionAttributeCollectionAllowed() *bool
	GetId() *string
	GetInventoryDisplay() *string
	GetName() *string
	GetTypeEscaped() *MobileDeviceExtensionAttribute_type
	GetValue() []string
	SetExtensionAttributeCollectionAllowed(value *bool)
	SetId(value *string)
	SetInventoryDisplay(value *string)
	SetName(value *string)
	SetTypeEscaped(value *MobileDeviceExtensionAttribute_type)
	SetValue(value []string)
}
