// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type OidcSettings struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The jamfIdAuthenticationEnabled property
	jamfIdAuthenticationEnabled *bool
	// The userMapping property
	userMapping *OidcSettings_userMapping
	// The usernameAttributeClaimMapping property
	usernameAttributeClaimMapping *OidcSettings_usernameAttributeClaimMapping
}

// NewOidcSettings instantiates a new OidcSettings and sets the default values.
func NewOidcSettings() *OidcSettings {
	m := &OidcSettings{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateOidcSettingsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOidcSettingsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewOidcSettings(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *OidcSettings) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *OidcSettings) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["jamfIdAuthenticationEnabled"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetBoolValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetJamfIdAuthenticationEnabled(val)
		}
		return nil
	}
	res["userMapping"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseOidcSettings_userMapping)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUserMapping(val.(*OidcSettings_userMapping))
		}
		return nil
	}
	res["usernameAttributeClaimMapping"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseOidcSettings_usernameAttributeClaimMapping)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetUsernameAttributeClaimMapping(val.(*OidcSettings_usernameAttributeClaimMapping))
		}
		return nil
	}
	return res
}

// GetJamfIdAuthenticationEnabled gets the jamfIdAuthenticationEnabled property value. The jamfIdAuthenticationEnabled property
// returns a *bool when successful
func (m *OidcSettings) GetJamfIdAuthenticationEnabled() *bool {
	return m.jamfIdAuthenticationEnabled
}

// GetUserMapping gets the userMapping property value. The userMapping property
// returns a *OidcSettings_userMapping when successful
func (m *OidcSettings) GetUserMapping() *OidcSettings_userMapping {
	return m.userMapping
}

// GetUsernameAttributeClaimMapping gets the usernameAttributeClaimMapping property value. The usernameAttributeClaimMapping property
// returns a *OidcSettings_usernameAttributeClaimMapping when successful
func (m *OidcSettings) GetUsernameAttributeClaimMapping() *OidcSettings_usernameAttributeClaimMapping {
	return m.usernameAttributeClaimMapping
}

// Serialize serializes information the current object
func (m *OidcSettings) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteBoolValue("jamfIdAuthenticationEnabled", m.GetJamfIdAuthenticationEnabled())
		if err != nil {
			return err
		}
	}
	if m.GetUserMapping() != nil {
		cast := (*m.GetUserMapping()).String()
		err := writer.WriteStringValue("userMapping", &cast)
		if err != nil {
			return err
		}
	}
	if m.GetUsernameAttributeClaimMapping() != nil {
		cast := (*m.GetUsernameAttributeClaimMapping()).String()
		err := writer.WriteStringValue("usernameAttributeClaimMapping", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *OidcSettings) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetJamfIdAuthenticationEnabled sets the jamfIdAuthenticationEnabled property value. The jamfIdAuthenticationEnabled property
func (m *OidcSettings) SetJamfIdAuthenticationEnabled(value *bool) {
	m.jamfIdAuthenticationEnabled = value
}

// SetUserMapping sets the userMapping property value. The userMapping property
func (m *OidcSettings) SetUserMapping(value *OidcSettings_userMapping) {
	m.userMapping = value
}

// SetUsernameAttributeClaimMapping sets the usernameAttributeClaimMapping property value. The usernameAttributeClaimMapping property
func (m *OidcSettings) SetUsernameAttributeClaimMapping(value *OidcSettings_usernameAttributeClaimMapping) {
	m.usernameAttributeClaimMapping = value
}

type OidcSettingsable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetJamfIdAuthenticationEnabled() *bool
	GetUserMapping() *OidcSettings_userMapping
	GetUsernameAttributeClaimMapping() *OidcSettings_usernameAttributeClaimMapping
	SetJamfIdAuthenticationEnabled(value *bool)
	SetUserMapping(value *OidcSettings_userMapping)
	SetUsernameAttributeClaimMapping(value *OidcSettings_usernameAttributeClaimMapping)
}
