// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type PatchSoftwareTitleConfiguration struct {
	PatchSoftwareTitleConfigurationBase
	// The id property
	id *string
	// The packages property
	packages []PatchSoftwareTitlePackagesable
}

// NewPatchSoftwareTitleConfiguration instantiates a new PatchSoftwareTitleConfiguration and sets the default values.
func NewPatchSoftwareTitleConfiguration() *PatchSoftwareTitleConfiguration {
	m := &PatchSoftwareTitleConfiguration{
		PatchSoftwareTitleConfigurationBase: *NewPatchSoftwareTitleConfigurationBase(),
	}
	return m
}

// CreatePatchSoftwareTitleConfigurationFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePatchSoftwareTitleConfigurationFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewPatchSoftwareTitleConfiguration(), nil
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PatchSoftwareTitleConfiguration) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.PatchSoftwareTitleConfigurationBase.GetFieldDeserializers()
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["packages"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfObjectValues(CreatePatchSoftwareTitlePackagesFromDiscriminatorValue)
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]PatchSoftwareTitlePackagesable, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = v.(PatchSoftwareTitlePackagesable)
				}
			}
			m.SetPackages(res)
		}
		return nil
	}
	return res
}

// GetId gets the id property value. The id property
// returns a *string when successful
func (m *PatchSoftwareTitleConfiguration) GetId() *string {
	return m.id
}

// GetPackages gets the packages property value. The packages property
// returns a []PatchSoftwareTitlePackagesable when successful
func (m *PatchSoftwareTitleConfiguration) GetPackages() []PatchSoftwareTitlePackagesable {
	return m.packages
}

// Serialize serializes information the current object
func (m *PatchSoftwareTitleConfiguration) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.PatchSoftwareTitleConfigurationBase.Serialize(writer)
	if err != nil {
		return err
	}
	{
		err = writer.WriteStringValue("id", m.GetId())
		if err != nil {
			return err
		}
	}
	if m.GetPackages() != nil {
		cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetPackages()))
		for i, v := range m.GetPackages() {
			if v != nil {
				cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
			}
		}
		err = writer.WriteCollectionOfObjectValues("packages", cast)
		if err != nil {
			return err
		}
	}
	return nil
}

// SetId sets the id property value. The id property
func (m *PatchSoftwareTitleConfiguration) SetId(value *string) {
	m.id = value
}

// SetPackages sets the packages property value. The packages property
func (m *PatchSoftwareTitleConfiguration) SetPackages(value []PatchSoftwareTitlePackagesable) {
	m.packages = value
}

type PatchSoftwareTitleConfigurationable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	PatchSoftwareTitleConfigurationBaseable
	GetId() *string
	GetPackages() []PatchSoftwareTitlePackagesable
	SetId(value *string)
	SetPackages(value []PatchSoftwareTitlePackagesable)
}
