// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// RemoteAdministrationResponse a Remote administration response
type RemoteAdministrationResponse struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The displayName property
	displayName *string
	// The id property
	id *string
	// The siteId property
	siteId *string
	// The type property
	typeEscaped *RemoteAdministrationResponse_type
}

// NewRemoteAdministrationResponse instantiates a new RemoteAdministrationResponse and sets the default values.
func NewRemoteAdministrationResponse() *RemoteAdministrationResponse {
	m := &RemoteAdministrationResponse{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateRemoteAdministrationResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRemoteAdministrationResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewRemoteAdministrationResponse(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *RemoteAdministrationResponse) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetDisplayName gets the displayName property value. The displayName property
// returns a *string when successful
func (m *RemoteAdministrationResponse) GetDisplayName() *string {
	return m.displayName
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *RemoteAdministrationResponse) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["displayName"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDisplayName(val)
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["siteId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSiteId(val)
		}
		return nil
	}
	res["type"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseRemoteAdministrationResponse_type)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetTypeEscaped(val.(*RemoteAdministrationResponse_type))
		}
		return nil
	}
	return res
}

// GetId gets the id property value. The id property
// returns a *string when successful
func (m *RemoteAdministrationResponse) GetId() *string {
	return m.id
}

// GetSiteId gets the siteId property value. The siteId property
// returns a *string when successful
func (m *RemoteAdministrationResponse) GetSiteId() *string {
	return m.siteId
}

// GetTypeEscaped gets the type property value. The type property
// returns a *RemoteAdministrationResponse_type when successful
func (m *RemoteAdministrationResponse) GetTypeEscaped() *RemoteAdministrationResponse_type {
	return m.typeEscaped
}

// Serialize serializes information the current object
func (m *RemoteAdministrationResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("displayName", m.GetDisplayName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("id", m.GetId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("siteId", m.GetSiteId())
		if err != nil {
			return err
		}
	}
	if m.GetTypeEscaped() != nil {
		cast := (*m.GetTypeEscaped()).String()
		err := writer.WriteStringValue("type", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *RemoteAdministrationResponse) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetDisplayName sets the displayName property value. The displayName property
func (m *RemoteAdministrationResponse) SetDisplayName(value *string) {
	m.displayName = value
}

// SetId sets the id property value. The id property
func (m *RemoteAdministrationResponse) SetId(value *string) {
	m.id = value
}

// SetSiteId sets the siteId property value. The siteId property
func (m *RemoteAdministrationResponse) SetSiteId(value *string) {
	m.siteId = value
}

// SetTypeEscaped sets the type property value. The type property
func (m *RemoteAdministrationResponse) SetTypeEscaped(value *RemoteAdministrationResponse_type) {
	m.typeEscaped = value
}

type RemoteAdministrationResponseable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetDisplayName() *string
	GetId() *string
	GetSiteId() *string
	GetTypeEscaped() *RemoteAdministrationResponse_type
	SetDisplayName(value *string)
	SetId(value *string)
	SetSiteId(value *string)
	SetTypeEscaped(value *RemoteAdministrationResponse_type)
}
