// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

// the default landing page in Self Service
type SelfServiceInteractionSettings_defaultLandingPage int

const (
	HOME_SELFSERVICEINTERACTIONSETTINGS_DEFAULTLANDINGPAGE SelfServiceInteractionSettings_defaultLandingPage = iota
	BROWSE_SELFSERVICEINTERACTIONSETTINGS_DEFAULTLANDINGPAGE
	HISTORY_SELFSERVICEINTERACTIONSETTINGS_DEFAULTLANDINGPAGE
	NOTIFICATIONS_SELFSERVICEINTERACTIONSETTINGS_DEFAULTLANDINGPAGE
)

func (i SelfServiceInteractionSettings_defaultLandingPage) String() string {
	return []string{"HOME", "BROWSE", "HISTORY", "NOTIFICATIONS"}[i]
}

func ParseSelfServiceInteractionSettings_defaultLandingPage(v string) (any, error) {
	result := HOME_SELFSERVICEINTERACTIONSETTINGS_DEFAULTLANDINGPAGE
	switch v {
	case "HOME":
		result = HOME_SELFSERVICEINTERACTIONSETTINGS_DEFAULTLANDINGPAGE
	case "BROWSE":
		result = BROWSE_SELFSERVICEINTERACTIONSETTINGS_DEFAULTLANDINGPAGE
	case "HISTORY":
		result = HISTORY_SELFSERVICEINTERACTIONSETTINGS_DEFAULTLANDINGPAGE
	case "NOTIFICATIONS":
		result = NOTIFICATIONS_SELFSERVICEINTERACTIONSETTINGS_DEFAULTLANDINGPAGE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeSelfServiceInteractionSettings_defaultLandingPage(values []SelfServiceInteractionSettings_defaultLandingPage) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i SelfServiceInteractionSettings_defaultLandingPage) isMultiValue() bool {
	return false
}
