// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

type SessionHistoryItemWithDetails_statusType int

const (
	STARTED_SESSIONHISTORYITEMWITHDETAILS_STATUSTYPE SessionHistoryItemWithDetails_statusType = iota
	FINISHED_SESSIONHISTORYITEMWITHDETAILS_STATUSTYPE
	ERROR_SESSIONHISTORYITEMWITHDETAILS_STATUSTYPE
)

func (i SessionHistoryItemWithDetails_statusType) String() string {
	return []string{"STARTED", "FINISHED", "ERROR"}[i]
}

func ParseSessionHistoryItemWithDetails_statusType(v string) (any, error) {
	result := STARTED_SESSIONHISTORYITEMWITHDETAILS_STATUSTYPE
	switch v {
	case "STARTED":
		result = STARTED_SESSIONHISTORYITEMWITHDETAILS_STATUSTYPE
	case "FINISHED":
		result = FINISHED_SESSIONHISTORYITEMWITHDETAILS_STATUSTYPE
	case "ERROR":
		result = ERROR_SESSIONHISTORYITEMWITHDETAILS_STATUSTYPE
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeSessionHistoryItemWithDetails_statusType(values []SessionHistoryItemWithDetails_statusType) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i SessionHistoryItemWithDetails_statusType) isMultiValue() bool {
	return false
}
