// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Signature struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The algorithm property
	algorithm *string
	// The algorithmOid property
	algorithmOid *string
	// The value property
	value *string
}

// NewSignature instantiates a new Signature and sets the default values.
func NewSignature() *Signature {
	m := &Signature{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateSignatureFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSignatureFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewSignature(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Signature) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAlgorithm gets the algorithm property value. The algorithm property
// returns a *string when successful
func (m *Signature) GetAlgorithm() *string {
	return m.algorithm
}

// GetAlgorithmOid gets the algorithmOid property value. The algorithmOid property
// returns a *string when successful
func (m *Signature) GetAlgorithmOid() *string {
	return m.algorithmOid
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Signature) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["algorithm"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAlgorithm(val)
		}
		return nil
	}
	res["algorithmOid"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetAlgorithmOid(val)
		}
		return nil
	}
	res["value"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetValue(val)
		}
		return nil
	}
	return res
}

// GetValue gets the value property value. The value property
// returns a *string when successful
func (m *Signature) GetValue() *string {
	return m.value
}

// Serialize serializes information the current object
func (m *Signature) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("algorithm", m.GetAlgorithm())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("algorithmOid", m.GetAlgorithmOid())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("value", m.GetValue())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Signature) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAlgorithm sets the algorithm property value. The algorithm property
func (m *Signature) SetAlgorithm(value *string) {
	m.algorithm = value
}

// SetAlgorithmOid sets the algorithmOid property value. The algorithmOid property
func (m *Signature) SetAlgorithmOid(value *string) {
	m.algorithmOid = value
}

// SetValue sets the value property value. The value property
func (m *Signature) SetValue(value *string) {
	m.value = value
}

type Signatureable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAlgorithm() *string
	GetAlgorithmOid() *string
	GetValue() *string
	SetAlgorithm(value *string)
	SetAlgorithmOid(value *string)
	SetValue(value *string)
}
