// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

type SlasaAcceptance_slasaAcceptanceStatus int

const (
	ACCEPTED_SLASAACCEPTANCE_SLASAACCEPTANCESTATUS SlasaAcceptance_slasaAcceptanceStatus = iota
	NOT_ACCEPTED_SLASAACCEPTANCE_SLASAACCEPTANCESTATUS
)

func (i SlasaAcceptance_slasaAcceptanceStatus) String() string {
	return []string{"ACCEPTED", "NOT_ACCEPTED"}[i]
}

func ParseSlasaAcceptance_slasaAcceptanceStatus(v string) (any, error) {
	result := ACCEPTED_SLASAACCEPTANCE_SLASAACCEPTANCESTATUS
	switch v {
	case "ACCEPTED":
		result = ACCEPTED_SLASAACCEPTANCE_SLASAACCEPTANCESTATUS
	case "NOT_ACCEPTED":
		result = NOT_ACCEPTED_SLASAACCEPTANCE_SLASAACCEPTANCESTATUS
	default:
		return nil, nil
	}
	return &result, nil
}

func SerializeSlasaAcceptance_slasaAcceptanceStatus(values []SlasaAcceptance_slasaAcceptanceStatus) []string {
	result := make([]string, len(values))
	for i, v := range values {
		result[i] = v.String()
	}
	return result
}

func (i SlasaAcceptance_slasaAcceptanceStatus) isMultiValue() bool {
	return false
}
