// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SoftwareUpdateSettings struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The recommendationCadence property
	recommendationCadence *SoftwareUpdateSettings_recommendationCadence
}

// NewSoftwareUpdateSettings instantiates a new SoftwareUpdateSettings and sets the default values.
func NewSoftwareUpdateSettings() *SoftwareUpdateSettings {
	m := &SoftwareUpdateSettings{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateSoftwareUpdateSettingsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSoftwareUpdateSettingsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewSoftwareUpdateSettings(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *SoftwareUpdateSettings) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SoftwareUpdateSettings) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["recommendationCadence"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetEnumValue(ParseSoftwareUpdateSettings_recommendationCadence)
		if err != nil {
			return err
		}
		if val != nil {
			m.SetRecommendationCadence(val.(*SoftwareUpdateSettings_recommendationCadence))
		}
		return nil
	}
	return res
}

// GetRecommendationCadence gets the recommendationCadence property value. The recommendationCadence property
// returns a *SoftwareUpdateSettings_recommendationCadence when successful
func (m *SoftwareUpdateSettings) GetRecommendationCadence() *SoftwareUpdateSettings_recommendationCadence {
	return m.recommendationCadence
}

// Serialize serializes information the current object
func (m *SoftwareUpdateSettings) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetRecommendationCadence() != nil {
		cast := (*m.GetRecommendationCadence()).String()
		err := writer.WriteStringValue("recommendationCadence", &cast)
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *SoftwareUpdateSettings) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetRecommendationCadence sets the recommendationCadence property value. The recommendationCadence property
func (m *SoftwareUpdateSettings) SetRecommendationCadence(value *SoftwareUpdateSettings_recommendationCadence) {
	m.recommendationCadence = value
}

type SoftwareUpdateSettingsable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetRecommendationCadence() *SoftwareUpdateSettings_recommendationCadence
	SetRecommendationCadence(value *SoftwareUpdateSettings_recommendationCadence)
}
