// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type StaticComputerGroupAssignment struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// Set of computer IDs to assign to the static group
	assignments []string
	// The description property
	description *string
	// The id property
	id *string
	// The name property
	name *string
	// The siteId property
	siteId *string
}

// NewStaticComputerGroupAssignment instantiates a new StaticComputerGroupAssignment and sets the default values.
func NewStaticComputerGroupAssignment() *StaticComputerGroupAssignment {
	m := &StaticComputerGroupAssignment{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateStaticComputerGroupAssignmentFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateStaticComputerGroupAssignmentFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewStaticComputerGroupAssignment(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *StaticComputerGroupAssignment) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetAssignments gets the assignments property value. Set of computer IDs to assign to the static group
// returns a []string when successful
func (m *StaticComputerGroupAssignment) GetAssignments() []string {
	return m.assignments
}

// GetDescription gets the description property value. The description property
// returns a *string when successful
func (m *StaticComputerGroupAssignment) GetDescription() *string {
	return m.description
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *StaticComputerGroupAssignment) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["assignments"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetCollectionOfPrimitiveValues("string")
		if err != nil {
			return err
		}
		if val != nil {
			res := make([]string, len(val))
			for i, v := range val {
				if v != nil {
					res[i] = *v.(*string)
				}
			}
			m.SetAssignments(res)
		}
		return nil
	}
	res["description"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDescription(val)
		}
		return nil
	}
	res["id"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetId(val)
		}
		return nil
	}
	res["name"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetName(val)
		}
		return nil
	}
	res["siteId"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetSiteId(val)
		}
		return nil
	}
	return res
}

// GetId gets the id property value. The id property
// returns a *string when successful
func (m *StaticComputerGroupAssignment) GetId() *string {
	return m.id
}

// GetName gets the name property value. The name property
// returns a *string when successful
func (m *StaticComputerGroupAssignment) GetName() *string {
	return m.name
}

// GetSiteId gets the siteId property value. The siteId property
// returns a *string when successful
func (m *StaticComputerGroupAssignment) GetSiteId() *string {
	return m.siteId
}

// Serialize serializes information the current object
func (m *StaticComputerGroupAssignment) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	if m.GetAssignments() != nil {
		err := writer.WriteCollectionOfStringValues("assignments", m.GetAssignments())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("description", m.GetDescription())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("name", m.GetName())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("siteId", m.GetSiteId())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *StaticComputerGroupAssignment) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetAssignments sets the assignments property value. Set of computer IDs to assign to the static group
func (m *StaticComputerGroupAssignment) SetAssignments(value []string) {
	m.assignments = value
}

// SetDescription sets the description property value. The description property
func (m *StaticComputerGroupAssignment) SetDescription(value *string) {
	m.description = value
}

// SetId sets the id property value. The id property
func (m *StaticComputerGroupAssignment) SetId(value *string) {
	m.id = value
}

// SetName sets the name property value. The name property
func (m *StaticComputerGroupAssignment) SetName(value *string) {
	m.name = value
}

// SetSiteId sets the siteId property value. The siteId property
func (m *StaticComputerGroupAssignment) SetSiteId(value *string) {
	m.siteId = value
}

type StaticComputerGroupAssignmentable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetAssignments() []string
	GetDescription() *string
	GetId() *string
	GetName() *string
	GetSiteId() *string
	SetAssignments(value []string)
	SetDescription(value *string)
	SetId(value *string)
	SetName(value *string)
	SetSiteId(value *string)
}
