// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ValidateApplicationsCommand struct {
	MdmCommandBase
}

// NewValidateApplicationsCommand instantiates a new ValidateApplicationsCommand and sets the default values.
func NewValidateApplicationsCommand() *ValidateApplicationsCommand {
	m := &ValidateApplicationsCommand{
		MdmCommandBase: *NewMdmCommandBase(),
	}
	return m
}

// CreateValidateApplicationsCommandFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateValidateApplicationsCommandFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewValidateApplicationsCommand(), nil
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ValidateApplicationsCommand) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := m.MdmCommandBase.GetFieldDeserializers()
	return res
}

// Serialize serializes information the current object
func (m *ValidateApplicationsCommand) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	err := m.MdmCommandBase.Serialize(writer)
	if err != nil {
		return err
	}
	return nil
}

type ValidateApplicationsCommandable interface {
	MdmCommandBaseable
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
