// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// VerbosePackageDeploymentResponse_errors the error will contain either the 'device' or 'group' property
type VerbosePackageDeploymentResponse_errors struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The device property
	device *int32
	// The group property
	group *int32
	// The reason property
	reason *string
}

// NewVerbosePackageDeploymentResponse_errors instantiates a new VerbosePackageDeploymentResponse_errors and sets the default values.
func NewVerbosePackageDeploymentResponse_errors() *VerbosePackageDeploymentResponse_errors {
	m := &VerbosePackageDeploymentResponse_errors{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateVerbosePackageDeploymentResponse_errorsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVerbosePackageDeploymentResponse_errorsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewVerbosePackageDeploymentResponse_errors(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *VerbosePackageDeploymentResponse_errors) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetDevice gets the device property value. The device property
// returns a *int32 when successful
func (m *VerbosePackageDeploymentResponse_errors) GetDevice() *int32 {
	return m.device
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *VerbosePackageDeploymentResponse_errors) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["device"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDevice(val)
		}
		return nil
	}
	res["group"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetGroup(val)
		}
		return nil
	}
	res["reason"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetReason(val)
		}
		return nil
	}
	return res
}

// GetGroup gets the group property value. The group property
// returns a *int32 when successful
func (m *VerbosePackageDeploymentResponse_errors) GetGroup() *int32 {
	return m.group
}

// GetReason gets the reason property value. The reason property
// returns a *string when successful
func (m *VerbosePackageDeploymentResponse_errors) GetReason() *string {
	return m.reason
}

// Serialize serializes information the current object
func (m *VerbosePackageDeploymentResponse_errors) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteInt32Value("device", m.GetDevice())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("group", m.GetGroup())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteStringValue("reason", m.GetReason())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *VerbosePackageDeploymentResponse_errors) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetDevice sets the device property value. The device property
func (m *VerbosePackageDeploymentResponse_errors) SetDevice(value *int32) {
	m.device = value
}

// SetGroup sets the group property value. The group property
func (m *VerbosePackageDeploymentResponse_errors) SetGroup(value *int32) {
	m.group = value
}

// SetReason sets the reason property value. The reason property
func (m *VerbosePackageDeploymentResponse_errors) SetReason(value *string) {
	m.reason = value
}

type VerbosePackageDeploymentResponse_errorsable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetDevice() *int32
	GetGroup() *int32
	GetReason() *string
	SetDevice(value *int32)
	SetGroup(value *int32)
	SetReason(value *string)
}
