// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type VerbosePackageDeploymentResponse_queuedCommands struct {
	// Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
	additionalData map[string]any
	// The commandUuid property
	commandUuid *string
	// The device property
	device *int32
}

// NewVerbosePackageDeploymentResponse_queuedCommands instantiates a new VerbosePackageDeploymentResponse_queuedCommands and sets the default values.
func NewVerbosePackageDeploymentResponse_queuedCommands() *VerbosePackageDeploymentResponse_queuedCommands {
	m := &VerbosePackageDeploymentResponse_queuedCommands{}
	m.SetAdditionalData(make(map[string]any))
	return m
}

// CreateVerbosePackageDeploymentResponse_queuedCommandsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVerbosePackageDeploymentResponse_queuedCommandsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) (i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
	return NewVerbosePackageDeploymentResponse_queuedCommands(), nil
}

// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *VerbosePackageDeploymentResponse_queuedCommands) GetAdditionalData() map[string]any {
	return m.additionalData
}

// GetCommandUuid gets the commandUuid property value. The commandUuid property
// returns a *string when successful
func (m *VerbosePackageDeploymentResponse_queuedCommands) GetCommandUuid() *string {
	return m.commandUuid
}

// GetDevice gets the device property value. The device property
// returns a *int32 when successful
func (m *VerbosePackageDeploymentResponse_queuedCommands) GetDevice() *int32 {
	return m.device
}

// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *VerbosePackageDeploymentResponse_queuedCommands) GetFieldDeserializers() map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
	res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error)
	res["commandUuid"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetStringValue()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetCommandUuid(val)
		}
		return nil
	}
	res["device"] = func(n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
		val, err := n.GetInt32Value()
		if err != nil {
			return err
		}
		if val != nil {
			m.SetDevice(val)
		}
		return nil
	}
	return res
}

// Serialize serializes information the current object
func (m *VerbosePackageDeploymentResponse_queuedCommands) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter) error {
	{
		err := writer.WriteStringValue("commandUuid", m.GetCommandUuid())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteInt32Value("device", m.GetDevice())
		if err != nil {
			return err
		}
	}
	{
		err := writer.WriteAdditionalData(m.GetAdditionalData())
		if err != nil {
			return err
		}
	}
	return nil
}

// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *VerbosePackageDeploymentResponse_queuedCommands) SetAdditionalData(value map[string]any) {
	m.additionalData = value
}

// SetCommandUuid sets the commandUuid property value. The commandUuid property
func (m *VerbosePackageDeploymentResponse_queuedCommands) SetCommandUuid(value *string) {
	m.commandUuid = value
}

// SetDevice sets the device property value. The device property
func (m *VerbosePackageDeploymentResponse_queuedCommands) SetDevice(value *int32) {
	m.device = value
}

type VerbosePackageDeploymentResponse_queuedCommandsable interface {
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
	i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
	GetCommandUuid() *string
	GetDevice() *int32
	SetCommandUuid(value *string)
	SetDevice(value *int32)
}
