// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:e29c3c55fac9427f0859dfeab08822cf7cbca1463246f5d9cdeb8393ab9d2a4c). DO NOT EDIT.

package v1_onboarding_eligible_policy

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// V1OnboardingEligiblePolicyDataSourceModel is the Terraform state for a jamfpro_v1_onboarding_eligible_policy.
//
// Field order follows the schema, and the timeouts value is last.
type V1OnboardingEligiblePolicyDataSourceModel struct {
	ID               types.String   `tfsdk:"id"`
	Name             types.String   `tfsdk:"name"`
	ScopeDescription types.String   `tfsdk:"scope_description"`
	SiteDescription  types.String   `tfsdk:"site_description"`
	Timeouts         timeouts.Value `tfsdk:"timeouts"`
}
