// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:871c3b053ae073a64e0d70d624eefe6f67179a2717a44566972b2e35df2ff285). DO NOT EDIT.

package credential

import (
	"context"

	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/thousandeyes_api/credentials"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/services/common/convert"
)

// constructResource maps Terraform configuration onto the API's request body.
//
// Only writable attributes appear here. A computed attribute has no expand
// conversion, so it cannot be sent by construction rather than by discipline.
func constructResource(ctx context.Context, data *CredentialResourceModel) *credentials.CredentialRequest {
	tflog.Debug(ctx, "constructing request body", map[string]any{"resource": ResourceName})

	body := &credentials.CredentialRequest{}

	body.Name = convert.FrameworkToPtrString(data.Name)
	body.Value = convert.FrameworkToPtrString(data.Value)

	return body
}
