// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v3

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ComputerGroupsSmartGroupsRequestBuilder builds and executes requests for operations under \v3\computer-groups\smart-groups
type ComputerGroupsSmartGroupsRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// ComputerGroupsSmartGroupsRequestBuilderGetQueryParameters search for Smart Computer Groups
type ComputerGroupsSmartGroupsRequestBuilderGetQueryParameters struct {
	// Query in the RSQL format, allowing to filter smart computer group collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: id, name, siteId. The siteId field can only be filtered by admins with full access. Any sited admin will have siteId filtered automatically. Example: name=="*group*"
	Filter   *string "uriparametername:\"filter\""
	Page     *int32  "uriparametername:\"page\""
	PageSize *int32  "uriparametername:\"page%2Dsize\""
	// Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma. Example: sort=name:asc
	Sort []string "uriparametername:\"sort\""
}

// ComputerGroupsSmartGroupsRequestBuilderPostQueryParameters creates a Smart Computer Group with strict andOr enum validation.
type ComputerGroupsSmartGroupsRequestBuilderPostQueryParameters struct {
	// Optional. Return platform identifiers instead of internal identifiers when set to true.
	Platform *bool "uriparametername:\"platform\""
}

// ById gets an item from the github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk.v3.computerGroups.smartGroups.item collection
// returns a *ComputerGroupsSmartGroupsSmartGroupsItemRequestBuilder when successful
func (m *ComputerGroupsSmartGroupsRequestBuilder) ById(id string) *ComputerGroupsSmartGroupsSmartGroupsItemRequestBuilder {
	urlTplParams := make(map[string]string)
	for idx, item := range m.BaseRequestBuilder.PathParameters {
		urlTplParams[idx] = item
	}
	if id != "" {
		urlTplParams["id"] = id
	}
	return NewComputerGroupsSmartGroupsSmartGroupsItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}

// NewComputerGroupsSmartGroupsRequestBuilderInternal instantiates a new ComputerGroupsSmartGroupsRequestBuilder and sets the default values.
func NewComputerGroupsSmartGroupsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ComputerGroupsSmartGroupsRequestBuilder {
	m := &ComputerGroupsSmartGroupsRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v3/computer-groups/smart-groups{?filter*,page*,page%2Dsize*,platform*,sort*}", pathParameters),
	}
	return m
}

// NewComputerGroupsSmartGroupsRequestBuilder instantiates a new ComputerGroupsSmartGroupsRequestBuilder and sets the default values.
func NewComputerGroupsSmartGroupsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *ComputerGroupsSmartGroupsRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewComputerGroupsSmartGroupsRequestBuilderInternal(urlParams, requestAdapter)
}

// Get search for Smart Computer Groups
// returns a SmartGroupSearchResultable when successful
func (m *ComputerGroupsSmartGroupsRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ComputerGroupsSmartGroupsRequestBuilderGetQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.SmartGroupSearchResultable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateSmartGroupSearchResultFromDiscriminatorValue, nil)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.SmartGroupSearchResultable), nil
}

// Post creates a Smart Computer Group with strict andOr enum validation.
// returns a HrefResponseable when successful
// returns a ApiError error when the service returns a 400 status code
// returns a ApiError error when the service returns a 422 status code
func (m *ComputerGroupsSmartGroupsRequestBuilder) Post(ctx context.Context, body id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.SmartComputerGroupV3able, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ComputerGroupsSmartGroupsRequestBuilderPostQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.HrefResponseable, error) {
	requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
		"422": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateHrefResponseFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.HrefResponseable), nil
}

// ToGetRequestInformation search for Smart Computer Groups
// returns a *RequestInformation when successful
func (m *ComputerGroupsSmartGroupsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ComputerGroupsSmartGroupsRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// ToPostRequestInformation creates a Smart Computer Group with strict andOr enum validation.
// returns a *RequestInformation when successful
func (m *ComputerGroupsSmartGroupsRequestBuilder) ToPostRequestInformation(ctx context.Context, body id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.SmartComputerGroupV3able, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ComputerGroupsSmartGroupsRequestBuilderPostQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
	if err != nil {
		return nil, err
	}
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ComputerGroupsSmartGroupsRequestBuilder when successful
func (m *ComputerGroupsSmartGroupsRequestBuilder) WithUrl(rawUrl string) *ComputerGroupsSmartGroupsRequestBuilder {
	return NewComputerGroupsSmartGroupsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
