// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:e29c3c55fac9427f0859dfeab08822cf7cbca1463246f5d9cdeb8393ab9d2a4c). DO NOT EDIT.

package v1_volume_purchasing_location

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/client"
	sdk "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk"
	commonschema "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/services/common/schema"
)

const (
	// TypeName is the Terraform type this resource registers as.
	TypeName = "jamfpro_v1_volume_purchasing_location"

	// Default per-operation timeouts, in seconds. A practitioner overrides them
	// with the resource's timeouts block.
	CreateTimeout = 180
	ReadTimeout   = 180
	UpdateTimeout = 180
	DeleteTimeout = 180
)

// Compile-time assertions that this resource implements what it claims to. They
// turn a missing method into a build failure rather than a runtime surprise.
var (
	_ resource.Resource                = (*V1VolumePurchasingLocationResource)(nil)
	_ resource.ResourceWithConfigure   = (*V1VolumePurchasingLocationResource)(nil)
	_ resource.ResourceWithImportState = (*V1VolumePurchasingLocationResource)(nil)
)

// NewV1VolumePurchasingLocationResource returns the jamfpro_v1_volume_purchasing_location resource.
func NewV1VolumePurchasingLocationResource() resource.Resource {
	return &V1VolumePurchasingLocationResource{}
}

// V1VolumePurchasingLocationResource implements the jamfpro_v1_volume_purchasing_location resource.
type V1VolumePurchasingLocationResource struct {
	client *sdk.JamfProClient
}

// Metadata returns the resource type name.
func (r *V1VolumePurchasingLocationResource) Metadata(_ context.Context, _ resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = TypeName
}

// Configure receives the configured SDK client from the provider.
func (r *V1VolumePurchasingLocationResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = client.ForResource(ctx, req, resp, TypeName)
}

// ImportState maps a terraform import into state.
func (r *V1VolumePurchasingLocationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// Schema returns the resource schema.
func (r *V1VolumePurchasingLocationResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieve a Volume Purchasing Location with the supplied id.",
		Attributes: map[string]schema.Attribute{
			"apple_id": schema.StringAttribute{
				Computed: true,
			},
			"auto_register_managed_users": schema.BoolAttribute{
				Optional: true,
			},
			"automatically_populate_purchased_content": schema.BoolAttribute{
				Optional: true,
			},
			"client_context_mismatch": schema.BoolAttribute{
				Computed: true,
				MarkdownDescription: "If this is \"true\", the clientContext used by this server does not match the clientContext " +
					"returned by the Volume Purchasing API.",
			},
			"content": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"adam_id": schema.StringAttribute{
							Computed: true,
						},
						"content_type": schema.StringAttribute{
							Computed: true,
						},
						"device_types": schema.SetAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"icon_url": schema.StringAttribute{
							Computed: true,
						},
						"license_count_in_use": schema.Int64Attribute{
							Computed: true,
						},
						"license_count_reported": schema.Int64Attribute{
							Computed: true,
						},
						"license_count_total": schema.Int64Attribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"pricing_param": schema.StringAttribute{
							Computed: true,
						},
					},
				},
				Computed: true,
			},
			"country_code": schema.StringAttribute{
				Computed: true,
				MarkdownDescription: "The two-letter ISO 3166-1 code that designates the country where the Volume Purchasing " +
					"account is located.",
			},
			"email": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_sync_time": schema.StringAttribute{
				Computed: true,
			},
			"location_name": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Optional: true,
				MarkdownDescription: "If no value is provided when creating a VolumePurchasingLocation object, the 'name' will " +
					"default to the 'locationName' value",
			},
			"organization_name": schema.StringAttribute{
				Computed: true,
			},
			"send_notification_when_no_longer_assigned": schema.BoolAttribute{
				Optional: true,
			},
			"site_id": schema.StringAttribute{
				Optional: true,
			},
			"site_name": schema.StringAttribute{
				Computed: true,
			},
			"token_expiration": schema.StringAttribute{
				Computed: true,
			},
			"total_purchased_licenses": schema.Int64Attribute{
				Computed: true,
			},
			"total_used_licenses": schema.Int64Attribute{
				Computed: true,
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": commonschema.ResourceTimeouts(ctx),
		},
	}
}
