# Code generated by tfpfgen from blueprints/thousandeyes-kiota
# (sha256:66d43c79404f9a1a2dfee966ad4281335bad90a175b22bbeae34019e261935fb). DO NOT EDIT.

# The smallest configuration this resource accepts: its required attributes and nothing else.
#
# Regenerated, so it follows the schema. If the API starts requiring a field, this file gains it
# on the next emit rather than an acceptance run discovering it.

resource "thousandeyes_dashboard" "test" {
  title = "tfacc-title"
}
