# Code generated by tfpfgen from blueprints/jamfpro
# (sha256:92588417fa010d48e3954c780a1c7284689923c40fd60ea7464f85cbc75b43eb). DO NOT EDIT.

# The widest configuration the evidence supports: every writable attribute with a derivable
# value, chosen by the same derivation the rehearsal probe sends to the live API.
#
# Regenerated and policed, deliberately. This file used to be a hand-owned scaffold, and
# hand edits are how its values drifted from the generated assertions -- the checks derive
# from the blueprint, so the blueprint is where a value is corrected: an accFixture hint for
# something only a human knows, recorded behaviour for everything the probe observed. What
# could not be derived is listed inside the block, each with the reason.

resource "jamfpro_v1_distribution_point" "test" {
  #
  # Not filled in, because no correct value could be derived. Each of these is optional, so this
  # configuration is valid as it stands -- but it is testing less than it could.
  #
  # backup_distribution_point_id: it references an object that must already exist, which a
  # synthesised value cannot name; supply one through accFixture if the test has the object
  #
  # https_password: it is credential-shaped, and a generated fixture must not invent values that
  # read as secrets; supply one through accFixture if the test needs it
  #
  # https_username: it is credential-shaped, and a generated fixture must not invent values that
  # read as secrets; supply one through accFixture if the test needs it
  #
  # read_only_password: it is credential-shaped, and a generated fixture must not invent values
  # that read as secrets; supply one through accFixture if the test needs it
  #
  # read_only_username: it is credential-shaped, and a generated fixture must not invent values
  # that read as secrets; supply one through accFixture if the test needs it
  #
  # read_write_password: it is credential-shaped, and a generated fixture must not invent values
  # that read as secrets; supply one through accFixture if the test needs it
  #
  # read_write_username: it is credential-shaped, and a generated fixture must not invent values
  # that read as secrets; supply one through accFixture if the test needs it
  #
  # ssh_password: it is credential-shaped, and a generated fixture must not invent values that
  # read as secrets; supply one through accFixture if the test needs it
  #
  # ssh_username: it is credential-shaped, and a generated fixture must not invent values that
  # read as secrets; supply one through accFixture if the test needs it
  enable_load_balancing        = true
  file_sharing_connection_type = "tfacc-file-sharing-connection-type"
  https_context                = "tfacc-https-context"
  https_enabled                = true
  https_port                   = 1
  https_security_type          = "tfacc-https-security-type"
  local_path_to_share          = "tfacc-local-path-to-share"
  name                         = "tfacc-name"
  port                         = 1
  principal                    = true
  server_name                  = "tfacc-server-name"
  share_name                   = "tfacc-share-name"
  workgroup                    = "tfacc-workgroup"
}
