// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:bf6272b765f980ac893921a34f7eb40873d02a42c4df60955393027f30f6a344). DO NOT EDIT.

package disable_endpoint_agent

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// DisableEndpointAgentConfig is the configuration for a thousandeyes_disable_endpoint_agent.
//
// Named for configuration rather than state, because an action has no state: this is decoded
// from InvokeRequest.Config and never written back.
type DisableEndpointAgentConfig struct {
	AgentID types.String `tfsdk:"agent_id"`
}
