// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:e29c3c55fac9427f0859dfeab08822cf7cbca1463246f5d9cdeb8393ab9d2a4c). DO NOT EDIT.

package v3_computer_prestage

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// V3ComputerPrestageDataSourceModel is the Terraform state for a jamfpro_v3_computer_prestage.
//
// Field order follows the schema, and the timeouts value is last.
type V3ComputerPrestageDataSourceModel struct {
	AccountSettings                    types.Object   `tfsdk:"account_settings"`
	AnchorCertificates                 types.Set      `tfsdk:"anchor_certificates"`
	AuthenticationPrompt               types.String   `tfsdk:"authentication_prompt"`
	AutoAdvanceSetup                   types.Bool     `tfsdk:"auto_advance_setup"`
	CustomPackageDistributionPointID   types.String   `tfsdk:"custom_package_distribution_point_id"`
	CustomPackageIDs                   types.Set      `tfsdk:"custom_package_ids"`
	DefaultPrestage                    types.Bool     `tfsdk:"default_prestage"`
	Department                         types.String   `tfsdk:"department"`
	DeviceEnrollmentProgramInstanceID  types.String   `tfsdk:"device_enrollment_program_instance_id"`
	DisplayName                        types.String   `tfsdk:"display_name"`
	EnableDeviceBasedActivationLock    types.Bool     `tfsdk:"enable_device_based_activation_lock"`
	EnableRecoveryLock                 types.Bool     `tfsdk:"enable_recovery_lock"`
	EnrollmentCustomizationID          types.String   `tfsdk:"enrollment_customization_id"`
	EnrollmentSiteID                   types.String   `tfsdk:"enrollment_site_id"`
	ID                                 types.String   `tfsdk:"id"`
	InstallProfilesDuringSetup         types.Bool     `tfsdk:"install_profiles_during_setup"`
	KeepExistingLocationInformation    types.Bool     `tfsdk:"keep_existing_location_information"`
	KeepExistingSiteMembership         types.Bool     `tfsdk:"keep_existing_site_membership"`
	Language                           types.String   `tfsdk:"language"`
	LocationInformation                types.Object   `tfsdk:"location_information"`
	Mandatory                          types.Bool     `tfsdk:"mandatory"`
	ManifestURL                        types.String   `tfsdk:"manifest_url"`
	MdmRemovable                       types.Bool     `tfsdk:"mdm_removable"`
	MinimumOSSpecificVersion           types.String   `tfsdk:"minimum_os_specific_version"`
	PlatformSsoAppBundleID             types.String   `tfsdk:"platform_sso_app_bundle_id"`
	PrestageInstalledProfileIDs        types.Set      `tfsdk:"prestage_installed_profile_ids"`
	PrestageMinimumOSTargetVersionType types.String   `tfsdk:"prestage_minimum_os_target_version_type"`
	PreventActivationLock              types.Bool     `tfsdk:"prevent_activation_lock"`
	ProfileURL                         types.String   `tfsdk:"profile_url"`
	ProfileUUID                        types.String   `tfsdk:"profile_uuid"`
	PssoConfigProfileID                types.String   `tfsdk:"psso_config_profile_id"`
	PssoEnabled                        types.Bool     `tfsdk:"psso_enabled"`
	PurchasingInformation              types.Object   `tfsdk:"purchasing_information"`
	RecoveryLockPasswordType           types.String   `tfsdk:"recovery_lock_password_type"`
	Region                             types.String   `tfsdk:"region"`
	RequireAuthentication              types.Bool     `tfsdk:"require_authentication"`
	RotateRecoveryLockPassword         types.Bool     `tfsdk:"rotate_recovery_lock_password"`
	SiteID                             types.String   `tfsdk:"site_id"`
	SupportEmailAddress                types.String   `tfsdk:"support_email_address"`
	SupportPhoneNumber                 types.String   `tfsdk:"support_phone_number"`
	VersionLock                        types.Int64    `tfsdk:"version_lock"`
	Timeouts                           timeouts.Value `tfsdk:"timeouts"`
}

// V3ComputerPrestageAccountSettingsResponseModel is one element of a nested attribute.
//
// It is a sibling of the data source model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V3ComputerPrestageAccountSettingsResponseModel struct {
	AdminUsername                           types.String `tfsdk:"admin_username"`
	HiddenAdminAccount                      types.Bool   `tfsdk:"hidden_admin_account"`
	ID                                      types.String `tfsdk:"id"`
	LocalAdminAccountEnabled                types.Bool   `tfsdk:"local_admin_account_enabled"`
	LocalUserManaged                        types.Bool   `tfsdk:"local_user_managed"`
	PayloadConfigured                       types.Bool   `tfsdk:"payload_configured"`
	PrefillAccountFullName                  types.String `tfsdk:"prefill_account_full_name"`
	PrefillAccountUserName                  types.String `tfsdk:"prefill_account_user_name"`
	PrefillPrimaryAccountInfoFeatureEnabled types.Bool   `tfsdk:"prefill_primary_account_info_feature_enabled"`
	PrefillType                             types.String `tfsdk:"prefill_type"`
	PreventPrefillInfoFromModification      types.Bool   `tfsdk:"prevent_prefill_info_from_modification"`
	UserAccountType                         types.String `tfsdk:"user_account_type"`
	VersionLock                             types.Int64  `tfsdk:"version_lock"`
}

// v3ComputerPrestageAccountSettingsResponseAttrTypes describes V3ComputerPrestageAccountSettingsResponseModel to the framework.
//
// It is declared once and referenced by the conversion helper, so the shape cannot
// drift between the declaration and the code that populates it.
var v3ComputerPrestageAccountSettingsResponseAttrTypes = map[string]attr.Type{
	"admin_username":              types.StringType,
	"hidden_admin_account":        types.BoolType,
	"id":                          types.StringType,
	"local_admin_account_enabled": types.BoolType,
	"local_user_managed":          types.BoolType,
	"payload_configured":          types.BoolType,
	"prefill_account_full_name":   types.StringType,
	"prefill_account_user_name":   types.StringType,
	"prefill_primary_account_info_feature_enabled": types.BoolType,
	"prefill_type":                           types.StringType,
	"prevent_prefill_info_from_modification": types.BoolType,
	"user_account_type":                      types.StringType,
	"version_lock":                           types.Int64Type,
}

var v3ComputerPrestageAccountSettingsResponseObjectType = types.ObjectType{AttrTypes: v3ComputerPrestageAccountSettingsResponseAttrTypes}

// V3ComputerPrestageLocationInformationV2Model is one element of a nested attribute.
//
// It is a sibling of the data source model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V3ComputerPrestageLocationInformationV2Model struct {
	BuildingID   types.String `tfsdk:"building_id"`
	DepartmentID types.String `tfsdk:"department_id"`
	Email        types.String `tfsdk:"email"`
	ID           types.String `tfsdk:"id"`
	Phone        types.String `tfsdk:"phone"`
	Position     types.String `tfsdk:"position"`
	Realname     types.String `tfsdk:"realname"`
	Room         types.String `tfsdk:"room"`
	Username     types.String `tfsdk:"username"`
	VersionLock  types.Int64  `tfsdk:"version_lock"`
}

// v3ComputerPrestageLocationInformationV2AttrTypes describes V3ComputerPrestageLocationInformationV2Model to the framework.
//
// It is declared once and referenced by the conversion helper, so the shape cannot
// drift between the declaration and the code that populates it.
var v3ComputerPrestageLocationInformationV2AttrTypes = map[string]attr.Type{
	"building_id":   types.StringType,
	"department_id": types.StringType,
	"email":         types.StringType,
	"id":            types.StringType,
	"phone":         types.StringType,
	"position":      types.StringType,
	"realname":      types.StringType,
	"room":          types.StringType,
	"username":      types.StringType,
	"version_lock":  types.Int64Type,
}

var v3ComputerPrestageLocationInformationV2ObjectType = types.ObjectType{AttrTypes: v3ComputerPrestageLocationInformationV2AttrTypes}

// V3ComputerPrestagePrestagePurchasingInformationV2Model is one element of a nested attribute.
//
// It is a sibling of the data source model rather than an inner type, because the
// framework decodes collection elements into a named type.
type V3ComputerPrestagePrestagePurchasingInformationV2Model struct {
	AppleCareID       types.String `tfsdk:"apple_care_id"`
	ID                types.String `tfsdk:"id"`
	LeaseDate         types.String `tfsdk:"lease_date"`
	Leased            types.Bool   `tfsdk:"leased"`
	LifeExpectancy    types.Int64  `tfsdk:"life_expectancy"`
	PoDate            types.String `tfsdk:"po_date"`
	PoNumber          types.String `tfsdk:"po_number"`
	PurchasePrice     types.String `tfsdk:"purchase_price"`
	Purchased         types.Bool   `tfsdk:"purchased"`
	PurchasingAccount types.String `tfsdk:"purchasing_account"`
	PurchasingContact types.String `tfsdk:"purchasing_contact"`
	Vendor            types.String `tfsdk:"vendor"`
	VersionLock       types.Int64  `tfsdk:"version_lock"`
	WarrantyDate      types.String `tfsdk:"warranty_date"`
}

// v3ComputerPrestagePrestagePurchasingInformationV2AttrTypes describes V3ComputerPrestagePrestagePurchasingInformationV2Model to the framework.
//
// It is declared once and referenced by the conversion helper, so the shape cannot
// drift between the declaration and the code that populates it.
var v3ComputerPrestagePrestagePurchasingInformationV2AttrTypes = map[string]attr.Type{
	"apple_care_id":      types.StringType,
	"id":                 types.StringType,
	"lease_date":         types.StringType,
	"leased":             types.BoolType,
	"life_expectancy":    types.Int64Type,
	"po_date":            types.StringType,
	"po_number":          types.StringType,
	"purchase_price":     types.StringType,
	"purchased":          types.BoolType,
	"purchasing_account": types.StringType,
	"purchasing_contact": types.StringType,
	"vendor":             types.StringType,
	"version_lock":       types.Int64Type,
	"warranty_date":      types.StringType,
}

var v3ComputerPrestagePrestagePurchasingInformationV2ObjectType = types.ObjectType{AttrTypes: v3ComputerPrestagePrestagePurchasingInformationV2AttrTypes}
