// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:e29c3c55fac9427f0859dfeab08822cf7cbca1463246f5d9cdeb8393ab9d2a4c). DO NOT EDIT.

package v1_distribution_point

import (
	"context"

	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/services/common/convert"
)

// mapRemoteStateToTerraform maps the API's response onto Terraform state.
//
// This function replaces what a reflection-based provider does at runtime. Being
// generated code, a field whose conversion is wrong is a compile error rather
// than a surprise during apply.
func mapRemoteStateToTerraform(ctx context.Context, data *V1DistributionPointResourceModel, remote models.DistributionPointable) {
	if remote == nil {
		tflog.Debug(ctx, "remote resource is nil, leaving state untouched", map[string]any{
			"resource": TypeName,
		})
		return
	}

	data.BackupDistributionPointID = convert.PtrStringToFramework(remote.GetBackupDistributionPointId())
	data.EnableLoadBalancing = convert.PtrBoolToFramework(remote.GetEnableLoadBalancing())
	data.FileSharingConnectionType = convert.PtrStringerToFramework(remote.GetFileSharingConnectionType())
	data.HTTPSContext = convert.PtrStringToFramework(remote.GetHttpsContext())
	data.HTTPSEnabled = convert.PtrBoolToFramework(remote.GetHttpsEnabled())
	data.HTTPSPassword = convert.PtrStringToFramework(remote.GetHttpsPassword())
	data.HTTPSPort = convert.PtrInt32ToFrameworkInt64(remote.GetHttpsPort())
	data.HTTPSSecurityType = convert.PtrStringerToFramework(remote.GetHttpsSecurityType())
	data.HTTPSUsername = convert.PtrStringToFramework(remote.GetHttpsUsername())
	data.ID = convert.PtrStringToFramework(remote.GetId())
	data.LocalPathToShare = convert.PtrStringToFramework(remote.GetLocalPathToShare())
	data.Name = convert.PtrStringToFramework(remote.GetName())
	data.Port = convert.PtrInt32ToFrameworkInt64(remote.GetPort())
	data.Principal = convert.PtrBoolToFramework(remote.GetPrincipal())
	data.ReadOnlyPassword = convert.PtrStringToFramework(remote.GetReadOnlyPassword())
	data.ReadOnlyUsername = convert.PtrStringToFramework(remote.GetReadOnlyUsername())
	data.ReadWritePassword = convert.PtrStringToFramework(remote.GetReadWritePassword())
	data.ReadWriteUsername = convert.PtrStringToFramework(remote.GetReadWriteUsername())
	data.ServerName = convert.PtrStringToFramework(remote.GetServerName())
	data.ShareName = convert.PtrStringToFramework(remote.GetShareName())
	data.SshPassword = convert.PtrStringToFramework(remote.GetSshPassword())
	data.SshUsername = convert.PtrStringToFramework(remote.GetSshUsername())
	data.Workgroup = convert.PtrStringToFramework(remote.GetWorkgroup())

	tflog.Debug(ctx, "mapped remote state", map[string]any{"resource": TypeName})
}
