// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package preview

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// RemoteAdministrationConfigurationsRequestBuilder builds and executes requests for operations under \preview\remote-administration-configurations
type RemoteAdministrationConfigurationsRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// RemoteAdministrationConfigurationsRequestBuilderGetQueryParameters remote administration feature creates a secure screen-sharing experience between Jamf Pro administrators and their end-users.
type RemoteAdministrationConfigurationsRequestBuilderGetQueryParameters struct {
	Page     *int32 "uriparametername:\"page\""
	PageSize *int32 "uriparametername:\"page%2Dsize\""
}

// NewRemoteAdministrationConfigurationsRequestBuilderInternal instantiates a new RemoteAdministrationConfigurationsRequestBuilder and sets the default values.
func NewRemoteAdministrationConfigurationsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *RemoteAdministrationConfigurationsRequestBuilder {
	m := &RemoteAdministrationConfigurationsRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/preview/remote-administration-configurations{?page*,page%2Dsize*}", pathParameters),
	}
	return m
}

// NewRemoteAdministrationConfigurationsRequestBuilder instantiates a new RemoteAdministrationConfigurationsRequestBuilder and sets the default values.
func NewRemoteAdministrationConfigurationsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *RemoteAdministrationConfigurationsRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewRemoteAdministrationConfigurationsRequestBuilderInternal(urlParams, requestAdapter)
}

// Get remote administration feature creates a secure screen-sharing experience between Jamf Pro administrators and their end-users.
// returns a RemoteAdministrationSearchResultsable when successful
// returns a ApiError error when the service returns a 404 status code
func (m *RemoteAdministrationConfigurationsRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[RemoteAdministrationConfigurationsRequestBuilderGetQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.RemoteAdministrationSearchResultsable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"404": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateRemoteAdministrationSearchResultsFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.RemoteAdministrationSearchResultsable), nil
}

// TeamViewer the teamViewer property
// returns a *RemoteAdministrationConfigurationsTeamViewerRequestBuilder when successful
func (m *RemoteAdministrationConfigurationsRequestBuilder) TeamViewer() *RemoteAdministrationConfigurationsTeamViewerRequestBuilder {
	return NewRemoteAdministrationConfigurationsTeamViewerRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}

// ToGetRequestInformation remote administration feature creates a secure screen-sharing experience between Jamf Pro administrators and their end-users.
// returns a *RequestInformation when successful
func (m *RemoteAdministrationConfigurationsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[RemoteAdministrationConfigurationsRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *RemoteAdministrationConfigurationsRequestBuilder when successful
func (m *RemoteAdministrationConfigurationsRequestBuilder) WithUrl(rawUrl string) *RemoteAdministrationConfigurationsRequestBuilder {
	return NewRemoteAdministrationConfigurationsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
