// Code generated by tfpfgen from blueprints/thousandeyes-kiota
// (sha256:4dc9a6901b2eeec6365c29acf7cbcae4f13e44b4a43885ff5f9d060be3e7b5d3). DO NOT EDIT.

package user

import (
	"context"

	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes-kiota/internal/sdk/models"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes-kiota/internal/services/common/convert"
)

// mapRemoteStateToTerraform maps the API's response onto Terraform state.
//
// This function replaces what a reflection-based provider does at runtime. Being
// generated code, a field whose conversion is wrong is a compile error rather
// than a surprise during apply.
func mapRemoteStateToTerraform(ctx context.Context, data *UserResourceModel, remote models.Administrative_API_UserDetailable) {
	if remote == nil {
		tflog.Debug(ctx, "remote resource is nil, leaving state untouched", map[string]any{
			"resource": TypeName,
		})
		return
	}

	data.DateRegistered = convert.PtrTimeToFramework(remote.GetDateRegistered())
	data.Email = convert.PtrStringToFramework(remote.GetEmail())
	data.LastLogin = convert.PtrTimeToFramework(remote.GetLastLogin())
	data.Name = convert.PtrStringToFramework(remote.GetName())
	data.ID = convert.PtrStringToFramework(remote.GetUid())

	tflog.Debug(ctx, "mapped remote state", map[string]any{"resource": TypeName})
}
