// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:e29c3c55fac9427f0859dfeab08822cf7cbca1463246f5d9cdeb8393ab9d2a4c). DO NOT EDIT.

package v1_api_role

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// V1APIRoleResourceModel is the Terraform state for a jamfpro_v1_api_role.
//
// Field order follows the schema, and the timeouts value is last.
type V1APIRoleResourceModel struct {
	DisplayName types.String   `tfsdk:"display_name"`
	ID          types.String   `tfsdk:"id"`
	Privileges  types.Set      `tfsdk:"privileges"`
	Timeouts    timeouts.Value `tfsdk:"timeouts"`
}
