# Code generated by tfpfgen from blueprints/thousandeyes-kiota
# (sha256:c2cf76ac3103c3952bf7293d203903e0fe737bf6f5557c9886edf186808f4c22). DO NOT EDIT.

# The smallest configuration this resource accepts: its required attributes and nothing else.
#
# Regenerated, so it follows the schema. If the API starts requiring a field, this file gains it
# on the next emit rather than an acceptance run discovering it.

resource "thousandeyes_endpoint_label" "test" {
  # Where a value came from. A fixture takes what the API was observed to accept, not the first
  # value the specification documents -- which is the opposite of how a generated validator is
  # built. A validator errs toward permitting, because blocking a configuration the API would
  # have taken is a harm nobody can work around; a fixture errs toward working, because it is an
  # input rather than a contract.
  #
  # filters: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # match_type: observed accepted
  filters    = [{ key = "platform", mode = "in", values = ["windows"] }]
  match_type = "and"
  name       = "tfacc-name"
}
