// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:92588417fa010d48e3954c780a1c7284689923c40fd60ea7464f85cbc75b43eb). DO NOT EDIT.

package v1_building

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// V1BuildingDataSourceModel is the Terraform state for a jamfpro_v1_building.
//
// Field order follows the schema, and the timeouts value is last.
type V1BuildingDataSourceModel struct {
	City           types.String   `tfsdk:"city"`
	Country        types.String   `tfsdk:"country"`
	ID             types.String   `tfsdk:"id"`
	Name           types.String   `tfsdk:"name"`
	StateProvince  types.String   `tfsdk:"state_province"`
	StreetAddress1 types.String   `tfsdk:"street_address1"`
	StreetAddress2 types.String   `tfsdk:"street_address2"`
	ZipPostalCode  types.String   `tfsdk:"zip_postal_code"`
	Timeouts       timeouts.Value `tfsdk:"timeouts"`
}
