// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:e9fc089728e964a2ce1adf1c51444126c782ff30e172933b5177fd9a4982f6db). DO NOT EDIT.

package tests_dns_server

import (
	"context"

	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/thousandeyes_api/dns_server_tests"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/services/common/convert"
)

// mapRemoteStateToTerraform maps the API's response onto Terraform state.
//
// This function replaces what a reflection-based provider does at runtime. Being
// generated code, a field whose conversion is wrong is a compile error rather
// than a surprise during apply.
func mapRemoteStateToTerraform(ctx context.Context, data *TestsDNSServerResourceModel, remote *dns_server_tests.DnsServerTestResponse) {
	if remote == nil {
		tflog.Debug(ctx, "remote resource is nil, leaving state untouched", map[string]any{
			"resource": ResourceName,
		})
		return
	}

	data.AlertsEnabled = convert.PtrBoolToFramework(remote.AlertsEnabled)
	data.BandwidthMeasurements = convert.NamedBoolToFramework(remote.BandwidthMeasurements)
	data.BGPMeasurements = convert.NamedBoolToFramework(remote.BgpMeasurements)
	data.CreatedBy = convert.EnumToFramework(remote.CreatedBy)
	data.CreatedDate = convert.EnumToFramework(remote.CreatedDate)
	data.Description = convert.PtrStringToFramework(remote.Description)
	data.DNSQueryClass = convert.EnumToFramework(remote.DnsQueryClass)
	data.DNSTransportProtocol = convert.EnumToFramework(remote.DnsTransportProtocol)
	data.Enabled = convert.NamedBoolToFramework(remote.Enabled)
	data.FixedPacketRate = convert.IntEnumToFramework(remote.FixedPacketRate)
	data.Interval = convert.IntEnumToFramework(remote.Interval)
	data.Ipv6Policy = convert.EnumToFramework(remote.Ipv6Policy)
	data.LiveShare = convert.PtrBoolToFramework(remote.LiveShare)
	data.ModifiedBy = convert.PtrStringToFramework(remote.ModifiedBy)
	data.ModifiedDate = convert.PtrStringToFramework(remote.ModifiedDate)
	data.MTUMeasurements = convert.NamedBoolToFramework(remote.MtuMeasurements)
	data.NetworkMeasurements = convert.NamedBoolToFramework(remote.NetworkMeasurements)
	data.NumPathTraces = convert.IntEnumToFramework(remote.NumPathTraces)
	data.PathTraceMode = convert.EnumToFramework(remote.PathTraceMode)
	data.ProbeMode = convert.EnumToFramework(remote.ProbeMode)
	data.Protocol = convert.EnumToFramework(remote.Protocol)
	data.RandomizedStartTime = convert.NamedBoolToFramework(remote.RandomizedStartTime)
	data.RecursiveQueries = convert.PtrBoolToFramework(remote.RecursiveQueries)
	data.SavedEvent = convert.PtrBoolToFramework(remote.SavedEvent)
	data.ID = convert.PtrStringToFramework(remote.TestID)
	data.TestName = convert.PtrStringToFramework(remote.TestName)
	data.Type = convert.PtrStringToFramework(remote.Type)
	data.UsePublicBGP = convert.NamedBoolToFramework(remote.UsePublicBGP)

	tflog.Debug(ctx, "mapped remote state", map[string]any{"resource": ResourceName})
}
