// Code generated by tfpfgen from blueprints/thousandeyes
// (sha256:03f1a9d1deee1e76e51e48dbbc071404c0737e7a841d85bcad5a9c27643a1e84). DO NOT EDIT.

package tests_page_load

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/thousandeyes_api/page_load_tests"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/services/common/convert"
)

// mapRemoteStateToTerraform maps the API's response onto Terraform state.
//
// This function replaces what a reflection-based provider does at runtime. Being
// generated code, a field whose conversion is wrong is a compile error rather
// than a surprise during apply.
func mapRemoteStateToTerraform(ctx context.Context, data *TestsPageLoadResourceModel, remote *page_load_tests.PageLoadTestResponse) diag.Diagnostics {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)

	if remote == nil {
		tflog.Debug(ctx, "remote resource is nil, leaving state untouched", map[string]any{
			"resource": TypeName,
		})
		return diags
	}

	data.AlertsEnabled = convert.PtrBoolToFramework(remote.AlertsEnabled)
	data.AllowGeolocation = convert.NamedBoolToFramework(remote.AllowGeolocation)
	data.AllowMicAndCamera = convert.NamedBoolToFramework(remote.AllowMicAndCamera)
	data.AllowUnsafeLegacyRenegotiation = convert.NamedBoolToFramework(remote.AllowUnsafeLegacyRenegotiation)
	data.AuthType = convert.EnumToFramework(remote.AuthType)
	data.BandwidthMeasurements = convert.NamedBoolToFramework(remote.BandwidthMeasurements)
	data.BGPMeasurements = convert.NamedBoolToFramework(remote.BgpMeasurements)
	data.BlockDomains = convert.EnumToFramework(remote.BlockDomains)
	data.BrowserLanguage = convert.EnumToFramework(remote.BrowserLanguage)
	data.ChromeOptions = convert.EnumToFramework(remote.ChromeOptions)
	data.ClientCertificate = convert.EnumToFramework(remote.ClientCertificate)
	data.CollectProxyNetworkData = convert.NamedBoolToFramework(remote.CollectProxyNetworkData)
	data.ContentRegex = convert.PtrStringToFramework(remote.ContentRegex)
	data.CreatedBy = convert.EnumToFramework(remote.CreatedBy)
	data.CreatedDate = convert.EnumToFramework(remote.CreatedDate)
	data.Description = convert.PtrStringToFramework(remote.Description)
	data.DesiredStatusCode = convert.EnumToFramework(remote.DesiredStatusCode)
	data.DisableScreenshot = convert.NamedBoolToFramework(remote.DisableScreenshot)
	data.DistributedTracing = convert.NamedBoolToFramework(remote.DistributedTracing)
	data.EmulatedDeviceID = convert.PtrStringToFramework(remote.EmulatedDeviceID)
	data.Enabled = convert.NamedBoolToFramework(remote.Enabled)
	data.FixedPacketRate = convert.IntEnumToFramework(remote.FixedPacketRate)
	data.FollowRedirects = convert.NamedBoolToFramework(remote.FollowRedirects)
	data.HTTPInterval = convert.IntEnumToFramework(remote.HttpInterval)
	data.HTTPTargetTime = convert.IntEnumToFramework(remote.HttpTargetTime)
	data.HTTPTimeLimit = convert.IntEnumToFramework(remote.HttpTimeLimit)
	data.HTTPVersion = convert.IntEnumToFramework(remote.HttpVersion)
	data.IdentifyAgentTrafficWithUserAgent = convert.NamedBoolToFramework(remote.IdentifyAgentTrafficWithUserAgent)
	data.IncludeHeaders = convert.NamedBoolToFramework(remote.IncludeHeaders)
	data.Interval = convert.IntEnumToFramework(remote.Interval)
	data.LiveShare = convert.PtrBoolToFramework(remote.LiveShare)
	data.ModifiedBy = convert.PtrStringToFramework(remote.ModifiedBy)
	data.ModifiedDate = convert.PtrStringToFramework(remote.ModifiedDate)
	data.MTUMeasurements = convert.NamedBoolToFramework(remote.MtuMeasurements)
	data.NetworkMeasurements = convert.NamedBoolToFramework(remote.NetworkMeasurements)
	data.NumPathTraces = convert.IntEnumToFramework(remote.NumPathTraces)
	data.OverrideAgentProxy = convert.NamedBoolToFramework(remote.OverrideAgentProxy)
	data.OverrideProxyID = convert.EnumToFramework(remote.OverrideProxyID)
	data.PageLoadTargetTime = convert.PtrInt64ToFramework(remote.PageLoadTargetTime)
	data.PageLoadTimeLimit = convert.IntEnumToFramework(remote.PageLoadTimeLimit)
	data.PageLoadingStrategy = convert.EnumToFramework(remote.PageLoadingStrategy)
	data.Password = convert.EnumToFramework(remote.Password)
	data.PathTraceMode = convert.EnumToFramework(remote.PathTraceMode)
	data.ProbeMode = convert.EnumToFramework(remote.ProbeMode)
	data.Protocol = convert.EnumToFramework(remote.Protocol)
	data.RandomizedStartTime = convert.NamedBoolToFramework(remote.RandomizedStartTime)
	data.SavedEvent = convert.PtrBoolToFramework(remote.SavedEvent)
	data.SSLVersion = convert.EnumToFramework(remote.SslVersion)
	data.SSLVersionID = convert.EnumToFramework(remote.SslVersionID)
	data.Subinterval = convert.IntEnumToFramework(remote.Subinterval)
	data.ID = convert.PtrStringToFramework(remote.TestID)
	data.TestName = convert.PtrStringToFramework(remote.TestName)
	data.Type = convert.EnumToFramework(remote.Type)
	data.URL = convert.EnumToFramework(remote.URL)
	data.UseNtlm = convert.NamedBoolToFramework(remote.UseNtlm)
	data.UsePublicBGP = convert.NamedBoolToFramework(remote.UsePublicBGP)
	data.UserAgent = convert.EnumToFramework(remote.UserAgent)
	data.Username = convert.EnumToFramework(remote.Username)
	data.VaultCredentials, d = flattenTestsPageLoadTestVaultCredentials(ctx, remote.VaultCredentials)
	diags.Append(d...)
	data.VerifyCertificate = convert.NamedBoolToFramework(remote.VerifyCertificate)

	tflog.Debug(ctx, "mapped remote state", map[string]any{"resource": TypeName})

	return diags
}

// flattenTestsPageLoadTestVaultCredentials converts SDK structs into the framework value state holds.
func flattenTestsPageLoadTestVaultCredentials(ctx context.Context, in []page_load_tests.TestVaultCredential) (types.Set, diag.Diagnostics) {
	var diags diag.Diagnostics

	// A nil slice is null and an empty slice is empty. Conflating them produces a
	// diff no configuration change can resolve.
	if in == nil {
		return types.SetNull(testsPageLoadTestVaultCredentialObjectType), diags
	}

	models := make([]TestsPageLoadTestVaultCredentialModel, 0, len(in))
	for _, item := range in {
		var m TestsPageLoadTestVaultCredentialModel

		m.SecretID = convert.PtrStringToFramework(item.SecretID)
		m.Target = convert.EnumToFramework(item.Target)
		models = append(models, m)
	}

	out, d2 := types.SetValueFrom(ctx, testsPageLoadTestVaultCredentialObjectType, models)
	diags.Append(d2...)

	return out, diags
}
