# Code generated by tfpfgen from blueprints/thousandeyes-kiota
# (sha256:c2cf76ac3103c3952bf7293d203903e0fe737bf6f5557c9886edf186808f4c22). DO NOT EDIT.

# The action under test, invoked once by a terraform_data trigger on create. The
# subject's identifier arrives as a variable, supplied by the generated test from the
# environment -- an action's subject frequently cannot be created by Terraform.

variable "agent_id" {
  type = string
}

action "thousandeyes_disable_endpoint_agent" "test" {
  config {
    agent_id = var.agent_id
  }
}

resource "terraform_data" "trigger" {
  lifecycle {
    action_trigger {
      events  = [after_create]
      actions = [action.thousandeyes_disable_endpoint_agent.test]
    }
  }
}
