// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:92588417fa010d48e3954c780a1c7284689923c40fd60ea7464f85cbc75b43eb). DO NOT EDIT.

package v1_api_integration

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/services/common/convert"
)

// mapRemoteStateToTerraform maps the API's response onto Terraform state.
//
// This function replaces what a reflection-based provider does at runtime. Being
// generated code, a field whose conversion is wrong is a compile error rather
// than a surprise during apply.
func mapRemoteStateToTerraform(ctx context.Context, data *V1APIIntegrationResourceModel, remote models.ApiIntegrationResponseable) diag.Diagnostics {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)

	if remote == nil {
		tflog.Debug(ctx, "remote resource is nil, leaving state untouched", map[string]any{
			"resource": TypeName,
		})
		return diags
	}

	data.AccessTokenLifetimeSeconds = convert.PtrInt32ToFrameworkInt64(remote.GetAccessTokenLifetimeSeconds())
	data.AppType = convert.PtrStringerToFramework(remote.GetAppType())
	data.AuthorizationScopes, d = convert.StringSliceToFrameworkSet(ctx, remote.GetAuthorizationScopes())
	diags.Append(d...)
	data.ClientID = convert.PtrStringToFramework(remote.GetClientId())
	data.DisplayName = convert.PtrStringToFramework(remote.GetDisplayName())
	data.Enabled = convert.PtrBoolToFramework(remote.GetEnabled())
	data.ID = convert.PtrInt32ToFrameworkInt64(remote.GetId())

	tflog.Debug(ctx, "mapped remote state", map[string]any{"resource": TypeName})

	return diags
}
