package render

import (
	"fmt"
	"strings"

	"github.com/deploymenttheory/terraform-plugin-framework-codegen/internal/blueprint"
)

// maxNestDepth is a runaway guard, not a design limit.
//
// Nesting is generated to whatever depth a blueprint declares: four levels is routine in
// terraform-provider-microsoft365, and each level needs nothing the first level did not
// already need. The ceiling exists because a blueprint constructed in Go rather than
// loaded from JSON could nest into itself, and a generator that recurses forever gives a
// stack trace instead of a diagnostic.
//
// Ten is above any hand-written schema in the reference provider. The one case that
// exceeds it is a settings catalogue whose depth is sized at runtime from the
// practitioner's own configuration, up to fifteen levels. That shape is not expressible
// in this IR at all -- it is not a fixed schema -- so it is refused here by name rather
// than half-emitted.
const maxNestDepth = 10

// nestedShapes collects every nested object shape a schema declares, at any depth.
//
// Order is pre-order over the declaration order: an object appears before the objects
// nested inside it. Go initialises package-level vars by dependency rather than by
// position, so the order is for the reader rather than the compiler -- but it must be
// deterministic, because the drift check compares generated bytes.
func nestedShapes(sc schemaScope, s blueprint.Schema) ([]nestedShape, error) {
	var out []nestedShape

	// Each generated identifier is claimed once. At one level of nesting a collision was
	// unlikely; at four, two different objects called "ItemModel" is an easy mistake, and
	// it would emit two declarations of the same type.
	claimed := map[string]string{}

	if err := collectShapes(sc, s.Attributes, "", 1, claimed, &out); err != nil {
		return nil, err
	}

	return out, nil
}

type nestedShape struct {
	attr   blueprint.Attribute
	nested blueprint.NestedAttributeObject
	// path is the dotted attribute path to this object, for error messages.
	path string
}

func collectShapes(
	sc schemaScope,
	attrs []blueprint.Attribute,
	path string,
	depth int,
	claimed map[string]string,
	out *[]nestedShape,
) error {
	for _, a := range attrs {
		if a.Drop || !a.Type.Kind.IsNested() {
			continue
		}

		at := a.Name
		if path != "" {
			at = path + "." + a.Name
		}

		if a.Type.NestedObject == nil {
			return &ErrUnsupported{
				What: fmt.Sprintf("attribute %q of %s", at, sc.what),
				Why:  "a nested kind needs a nested object shape",
			}
		}

		if depth > maxNestDepth {
			return &ErrUnsupported{
				What: fmt.Sprintf("attribute %q of %s", at, sc.what),
				Why: fmt.Sprintf(
					"nesting reaches %d levels and the emitter stops at %d; a schema this deep is "+
						"usually one whose depth is decided at runtime, which this IR cannot express -- "+
						"write that resource by hand",
					depth, maxNestDepth,
				),
			}
		}

		n := *a.Type.NestedObject
		if err := claimIdentifiers(sc, at, n, claimed); err != nil {
			return err
		}

		*out = append(*out, nestedShape{attr: a, nested: n, path: at})

		if err := collectShapes(sc, n.Attributes, at, depth+1, claimed, out); err != nil {
			return err
		}
	}

	return nil
}

// claimIdentifiers refuses two nested objects that would declare the same Go identifier.
//
// Every one of these becomes a package-level declaration, so a repeat is a redeclaration
// error in the generated package. Catching it here names both attributes; the compiler
// error names neither.
func claimIdentifiers(
	sc schemaScope,
	at string,
	n blueprint.NestedAttributeObject,
	claimed map[string]string,
) error {
	for _, id := range []struct{ kind, name string }{
		{"goTypeName", n.GoTypeName},
		{"attrTypesVar", n.AttrTypesVar},
		{"objectTypeVar", n.ObjectTypeVar},
		{"expandFunc", n.ExpandFunc},
		{"flattenFunc", n.FlattenFunc},
	} {
		if id.name == "" {
			continue
		}
		if first, ok := claimed[id.name]; ok {
			return &ErrUnsupported{
				What: fmt.Sprintf("attribute %q of %s", at, sc.what),
				Why: fmt.Sprintf(
					"its %s %q is already used by %q; every nested object declares its own "+
						"package-level identifiers, so two objects cannot share one",
					id.kind, id.name, first,
				),
			}
		}
		claimed[id.name] = at
	}

	return nil
}

// nestedAttributeDecl renders a nested attribute's schema declaration.
func nestedAttributeDecl(
	sc schemaScope,
	a blueprint.Attribute,
	imports *importSet,
) (string, error) {
	n := a.Type.NestedObject

	var children []string
	for _, child := range n.Attributes {
		if child.Drop {
			continue
		}
		schemaType, ok := frameworkSchemaType[child.Type.Kind]
		if !ok {
			return "", &ErrUnsupported{
				What: fmt.Sprintf("nested attribute %q", a.Name+"."+child.Name),
				Why:  fmt.Sprintf("type kind %q has no framework mapping", child.Type.Kind),
			}
		}
		decl, err := attributeDecl(sc, child, schemaType, imports)
		if err != nil {
			return "", err
		}
		children = append(children, decl)
	}

	var b strings.Builder

	fmt.Fprintf(&b, "%q: schema.%s{\n", a.Name, frameworkSchemaType[a.Type.Kind])

	// A single nested attribute holds its children directly; a collection wraps
	// them in a nested-object descriptor.
	if a.Type.Kind == blueprint.KindSingleNested {
		b.WriteString("Attributes: map[string]schema.Attribute{\n")
		for _, c := range children {
			fmt.Fprintf(&b, "%s,\n", c)
		}
		b.WriteString("},\n")
	} else {
		b.WriteString(
			"NestedObject: schema.NestedAttributeObject{\nAttributes: map[string]schema.Attribute{\n",
		)
		for _, c := range children {
			fmt.Fprintf(&b, "%s,\n", c)
		}
		b.WriteString("},\n},\n")
	}

	writeAttributeFlags(&b, a)

	if a.MarkdownDescription != "" {
		fmt.Fprintf(&b, "MarkdownDescription: %s,\n", goStringLit(a.MarkdownDescription))
	}
	if a.DeprecationMessage != "" {
		fmt.Fprintf(&b, "DeprecationMessage: %s,\n", goStringLit(a.DeprecationMessage))
	}

	// A nested attribute takes validators and plan modifiers like any other, and
	// dropping a declared one silently is worse than refusing it: the blueprint says the
	// value is constrained and the generated provider does not enforce it.
	writeCustomCodeBlock(
		&b,
		"Validators",
		"validator."+validatorKind(a.Type.Kind),
		a.Validators,
		imports,
	)
	writeCustomCodeBlock(
		&b,
		"PlanModifiers",
		"planmodifier."+validatorKind(a.Type.Kind),
		planModifiersFor(sc, a, imports),
		imports,
	)

	b.WriteString("}")

	return b.String(), nil
}

// nestedModelView builds the sibling model, attr.Type map and object type for one
// nested shape.
func nestedModelView(s nestedShape) (NestedModelView, error) {
	v := NestedModelView{
		GoTypeName:    s.nested.GoTypeName,
		AttrTypesVar:  s.nested.AttrTypesVar,
		ObjectTypeVar: s.nested.ObjectTypeVar,
	}

	for _, child := range s.nested.Attributes {
		if child.Drop {
			continue
		}

		modelType, ok := frameworkModelType[child.Type.Kind]
		if !ok {
			return NestedModelView{}, &ErrUnsupported{
				What: fmt.Sprintf("nested attribute %q", child.Name),
				Why:  fmt.Sprintf("type kind %q has no model mapping", child.Type.Kind),
			}
		}
		v.Fields = append(
			v.Fields,
			fmt.Sprintf("%s %s `tfsdk:%q`", child.GoField, modelType, child.Name),
		)

		attrType, err := attrTypeExpr(child.Type)
		if err != nil {
			return NestedModelView{}, err
		}
		v.AttrTypeEntries = append(v.AttrTypeEntries, fmt.Sprintf("%q: %s,", child.Name, attrType))
	}

	return v, nil
}

// attrTypeExpr renders the attr.Type expression for a type, which the attr.Type
// map of a nested shape needs.
func attrTypeExpr(t blueprint.AttrType) (string, error) {
	if expr, ok := frameworkElemType[t.Kind]; ok {
		return expr, nil
	}

	switch t.Kind {
	case blueprint.KindList, blueprint.KindSet:
		if t.ElementType == nil {
			return "", &ErrUnsupported{What: "collection", Why: "no element type"}
		}
		elem, err := attrTypeExpr(*t.ElementType)
		if err != nil {
			return "", err
		}
		container := "ListType"
		if t.Kind == blueprint.KindSet {
			container = "SetType"
		}
		return fmt.Sprintf("types.%s{ElemType: %s}", container, elem), nil

	case blueprint.KindMap:
		if t.ElementType == nil {
			return "", &ErrUnsupported{What: "map", Why: "no element type"}
		}
		elem, err := attrTypeExpr(*t.ElementType)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("types.MapType{ElemType: %s}", elem), nil

	case blueprint.KindSingleNested, blueprint.KindListNested, blueprint.KindSetNested:
		// A nested object describes itself through the object type var its own model
		// declares, so an outer attr.Type map refers to that rather than restating the
		// shape. Restating it would be a second copy of the same truth, free to drift.
		if t.NestedObject == nil {
			return "", &ErrUnsupported{
				What: fmt.Sprintf("type kind %q", t.Kind),
				Why:  "a nested kind needs a nested object shape to name its object type",
			}
		}
		if t.NestedObject.ObjectTypeVar == "" {
			return "", &ErrUnsupported{
				What: fmt.Sprintf("nested object %q", t.NestedObject.GoTypeName),
				Why:  "it declares no objectTypeVar, so an enclosing attr.Type map cannot refer to it",
			}
		}

		if t.Kind == blueprint.KindSingleNested {
			return t.NestedObject.ObjectTypeVar, nil
		}

		container := "ListType"
		if t.Kind == blueprint.KindSetNested {
			container = "SetType"
		}

		return fmt.Sprintf("types.%s{ElemType: %s}", container, t.NestedObject.ObjectTypeVar), nil

	default:
		return "", &ErrUnsupported{
			What: fmt.Sprintf("type kind %q", t.Kind),
			Why:  "it has no attr.Type expression",
		}
	}
}

// nestedExpandView builds the helper converting a framework collection into SDK
// structs.
func nestedExpandView(s nestedShape) NestedFuncView {
	v := NestedFuncView{
		FuncName:      s.nested.ExpandFunc,
		FrameworkType: frameworkModelType[s.attr.Type.Kind],
		SDKType:       s.nested.SDKType,
		ObjectTypeVar: s.nested.ObjectTypeVar,
		ModelType:     s.nested.GoTypeName,
		IsCollection:  s.attr.Type.Kind.IsNestedCollection(),
	}

	for _, child := range s.nested.Attributes {
		if child.Drop || child.Wire.SkipExpand || child.Wire.Expand == nil {
			continue
		}

		call := *child.Wire.Expand
		if call.ReturnsError {
			// A child conversion that can fail makes the whole helper fallible.
			v.NeedsDiagnostics = true
			v.Assignments = append(v.Assignments, fmt.Sprintf(
				"item.%s, d = %s\ndiags.Append(d...)",
				child.Wire.SDKField, convertExpr(call, "m."+child.GoField)))
			continue
		}
		v.Assignments = append(v.Assignments, fmt.Sprintf("item.%s = %s",
			child.Wire.SDKField, convertExpr(call, "m."+child.GoField)))
	}

	return v
}

// nestedFlattenView builds the helper converting SDK structs into a framework
// collection.
func nestedFlattenView(s nestedShape) NestedFuncView {
	v := NestedFuncView{
		FuncName:      s.nested.FlattenFunc,
		FrameworkType: frameworkModelType[s.attr.Type.Kind],
		SDKType:       s.nested.SDKType,
		ObjectTypeVar: s.nested.ObjectTypeVar,
		ModelType:     s.nested.GoTypeName,
		IsCollection:  s.attr.Type.Kind.IsNestedCollection(),
		Container:     nestedContainer(s.attr.Type.Kind),
	}

	for _, child := range s.nested.Attributes {
		if child.Drop || child.Wire.SkipFlatten || child.Wire.Flatten == nil {
			continue
		}

		call := *child.Wire.Flatten
		if call.ReturnsError {
			v.NeedsDiagnostics = true
			v.Assignments = append(v.Assignments, fmt.Sprintf(
				"m.%s, d = %s\ndiags.Append(d...)",
				child.GoField, convertExpr(call, "item."+child.Wire.SDKField)))
			continue
		}
		v.Assignments = append(v.Assignments, fmt.Sprintf("m.%s = %s",
			child.GoField, convertExpr(call, "item."+child.Wire.SDKField)))
	}

	return v
}

// nestedContainer names the framework container a nested collection flattens into.
//
// Empty for a single nested object, which uses types.Object* rather than a container.
func nestedContainer(k blueprint.TypeKind) string {
	switch k {
	case blueprint.KindListNested:
		return "List"
	case blueprint.KindSetNested:
		return "Set"
	default:
		return ""
	}
}
