# Code generated by tfpfgen from blueprints/thousandeyes-kiota
# (sha256:4dc9a6901b2eeec6365c29acf7cbcae4f13e44b4a43885ff5f9d060be3e7b5d3). DO NOT EDIT.

# The seed resource this data source reads back, then the data block itself. One file,
# because the reference below only resolves against the resource above it.

resource "thousandeyes_tag" "test" {
  key         = "tfacc-ds-tag-key"
  value       = "tfacc-ds-tag-value"
  object_type = "test"
  access_type = "all"
}

data "thousandeyes_tag" "test" {
  id = thousandeyes_tag.test.id
}
