# Code generated by tfpfgen from blueprints/thousandeyes-kiota
# (sha256:fa61b1ea45f4367cd170792e55b26aeda4a622efe66e1cca32fcc31f9b7e8fdf). DO NOT EDIT.

# The smallest configuration this resource accepts: its required attributes and nothing else.
#
# Regenerated, so it follows the schema. If the API starts requiring a field, this file gains it
# on the next emit rather than an acceptance run discovering it.

resource "thousandeyes_credential" "test" {
  name  = "tfacc-name"
  value = "tfacc-value"
}
