// Code generated by tfpluginframeworkgen from blueprints/thousandeyes
// (sha256:cd019f12be32331be882ccdbb92a8c651d1dd5bad8c0cb209bba818d3b11f7b4). DO NOT EDIT.

package tests_dns_trace

import (
	"context"

	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/deploymenttheory/go-sdk-thousandeyes/thousandeyes/thousandeyes_api/dns_trace_tests"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/thousandeyes/internal/services/common/convert"
)

// mapRemoteStateToTerraform maps the API's response onto Terraform state.
//
// This function replaces what a reflection-based provider does at runtime. Being
// generated code, a field whose conversion is wrong is a compile error rather
// than a surprise during apply.
func mapRemoteStateToTerraform(ctx context.Context, data *TestsDNSTraceResourceModel, remote *dns_trace_tests.DnsTraceTestResponse) {
	if remote == nil {
		tflog.Debug(ctx, "remote resource is nil, leaving state untouched", map[string]any{
			"resource": ResourceName,
		})
		return
	}

	data.AlertsEnabled = convert.PtrBoolToFramework(remote.AlertsEnabled)
	data.CreatedBy = convert.EnumToFramework(remote.CreatedBy)
	data.CreatedDate = convert.EnumToFramework(remote.CreatedDate)
	data.Description = convert.PtrStringToFramework(remote.Description)
	data.DNSQueryClass = convert.EnumToFramework(remote.DnsQueryClass)
	data.DNSTransportProtocol = convert.EnumToFramework(remote.DnsTransportProtocol)
	data.Enabled = convert.NamedBoolToFramework(remote.Enabled)
	data.Interval = convert.IntEnumToFramework(remote.Interval)
	data.LiveShare = convert.PtrBoolToFramework(remote.LiveShare)
	data.ModifiedBy = convert.PtrStringToFramework(remote.ModifiedBy)
	data.ModifiedDate = convert.PtrStringToFramework(remote.ModifiedDate)
	data.RandomizedStartTime = convert.NamedBoolToFramework(remote.RandomizedStartTime)
	data.SavedEvent = convert.PtrBoolToFramework(remote.SavedEvent)
	data.ID = convert.PtrStringToFramework(remote.TestID)
	data.TestName = convert.PtrStringToFramework(remote.TestName)
	data.Type = convert.PtrStringToFramework(remote.Type)

	tflog.Debug(ctx, "mapped remote state", map[string]any{"resource": ResourceName})
}
