// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
	"context"

	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// InventoryPreloadRecordsDeleteAllRequestBuilder builds and executes requests for operations under \v2\inventory-preload\records\delete-all
type InventoryPreloadRecordsDeleteAllRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewInventoryPreloadRecordsDeleteAllRequestBuilderInternal instantiates a new InventoryPreloadRecordsDeleteAllRequestBuilder and sets the default values.
func NewInventoryPreloadRecordsDeleteAllRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InventoryPreloadRecordsDeleteAllRequestBuilder {
	m := &InventoryPreloadRecordsDeleteAllRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/inventory-preload/records/delete-all", pathParameters),
	}
	return m
}

// NewInventoryPreloadRecordsDeleteAllRequestBuilder instantiates a new InventoryPreloadRecordsDeleteAllRequestBuilder and sets the default values.
func NewInventoryPreloadRecordsDeleteAllRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *InventoryPreloadRecordsDeleteAllRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewInventoryPreloadRecordsDeleteAllRequestBuilderInternal(urlParams, requestAdapter)
}

// Post deletes all Inventory Preload records.
func (m *InventoryPreloadRecordsDeleteAllRequestBuilder) Post(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) error {
	requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return err
	}
	err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, nil)
	if err != nil {
		return err
	}
	return nil
}

// ToPostRequestInformation deletes all Inventory Preload records.
// returns a *RequestInformation when successful
func (m *InventoryPreloadRecordsDeleteAllRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *InventoryPreloadRecordsDeleteAllRequestBuilder when successful
func (m *InventoryPreloadRecordsDeleteAllRequestBuilder) WithUrl(rawUrl string) *InventoryPreloadRecordsDeleteAllRequestBuilder {
	return NewInventoryPreloadRecordsDeleteAllRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
