// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// LocalAdminPasswordItemAccountItemItemAuditRequestBuilder builds and executes requests for operations under \v2\local-admin-password\{clientManagementId}\account\{username}\{guid}\audit
type LocalAdminPasswordItemAccountItemItemAuditRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// NewLocalAdminPasswordItemAccountItemItemAuditRequestBuilderInternal instantiates a new LocalAdminPasswordItemAccountItemItemAuditRequestBuilder and sets the default values.
func NewLocalAdminPasswordItemAccountItemItemAuditRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *LocalAdminPasswordItemAccountItemItemAuditRequestBuilder {
	m := &LocalAdminPasswordItemAccountItemItemAuditRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/local-admin-password/{clientManagementId}/account/{username}/{guid}/audit", pathParameters),
	}
	return m
}

// NewLocalAdminPasswordItemAccountItemItemAuditRequestBuilder instantiates a new LocalAdminPasswordItemAccountItemItemAuditRequestBuilder and sets the default values.
func NewLocalAdminPasswordItemAccountItemItemAuditRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *LocalAdminPasswordItemAccountItemItemAuditRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewLocalAdminPasswordItemAccountItemItemAuditRequestBuilderInternal(urlParams, requestAdapter)
}

// Get get the full history of all local admin passwords for a specific user guid on a target device. History will include password, who viewed the password and when it was viewed. Get audit history by using the client management id, username, and user guid as the path parameters.
// returns a LapsPasswordAuditsResultsV2able when successful
// returns a ApiError error when the service returns a 400 status code
// returns a ApiError error when the service returns a 500 status code
func (m *LocalAdminPasswordItemAccountItemItemAuditRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.LapsPasswordAuditsResultsV2able, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
		"500": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateLapsPasswordAuditsResultsV2FromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.LapsPasswordAuditsResultsV2able), nil
}

// ToGetRequestInformation get the full history of all local admin passwords for a specific user guid on a target device. History will include password, who viewed the password and when it was viewed. Get audit history by using the client management id, username, and user guid as the path parameters.
// returns a *RequestInformation when successful
func (m *LocalAdminPasswordItemAccountItemItemAuditRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *LocalAdminPasswordItemAccountItemItemAuditRequestBuilder when successful
func (m *LocalAdminPasswordItemAccountItemItemAuditRequestBuilder) WithUrl(rawUrl string) *LocalAdminPasswordItemAccountItemItemAuditRequestBuilder {
	return NewLocalAdminPasswordItemAccountItemItemAuditRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
