// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package v2

import (
	"context"

	id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86 "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// PatchPoliciesPolicyDetailsRequestBuilder builds and executes requests for operations under \v2\patch-policies\policy-details
type PatchPoliciesPolicyDetailsRequestBuilder struct {
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}

// PatchPoliciesPolicyDetailsRequestBuilderGetQueryParameters retrieves a list of patch policies.
type PatchPoliciesPolicyDetailsRequestBuilderGetQueryParameters struct {
	// Query in the RSQL format, allowing to filter Patch Policy collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: id, name, enabled, targetPatchVersion, deploymentMethod, softwareTitleId, softwareTitleConfigurationId, killAppsDelayMinutes, killAppsMessage, isDowngrade, isPatchUnknownVersion, notificationHeader, selfServiceEnforceDeadline, selfServiceDeadline, installButtonText, selfServiceDescription, iconId, reminderFrequency, reminderEnabled. This param can be combined with paging and sorting.
	Filter   *string "uriparametername:\"filter\""
	Page     *int32  "uriparametername:\"page\""
	PageSize *int32  "uriparametername:\"page%2Dsize\""
	// Sorting criteria in the format: property:asc/desc. Default sort is id:asc. Multiple sort criteria are supported and must be separated with a comma.
	Sort []string "uriparametername:\"sort\""
}

// NewPatchPoliciesPolicyDetailsRequestBuilderInternal instantiates a new PatchPoliciesPolicyDetailsRequestBuilder and sets the default values.
func NewPatchPoliciesPolicyDetailsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *PatchPoliciesPolicyDetailsRequestBuilder {
	m := &PatchPoliciesPolicyDetailsRequestBuilder{
		BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/v2/patch-policies/policy-details{?filter*,page*,page%2Dsize*,sort*}", pathParameters),
	}
	return m
}

// NewPatchPoliciesPolicyDetailsRequestBuilder instantiates a new PatchPoliciesPolicyDetailsRequestBuilder and sets the default values.
func NewPatchPoliciesPolicyDetailsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter) *PatchPoliciesPolicyDetailsRequestBuilder {
	urlParams := make(map[string]string)
	urlParams["request-raw-url"] = rawUrl
	return NewPatchPoliciesPolicyDetailsRequestBuilderInternal(urlParams, requestAdapter)
}

// Get retrieves a list of patch policies.
// returns a PatchPolicyDetailsable when successful
// returns a ApiError error when the service returns a 400 status code
func (m *PatchPoliciesPolicyDetailsRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[PatchPoliciesPolicyDetailsRequestBuilderGetQueryParameters]) (id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.PatchPolicyDetailsable, error) {
	requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration)
	if err != nil {
		return nil, err
	}
	errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings{
		"400": id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreateApiErrorFromDiscriminatorValue,
	}
	res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.CreatePatchPolicyDetailsFromDiscriminatorValue, errorMapping)
	if err != nil {
		return nil, err
	}
	if res == nil {
		return nil, nil
	}
	return res.(id94bf7d41e66c7d4a6e9754bb7cc3d7dceacd2b73aa533f1ebddf2bb302e1d86.PatchPolicyDetailsable), nil
}

// ToGetRequestInformation retrieves a list of patch policies.
// returns a *RequestInformation when successful
func (m *PatchPoliciesPolicyDetailsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[PatchPoliciesPolicyDetailsRequestBuilderGetQueryParameters]) (*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
	requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
	i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
	requestInfo.Headers.TryAdd("Accept", "application/json")
	return requestInfo, nil
}

// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *PatchPoliciesPolicyDetailsRequestBuilder when successful
func (m *PatchPoliciesPolicyDetailsRequestBuilder) WithUrl(rawUrl string) *PatchPoliciesPolicyDetailsRequestBuilder {
	return NewPatchPoliciesPolicyDetailsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter)
}
