// Code generated by tfpfgen from blueprints/thousandeyes-kiota
// (sha256:c07c86d8b45cc559bad4f63740c908d3e2b3c0b6c06e40890fbf75ef49fe393f). DO NOT EDIT.

package role

import (
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// RoleResourceModel is the Terraform state for a thousandeyes_role.
//
// Field order follows the schema, and the timeouts value is last.
type RoleResourceModel struct {
	IsBuiltin   types.Bool     `tfsdk:"is_builtin"`
	Name        types.String   `tfsdk:"name"`
	Permissions types.Set      `tfsdk:"permissions"`
	ID          types.String   `tfsdk:"id"`
	Timeouts    timeouts.Value `tfsdk:"timeouts"`
}
