// Code generated by tfpfgen from blueprints/jamfpro
// (sha256:e29c3c55fac9427f0859dfeab08822cf7cbca1463246f5d9cdeb8393ab9d2a4c). DO NOT EDIT.

package v1_mobile_device_extension_attribute

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	models "github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/sdk/models"
	"github.com/deploymenttheory/terraform-plugin-framework-codegen/pilot/jamfpro/internal/services/common/convert"
)

// mapRemoteStateToTerraform maps the API's response onto Terraform state.
//
// This function replaces what a reflection-based provider does at runtime. Being
// generated code, a field whose conversion is wrong is a compile error rather
// than a surprise during apply.
func mapRemoteStateToTerraform(ctx context.Context, data *V1MobileDeviceExtensionAttributeResourceModel, remote models.MobileDeviceExtensionAttributesable) diag.Diagnostics {
	var (
		diags diag.Diagnostics
		d     diag.Diagnostics
	)

	if remote == nil {
		tflog.Debug(ctx, "remote resource is nil, leaving state untouched", map[string]any{
			"resource": TypeName,
		})
		return diags
	}

	data.DataType = convert.PtrStringerToFramework(remote.GetDataType())
	data.Description = convert.PtrStringToFramework(remote.GetDescription())
	data.ID = convert.PtrStringToFramework(remote.GetId())
	data.InputType = convert.PtrStringerToFramework(remote.GetInputType())
	data.InventoryDisplayType = convert.PtrStringerToFramework(remote.GetInventoryDisplayType())
	data.LdapAttributeMapping = convert.PtrStringToFramework(remote.GetLdapAttributeMapping())
	data.LdapExtensionAttributeAllowed = convert.PtrBoolToFramework(remote.GetLdapExtensionAttributeAllowed())
	data.Name = convert.PtrStringToFramework(remote.GetName())
	data.PopupMenuChoices, d = convert.StringSliceToFrameworkSet(ctx, remote.GetPopupMenuChoices())
	diags.Append(d...)

	tflog.Debug(ctx, "mapped remote state", map[string]any{"resource": TypeName})

	return diags
}
