# Code generated by tfpluginframeworkgen from blueprints/thousandeyes
# (sha256:34641e38d86861908506361741dc13945137d4be4706350b91de515c0979fdc0). DO NOT EDIT.

# The widest configuration the evidence supports: every writable attribute with a derivable
# value, chosen by the same derivation the rehearsal probe sends to the live API.
#
# Regenerated and policed, deliberately. This file used to be a hand-owned scaffold, and
# hand edits are how its values drifted from the generated assertions -- the checks derive
# from the blueprint, so the blueprint is where a value is corrected: an accFixture hint for
# something only a human knows, recorded behaviour for everything the probe observed. What
# could not be derived is listed inside the block, each with the reason.

resource "thousandeyes_tests_dnssec" "test" {
  # Where a value came from.
  #
  # alerts_enabled: the API's own default, so a value it is known to accept
  #
  # dns_query_class: documented; unprobed
  #
  # domain: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # enabled: the API's own default, so a value it is known to accept
  #
  # interval: curated in the blueprint's accFixture; the generator cannot derive it
  #
  # randomized_start_time: the API's own default, so a value it is known to accept
  #
  # agents: curated in the blueprint's accFixture; the generator cannot derive it
  alerts_enabled        = true
  description           = "tfacc-description"
  dns_query_class       = "in"
  domain                = "cloudflare.com"
  enabled               = true
  interval              = 3600
  randomized_start_time = false
  test_name             = "tfacc-test-name"
  agents                = [{ agent_id = "3" }]
}
